### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by theduke** [microsoft/mimalloc#10]
After instinctively running `make test`, I discovered that the main cmake targets don't include tests.

The tests in `./test` are rather ... sparse.

Seems like this might be an good thing to work on in the future. ;)

**Comment by daanx** [comment]
Yes, it would be nice to have a structured test framework for the full API. However, testing allocators is very hard as only specific allocation patterns may lead to bugs. The way we chose to tackle this in mimalloc is to have extensive invariant checking in the code, for example:
<https://github.com/microsoft/mimalloc/blob/master/src/page.c#L72>
where all invariants on a page are checked. When building in debug mode, with the cmake option 
`-DCHECK_FULL=ON` all these invariant checks are done on every free and allocation. We then run the 
[mimalloc-bench](https://github.com/daanx/mimalloc-bench) test (and SpecMark and other programs) on this to extensively check if the heap state is always valid. 
I would like to add regular unit tests though for the functional testing of the whole API surface.

**Comment by degski** [comment]
@daanx Regarding tests, is it normal I get:

    heap stats:     peak      total      freed       unit      count
       elapsed:     0.000 s
       process: user: 0.000 s, system: 0.016 s, faults: 644, reclaims: 0, rss: 2.2 mb

**Comment by daanx** [comment]
I added a new test target on the latest dev branch so do more API surface checks. The strategy is outlined in the new `test/readme.md`:

Testing allocators is difficult as bugs may only surface after particular
allocation patterns. The main approach to testing _mimalloc_ is therefore
to have extensive internal invariant checking (see `page_is_valid` in `page.c`
for example), which is enabled in debug mode with `-DMI_CHECK_FULL=ON`.
The main testing strategy is then to run [`mimalloc-bench`][bench] using full
invariant checking to catch any potential problems over a wide range of intensive
allocation benchmarks and programs.

However, this does not test well for the entire API surface and this is tested
with `test-api.c` when using `make test` (from `out/debug` etc). (This is
not complete yet, please add to it.)

The `main.c` and `main-override.c` are there to test if building and overriding
from a local install works and therefore these build a separate `test/CMakeLists.txt`.

[bench]: https://github.com/daanx/mimalloc-bench
