### ISSUE TITLE
Leak of memory mappings + memory leak.

### ISSUE THREAD

**Issue by alexey-milovidov** [microsoft/mimalloc#100]
We run a simple test:

https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/tests/mi_malloc_test.cpp

for the following scenario: allocate memory segments of a random medium to large size and keep the total allocated memory within some limit.

If we use jemalloc, the test is using constant number of memory mappings (32) and bounded amount of memory.

If we use mimalloc, the test works much slower but quickly creates huge amount of memory mappings:

```
$ while true; do cat /proc/$(pidof mi_malloc_test)/maps | wc -l; sleep 1; done
0
738
4894
8790
12608
16533
20428
24283
28041
31763
35642
39321
43014
46589
50222
53969
57612
61197
64718
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
65531
```

until it reaches the maximum. After that, it will start to leak memory untill all memory is exhausted.

It happens after about 5 million iterations:

```
$ dbms/src/Common/tests/mi_malloc_test
Total allocations: 1048576
Total allocations: 2097152
Total allocations: 3145728
Total allocations: 4194304
Total allocations: 5242880
Total allocations: 6291456
Total allocations: 7340032
^C
```

**Comment by daanx** [comment]
Ah thanks for finding this! I am looking into it ASAP (-- and amazing how simple the test is that leads to this behaviour).   (I just tried it on windows but it seems stable there)

**Comment by daanx** [comment]
Found it :-)  It was caused due to allocating many "huge" objects larger than 512kb (and not accessing them in the test). This lead mimalloc to use raw mmap for that which is very slow and becomes fragmented.

Now, the good news is that I was already working on better supporting huge allocations -- and if you pull the latest `dev-exp` branch it should be good again. This branch is more experimental but perhaps it is time to integrate parts of it back into `dev` and `master` (also since it just got WASM support thanks to @jedisct1 )

**Comment by daanx** [comment]
(ps. If you are ok, can I grab the test and modify it a bit and add it to the `mimalloc-bench` repository? If so, please add a MIT license on top of the test file so I can easily include  it.)

**Comment by alexey-milovidov** [comment]
> If you are ok, can I grab the test and modify it a bit and add it to the mimalloc-bench repository?

Sure!

> please add a MIT license on top of the test file so I can easily include it.

Ok, I've added a license:
https://github.com/yandex/ClickHouse/blob/master/dbms/src/Common/tests/mi_malloc_test.cpp

**Comment by daanx** [comment]
Thanks Alexey! -- appreciate the test and improving `mimalloc` to work better!

**Comment by Licenser** [comment]
The issue was closed but it's unclear of the memory leak was fixed and my tests seem to indicate it wasn't, could we get some clarification?

**Comment by daanx** [comment]
Ah, I thought this was fixed! I tried to access the test again but the links stopped working -- can you try with the latest `dev` branch if it still fails? If so, please send me the test source again; the plan was to add this to the mimalloc-bench but I didn't get around to it.

**Comment by Licenser** [comment]
I don't have access tot he original test, sorry, I'll see if I can create a simplified case for where I'm seeing it - sadly it's part of a bigger application :(

**Comment by daanx** [comment]
Ah I see. Please try with the latest `dev` branch -- there should be no problems anymore. The `dev` branch is being tested on large internal services and there seem to be no memory leak bugs. But if you do find a problem please write me so we can fix it.

**Comment by Licenser** [comment]
Hi daanx, thanks for the patients and sorry for getting back so late, had to find the time to run some tests. I can confirm that the memory leak is gone in the `dev` branch! :)

**Comment by Licenser** [comment]
looks like stable too after getting dev working and backtracking the steps it turns out there was a issue with the rust crate for mimalloc bumping the crate number not nut the git submodule to the newest version :( sorry about the confusion
