### ISSUE TITLE
Make all the non-exported functions static?

### ISSUE THREAD

**Issue by jedisct1** [microsoft/mimalloc#107]
`mimalloc` supports having everything concatenated via `static.c`, which is great and convenient.

However, symbol visibility attributes don't apply to static libraries (at least on Linux and when compiling to WebAssembly).
So the static library ends up with all the internal symbols being actually visible.

Given that everything can be concatenated, would it make sense to have all the internal symbols defined as `static`?

I've been working on such a change, which required moving a few things around, but more importantly touches almost all functions, so merging other branches becomes virtually impossible.

Still, would you be possibly open to having the internal symbols marked `static`? If this is the case, that can be done when the different branches don't diverge too much.

**Comment by daanx** [comment]
Yes, I like the idea -- it is really a shame that is so tricky to get this right in C.  One neat way around this is to define a new `mi_decl_internal` that normally expands to nothing (like now), but define it as `static` for the `static.c` file.  It does clutter the `mimalloc_internal.h` declarations though :-(

**Comment by jedisct1** [comment]
An `mi_decl_internal` macro looks like the best way to do it, even though we already have quite a lot of function attributes.
