### ISSUE TITLE
Necessary to append padding in struct mi_page_s?

### ISSUE THREAD

**Issue by jserv** [microsoft/mimalloc#108]
In file `include/mimalloc-types.h`, struct `mi_page_s` is defined as following:
```cpp
...
// improve page index calculation
#if MI_INTPTR_SIZE==8
  //void*                 padding[1];        // 10 words on 64-bit
#elif MI_INTPTR_SIZE==4
  void*                 padding[1];          // 12 words on 32-bit
#endif
```

I wonder if it is necessary to append member `padding`. Can it be replaced with compiler extensions such as  `__attribute__((aligned(x))` or `_declspec(align(#)` instead?

**Comment by daanx** [comment]
Yes, that would be nice but there is no easy portable way to do this. For now this is fine as the structure will not change.

**Comment by colesbury** [comment]
@daanx I think the padding comments are incorrect. `sizeof(mi_page_t)` is 88 bytes (11 words) on 64-bit systems. I think it's currently 13 words (with padding) on 32-bit systems.

Out of curiosity, does the padding improve any benchmarks?
