### ISSUE TITLE
make mimalloc allocation functions fail with total object size larger than PTRDIFF_MAX

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/mimalloc#121]
> Memory allocation functions malloc, calloc, realloc, reallocarray, valloc, pvalloc, memalign, and posix_memalign fail now with total object size larger than PTRDIFF_MAX. This is to avoid potential undefined behavior with pointer subtraction within the allocated object, where results might overflow the ptrdiff_t type.

From the glibc 2.30 (latest) update.
https://sourceware.org/ml/libc-announce/2019/msg00001.html
I guess you should update behavior too ?

context: https://trust-in-soft.com/objects-larger-than-ptrdiff_max-bytes/

**Comment by daanx** [comment]
Great suggestion -- implemented in dev 2066e27. Thanks!
