### ISSUE TITLE
Allocated block expansion without relocation

### ISSUE THREAD

**Issue by 2underscores-vic** [microsoft/mimalloc#123]
Hello!

It would be good to have some function like `realloc()` that tries to expand/shrink allocated memory buffer but doesn't try to relocate the block, just returns unsuccessful status when in place reallocation is impossible.

The idea is explained in detail [here](https://github.com/2underscores-vic/realloc4cpp/blob/P0894R1/realloc4cpp.md) (it's a [proposal](https://github.com/cplusplus/papers/issues/123) for ISO C++).

As examples of a possible solution:

[jemalloc](https://github.com/jemalloc/jemalloc) has `xmallocx()` function with the required behaviour (also it returns the real size of the resulting resized allocation as requested in #2).

Windows [HeapReAlloc()](https://docs.microsoft.com/en-us/windows/win32/api/heapapi/nf-heapapi-heaprealloc) function has `HEAP_REALLOC_IN_PLACE_ONLY` flag.

**Comment by daanx** [comment]
Thanks for your feedback. The function [`mi_expand`](https://microsoft.github.io/mimalloc/group__malloc.html#gaaee66a1d483c3e28f585525fb96707e4) seems to do what you suggest.

**Comment by 2underscores-vic** [comment]
AFAICS this function doesn't try to expand anything, just tries to reuse extra allocated space:

```
void* mi_expand(void* p, size_t newsize) mi_attr_noexcept {
  if (p == NULL) return NULL;
  size_t size = mi_usable_size(p);
  if (newsize > size) return NULL;
  return p; // it fits
}
```

Could we have true implementation? Does the library support allocated block expansion at all?

**Comment by daanx** [comment]
Ah I see what you mean. However, the current design often does have more space available.  But at the same time, the design is based on size segregated areas so it does *not* support further in-place expanding of blocks (well, perhaps we could support it for huge objects).
