### ISSUE TITLE
mi_heap_visit_blocks passes the wrong "arg" when visiting areas

### ISSUE THREAD

**Issue by colesbury** [microsoft/mimalloc#124]
The call on line 504 passes "arg" instead of "args->arg"

https://github.com/microsoft/mimalloc/blob/70648635c6ce3cd0f67f5f03e90ba39627e89bed/src/heap.c#L502-L511

"arg" is the pointer to the internal mi_visit_blocks_args_t structure. "args->arg" is the argument provided by the caller.

**Comment by daanx** [comment]
Thanks! Fixed it :-)
