### ISSUE TITLE
Inline code comments: 2mb vs 4mb segment size

### ISSUE THREAD

**Issue by colesbury** [microsoft/mimalloc#128]
The `mi_segment_s` code comment in mimalloc-types.h describes the segment size as 2mb on 64-bit systems. The size is listed elsewhere as 4mb on 64-bit systems, and it seems to be 4mb in practice.

https://github.com/microsoft/mimalloc/blob/cbc826beb598f48099a3b35d6f228103a630085a/include/mimalloc-types.h#L201-L204

Slightly above that the MI_PAGE_HUGE is described as 2mb aligned. I'm not sure if this is intentional. It seems to be 4mb aligned on 64-bit systems. (I guess that means it's also 2mb aligned)

https://github.com/microsoft/mimalloc/blob/cbc826beb598f48099a3b35d6f228103a630085a/include/mimalloc-types.h#L198

**Comment by daanx** [comment]
I'll fix the comments -- everything is 4MiB aligned and in size (`MI_SEGMENT_SIZE`) and they must be as that is how `free` finds the page a pointer belongs to.
