### ISSUE TITLE
Undefined reference to 'clock_gettime()'

### ISSUE THREAD

**Issue by plopresti** [microsoft/mimalloc#139]
Following instructions to build on Linux, the library compiles fine. But the test programs (mimalloc-test-api and mimalloc-test-stress) fail to link for me due to undefined references to clock_gettime().

I worked around this by using:

    cmake -DCMAKE_EXE_LINKER_FLAGS=-lrt ../..

Full disclosure: I am not 100% sure whether this is a problem with mimalloc or with my cmake installation. I am not a cmake expert and do not particularly want to become one...

**Comment by jserv** [comment]
From Linux Programmer's Manual (2017-09-15):
> Link with -lrt (only for glibc versions before 2.17).

And, `librt` is absent on macOS.

**Comment by plopresti** [comment]
Yeah, you caught me still using RHEL 6...

That patch fixes my build; thanks.

Although it does create a dependency on librt in libmimalloc.so itself:

```
$ ldd libmimalloc.so
        linux-vdso.so.1 =>  (0x00007fff6fce9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fec249c9000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fec247c0000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fec2442c000)
        /lib64/ld-linux-x86-64.so.2 (0x00000039e5e00000)
```

The "-lrt" is technically only needed for building the tests.

But this is a very minor wart. Everything does work. Thank you!
