### ISSUE TITLE
A/V in debug build in _mi_deferred_free during mi_process_done

### ISSUE THREAD

**Issue by rzheka** [microsoft/mimalloc#150]
When `NDEBUG` is defined, `mi_process_done()` calls `mi_collect()`, which eventually arrives at `_mi_deferred_free()`. The default heap passed to _mi_deferred_free() at this stage is an empty heap with `heap->tld == NULL` (it's already cleaned-up by `mi_thread_done()`), resulting in A/V when doing `heap->tld->heartbeat++;`.

**Comment by daanx** [comment]
Thanks for the report!  I think it is fixed in with e227341f in the latest `dev` branch.
