### ISSUE TITLE
dev-exp branch fail to compile under vs2019

### ISSUE THREAD

**Issue by kipodon** [microsoft/mimalloc#151]
I get these erros:

2>init.obj : error LNK2019: unresolved external symbol __imp_mi_allocator_init referenced in function mi_process_load
2>init.obj : error LNK2019: unresolved external symbol __imp_mi_allocator_done referenced in function mi_process_done

**Comment by daanx** [comment]
Ah yes, the VS2019 solution in lagging but I'll update it soon! -- I even see a PR is ready for this. (You can always open the VS2017 one in VS2019 too as a workaround).
