### ISSUE TITLE
using std::ifstream crashes mimalloc

### ISSUE THREAD

**Issue by kipodon** [microsoft/mimalloc#152]
Hi,

consider this small program.
I compiled it with vs2019. 
FileName should point to an existing file. (the content is not important, I think)
In my case it was a 60k text file.
what I am doing wrong?

I get this message in debug:

> mimalloc: error: trying to mi_free a pointer that does not point to a valid heap space: 000001D9130C9000
> 
> mimalloc: assertion failed: at "D:\mimalloc\src\options.c":149, _mi_error_message
>   assertion: "false"
> 

Thanks,
Alon.

`int main()
{
    //std::cout << "Hello World!\n";
  int ver = mi_version();

  const TCHAR* FileName = _T("c:\\somefile.txt");

  std::ifstream filestream;
  filestream.open(FileName, std::ios::binary);
  if (!filestream.is_open())
    return -1;
  return 0;

}
`

**Comment by daanx** [comment]
Thanks for the bug report! I just tried this in VS2017 in the `master` and `dev` branch and there are no errors and it works (as it should). (Note that in your example `\s` is an illegal escape sequence and you left out the required header includes). 

I wonder if it is related to VS2019 ? Or did you use another branch?

**Comment by kipodon** [comment]
Hi,
I tried master branch. (dev-exp failed to compile, did not try dev).
I tried now master with vs2017 and it shows the same problem. you can see this better at Debug compilation of both projects (mimalloc and my test)
in Release its does not always reproduce. but even in release, when I debug into mimalloc I see there is a call to mi_free() with a pointer not provided by mi_malloc()  are there additional allocation functions I should look at?
The bad escape sequence is, of course, a typo. if the input file fail to open, you will  not see any problem, as no buffers are allocated.

**Comment by daanx** [comment]
I still cannot repro. Can you checkout the `dev` branch. Then open the vs2017 solution, and set `mimalloc-override-test` as the startup project and replace the `main-override.cpp` with 
```
#include <windows.h>
#include <fstream>
#include <mimalloc.h>

int main()
{
//std::cout << "Hello World!\n";
  int ver = mi_version();

  const TCHAR* FileName = TEXT("..\\..\\..\\src\\segment.c");

  std::ifstream filestream;
  filestream.open(FileName, std::ios::binary);
  if (!filestream.is_open())
    return -1;
  return 0;

}
```
Let me know how it goes. 
Perhaps there is something else going on? In principle the redirection should catch all allocation calls.

**Comment by daanx** [comment]
I installed vs2019 and updated the solutions (and used toolset v142) and still could not repro.
but my windows version is: 10.0.17763 Build 17763  -- I dont see the 1903, perhaps that is the problem as  the redirection depends on the ucrtbase.dll which is perhaps updated? tbc.

**Comment by kipodon** [comment]
Hi,
When added my code to the sample. I could not see the problem.
when I compared the projects I noticed I added mimalloc lib with 
#pragma comment (lib, )
that was a bad idea.
mimalloc should be added as the first libarary.
the crash stopped only after clean and rebuild
it might be good idea to add to the documentation a suggestion to disable incremental linking

Thank you very much for your help. 
this library is great. I could not imagine that a memory allocation library will give me such I huge performance boost.
