### ISSUE TITLE
Benchmark report

### ISSUE THREAD

**Issue by EmuraDaisuke** [microsoft/mimalloc#159]
Hello mimalloc!

I am [KanameShiki](https://github.com/EmuraDaisuke/MemoryAllocator.KanameShiki).
Same memory allocator as you.

I hope that various ideas will merge to create a better memory allocator.
I believe it will benefit all people who use computers.

**Comment by daanx** [comment]
Thank you for the report! I will try to incorporate your allocator (and benchmarks) in the [mimalloc-bench](https://github.com/daanx/mimalloc-bench) benchmark suite :-)
