### ISSUE TITLE
please provide a .pc file

### ISSUE THREAD

**Issue by lu-zero** [microsoft/mimalloc#16]
pkg-config support makes much easier to deal with libraries.

**Comment by daanx** [comment]
Good idea -- I'll look into it.

**Comment by ObiWahn** [comment]
http://dailycommit.blogspot.com/2016/10/how-to-generate-pkg-config-file-with.html -- looks useful

**Comment by daanx** [comment]
I like this idea but I know too litte about `.pc` files. If anyone is interested in supporting this for `mimalloc` please submit a PR
