### ISSUE TITLE
manual symlink

### ISSUE THREAD

**Issue by gramian** [microsoft/mimalloc#166]
I had to create a symlink /lib/libmimalloc.so.1.0 -> /lib/mimalloc-1.0/libmimalloc.so.1.0 manually to make a build process work, that had no issues with earlier (pre 1.1.0) mimalloc versions. Does that need to be fixed on your end?

**Comment by daanx** [comment]
Yes, I changed things it the CMakeLists.txt to set a symlink -- I wonder why it does not work though?
Before I made a copy but that is not ideal either

**Comment by daanx** [comment]
If anyone has an idea what is wrong it the cmake file with the symlink creation, let me know :-)

**Comment by ohasanliUW** [comment]
Ignore 5433dbb.
b41183e has the fix for this issue. I tested it on macOS.

**Comment by ohasanliUW** [comment]
Please close this issue.
