### ISSUE TITLE
How to build mimalloc-redirect.dll?

### ISSUE THREAD

**Issue by fabio-polystream** [microsoft/mimalloc#171]
I would like to build `mimalloc-redirect.dll` myself, but I don't find the related VS2017 project that builds it. `mimalloc-override` just expect `mimalloc-redirect.lib` in the bin folder. What would I need to do to build `mimalloc-redirect`, if possible at all?

**Comment by daanx** [comment]
Ah, at this time the source of the redirect dll's is not yet public; the plan is do make it open source too though in the future.

**Comment by fabio-polystream** [comment]
I see, thank you anyway. I am looking forward to it ;)

**Comment by daanx** [comment]
working on it.. :-)

**Comment by synacker** [comment]
We are waiting for! )

**Comment by thomascowell** [comment]
I'm also interested in the source to this. Is there any update on when this may be released? Thanks!

**Comment by nkeemik** [comment]
@daanx , any news on making the source of mimalloc-redirect public ?

**Comment by Khodyn** [comment]
@daanx Hello? It's been almost two years, what's so difficult about open sourcing mimalloc-redirect?

**Comment by variar** [comment]
@Khodyn looking at how the malloc redirection is done in TBB malloc, there might be some internals of C runtime involved. It seems that Intel did some reverse engineering, while mimalloc-redirect may have access to copyrighted sources:

Sample from `onetbb/src/tbbmalloc_proxy/proxy.cpp`
```
const char* known_bytecodes[] = {
#if _WIN64
//  "========================================================" - 56 symbols
    "4883EC284885C974",       // release free()
    "4883EC284885C975",       // release _msize()
    "4885C974375348",         // release free() 8.0.50727.42, 10.0
    "E907000000CCCC",         // release _aligned_msize(), _aligned_free() ucrtbase.dll
    "C7442410000000008B",     // release free() ucrtbase.dll 10.0.14393.33
    "E90B000000CCCC",         // release _msize() ucrtbase.dll 10.0.14393.33
    "48895C24085748",         // release _aligned_msize() ucrtbase.dll 10.0.14393.33
    "E903000000CCCC",         // release _aligned_msize() ucrtbase.dll 10.0.16299.522
    "48894C24084883EC28BA",   // debug prologue
    "4C894424184889542410",   // debug _aligned_msize() 10.0
    "48894C24084883EC2848",   // debug _aligned_free 10.0
    "488BD1488D0D#*******E9", // _o_free(), ucrtbase.dll
 #if __TBB_OVERLOAD_OLD_MSVCR
    "48895C2408574883EC3049", // release _aligned_msize 9.0
    "4883EC384885C975",       // release _msize() 9.0
    "4C8BC1488B0DA6E4040033", // an old win64 SDK
 #endif
```

It might be possible to adapt TBB malloc redirection code for mimalloc.

**Comment by coltorchen** [comment]
> working on it.. :-)

We are waiting for! ) @daanx 
any news on making the source of mimalloc-redirect public ?

**Comment by cher-nov** [comment]
still waiting...

**Comment by vauki** [comment]
me too :/

**Comment by first-zhangwei** [comment]
@daanx Three years have passed, when do we have to wait? :(

**Comment by litterbug23** [comment]
waiting

**Comment by YuriArthas** [comment]
waiting...(2024)

**Comment by Erfan-Ahmadi** [comment]
waiting.

**Comment by Erfan-Ahmadi** [comment]
For anyone who's here, trying to learn how to redirect/detour their own malloc on Windows, but don't want to use `mimalloc` yet. here is my guide to you:
use [minhook](https://github.com/TsudaKageyu/minhook) and hook malloc/free functions from c runtime (ucrtbase.dll/ucrtbased.dll), it is really easy to setup. (you can use any similar lib like Microsofts Detour which I haven't used)
Additionally you can see how [rmem](https://github.com/RudjiGames/rmem), an instrumentation tool for [MTuner](https://github.com/RudjiGames/MTuner), is using this.
here is my gist on how you can detour your own malloc/free and detour your c runtime functions using minhook:
https://gist.github.com/Erfan-Ahmadi/93369b8b7fbce77b1adf8e244ea33849
