### ISSUE TITLE
Creating a mimalloc.dll

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#174]
The docs says you can only override default malloc by building mimalloc-override *and* having mimalloc.dll. But the solution provided doesn't have a way to build a dll. I tried changing configs but didn't get it to build, how do you do it?

**Comment by daanx** [comment]
Ah sorry for the confusion; I will try to update the documentation to be more clear. Currently, on Windows, to override the standard `malloc`, you need `mimalloc-override.dll` together with `mimalloc-redirect.dll`. The first one is the `mimalloc` library while the second one implements the "magic" to take over the C runtime `malloc`. The `mimalloc-redirect` dll's are in it the `bin` folder and copied by the solution to the output of a project. The plan is to make the redirect dll's open source but they are not yet.
