### ISSUE TITLE
mimalloc is using a lot of memory in multithreading test

### ISSUE THREAD

**Issue by migra-leutek** [microsoft/mimalloc#177]
In a multhreading test mimalloc uses much more memory than the default allocator of VS 2017.
50 threads delete and create about 3000 events/s in a database the whole time. 
The thread which creates one event and the thread which deletes the created event is often not the same thread.

Output of  mi_stats_print():
heap stats:     peak      total      freed       unit      count  
  reserved:    22.5 gb    22.5 gb     1.0 gb       1 b              not all freed!
 committed:    57.1 gb101321.2 gb101296.2 gb       1 b              not all freed!
     reset:       0 b        0 b        0 b        1 b              ok
   touched:    29.0 mb    18.7 gb  3336.8 gb       1 b              ok
  segments:    15.3 kb    24.7 mb    24.7 mb       1 b     25.9 m   not all freed!
-abandoned:     6.5 kb     7.3 kb     1.1 kb       1 b      7.5 k   not all freed!
   -cached:       0 b        0 b        0 b        1 b        0     ok
     pages:   338.0 kb   478.9 mb   478.8 mb       1 b    502.2 m   not all freed!
-abandoned:    96.8 kb   114.8 kb    19.6 kb       1 b    117.5 k   not all freed!
 -extended:
 -noretire:       0   
     mmaps:
   commits:
   threads:
  searches:     0.0 avg
   elapsed: 121781.379 s
   process: user: 1465362.813 s, system: 125103.188 s, faults: 8625157, reclaims: 0, rss: 31.8 gb, commit charge: 33.8 gb

![RAM consumption](https://user-images.githubusercontent.com/39116563/69305561-bb5cd280-0c24-11ea-9792-9faae3fd4cd8.png)

**Comment by daanx** [comment]
Ouch, that looks not good at all! Are you using the latest `dev` branch?  Can you try to run with the latest `dev` branch with `MIMALLOC_EAGER_COMMIT=0`?

Generally, on Windows, mimalloc tends to commit more than the default allocator but the actual working set should be similar and not keep growing. The `mstress` and `xmalloc-test` benchmarks test heavily allocation between threads, and creating/terminating threads and there is no growth there so I think there is something else going on.

**Comment by gnzlbg** [comment]
@migra-leutek do you have a way to reproduce this (a self contained application that one can download, compile, and run?) or even better, have you been able to reduce this to a minimum working example ?

**Comment by migra-leutek** [comment]
I will try to isolate the failure so I can give you a working example.

**Comment by daanx** [comment]
This issue is very concerning to me, especially as I have heard it before but as of now I cannot reproduce it locally (nor does it occur in other very large services that are running mimalloc). It is my number one thing to fix though it I can get to the root of the issue. @gnzlbg: are you able to run a test version of mimalloc again to see how it behaves?  [mimalloc-test](https://www.dropbox.com/s/67nv967x2dbdu3n/mimalloc-override.dll?dl=1). You should be able to just overwrite the one you use and re-run the test.  It might just fix the issue... fingers crossed :-)

**Comment by daanx** [comment]
@migra-leutek: I fixed some subtle concurrency bug recently which perhaps solves the problem. I compiled a recent version of `dev-abandon` branch [here](https://www.dropbox.com/s/700m4g46cjgvpmx/mimalloc-override.dll?dl=1). (This is a full debug version so it is slowish though)

**Comment by migra-leutek** [comment]
I tried the new mimalloc-override.dlls.
Our application is running with the 1st version of mimalloc-override.dll.
The memory is still raising the 1st day but then it comes to an end.
For further investigation you should send me the release version because our application reaches only 10% of the performance with the debug version.

With the 2nd version of mimalloc-override.dll our application is not running because it has a problem during the initialization phase. There seems to be a bug in the 2nd version.
If you also give me the mimalloc-override.pdb file I could make a stacktrace of our application and send it to you.

**Comment by daanx** [comment]
Thanks so much for trying; the pdb is [here](https://www.dropbox.com/s/2zkrlz3woikjkgh/mimalloc-override.pdb?dl=1). Would be great to get a stack trace (-- it might happen due to huge OS page reservation ?).  

I will also prepare a regular debug version that does not do full internal checking as that slows down things a lot. Thanks for trying, hope we can find out what is going on.

**Comment by daanx** [comment]
Ah, I think the error you encountered during initialization is fixed now. Here are the updated [dll](https://www.dropbox.com/s/700m4g46cjgvpmx/mimalloc-override.dll?dl=1) and [pdb](https://www.dropbox.com/s/2zkrlz3woikjkgh/mimalloc-override.pdb?dl=1) (build using MI_DEBUG=2 so hopefully fast enough while still checking a lot).

**Comment by daanx** [comment]
Is there any progess on this? If possible try the latest `dev` or 1.6.1 as there has been various improvements to improve memory usage recently.

**Comment by migra-leutek** [comment]
Yes, there is a progress on this. The memory consumption with 1.6.1 is much better than before.
![MemoryAllocation_with_mimalloc](https://user-images.githubusercontent.com/39116563/76881799-f7720e00-6879-11ea-9e3a-00093b12aad7.png)
