### ISSUE TITLE
Running exe with mimalloc on wine

### ISSUE THREAD

**Issue by kipodon** [microsoft/mimalloc#180]
Hi,
I am trying to run an application that uses mimalloc on wine. 
the pre built mimalloc-redirect.dll uses a function called RtlQueryEnvironmentVariable
 in ntdll.dll. this function is not implemented under wine.
I wonder what win32 calls created that dependency so I can call wine and ask them for implementation. so it would be helpful if I can compile this code myself. 

Alon

**Comment by daanx** [comment]
Ah, the `mimalloc-redirect.dll` is very specific for Windows -- I am surprised though `RtlQueryEnvironmentVariable` is not available as that has been around a long time. The best way is to ask the Wine developers to support this. However, it may still not work as it is quite specific to Windows and ucrtbase.dll. :-(
