### ISSUE TITLE
Verbose output with Windows MFC GUI application

### ISSUE THREAD

**Issue by bencherian** [microsoft/mimalloc#181]
I have been trying to use mimalloc via dynamic overriding in an existing Windows MFC GUI application. I wanted to look more into allocation statistics, etc. but have been unable to get any of the console output to show up when linking to mimalloc from this application even when I start it from the console. (It does appear to be getting used, and the environment variables do actually affect the memory utilization.) The code appears to jump through some hoops in order to write output to the console. Is there anything special I need to do in order for this to work properly? (Other console output from other libraries which use fprintf to write to stderr appear as expected.)

*On a somewhat related note which might be useful for future users, I began looking into this in more detail because dynamic linking would result in very different behavior when my application was launched through a debugger as opposed to being launched standalone. It turns out that my antivirus software (CB Defense) will load itself into the process whenever an (unknown?) standalone application is run. This in turn loads the UCRT DLL prior to mimalloc being loaded, which prevents malloc redirection.

**Comment by daanx** [comment]
Hi, mimalloc only outputs all messages when `MIMALLOC_VERBOSE=1` is set. However, on Windows we use `cputs` to directly output to the console  (to avoid locking issues if the CRT itself uses mimalloc). This might be the culprit for you. However, you can also use `mi_register_output` to register your own output handlers which you can  use to show statistics in a GUI for example. (use the latest `dev` version as it got a helpful extra argument recently)

* with respect to the antivirus software: ouch! but what can we do in that case? I'll add a note in the documentation.
