### ISSUE TITLE
mprotect cannot release memory on linux with kernel 4.9.0

### ISSUE THREAD

**Issue by wstc** [microsoft/mimalloc#182]
i test it with option `reset_decommits`

btw, `segment_reset` is ok!

**Comment by daanx** [comment]
Thanks for spotting this -- `reset_decommits` is still "experimental" but I will look into it. I am working on delayed resets and this should be part of that.

**Comment by daanx** [comment]
I think it is fixed in the latest `dev` version -- I just tried on Ubuntu 18.04 (kernel 4.15.0).
Test as:
```
~/dev/mimalloc/out/debug> cmake ../.. -DMI_DEBUG_FULL=ON
...
~/dev/mimalloc/out/debug> MIMALLOC_EAGER_COMMIT=0 MIMALLOC_EAGER_REGION_COMMIT=0 MIMALLOC_PAGE_RESET=1 MIMALLOC_SEGMENT_RESET=1 MIMALLOC_RESET_DECOMMITS=1 MIMALLOC_VERBOSE=1 ./mimalloc-test-stress
```
