### ISSUE TITLE
bugs on large_os_pages in ver1.2.1

### ISSUE THREAD

**Issue by wstc** [microsoft/mimalloc#184]
when is set env (mimalloc_large_os_pages=1),

this occur when malloc call before mimalloc init。

```
_mi_malloc_generic -> mi_thread_init -> mi_process_init -> _mi_os_init ->
mi_option_get (large_os_pages) -> mi_option_init

because  _mi_preloading() is True, 
so we can't init large_os_page_size, and we'll never reinit it !
```
i test ver1.2.0,  and i do not find such bug. please check it.

**Comment by daanx** [comment]
Thanks for spotting this -- should be fixed in 1.2.2
