### ISSUE TITLE
Specify x86 calling convention for export APIs

### ISSUE THREAD

**Issue by mcfi** [microsoft/mimalloc#185]
Scenario to support: Say if two DLLs A.dll and B.dll in the same project wants to link with a static mimalloc lib, and the two DLLs, due to historic reasons, are compiled with default calling conventions different (A has _cdecl and B has _stdcall). Since mimalloc.h doesn't explicitly specify the calling conventions of those exported APIs, when A is compiled, those APIs in the static lib are expected to have _cdecl while when B is compiled, those APIs in the static lib are expected to be __stdcall. Though we can build two copies of static mimalloc lib and link separately with A and B, it is redundant and developers may need spend a lot of time to figure out what's going on.

Proposed solution: explicitly specify the calling convention of mimalloc APIs

**Comment by daanx** [comment]
Thanks! I think this is only an issue on Windows right? We may add  `mi_cdecl` to the `mi_decl_export` definitionts on Windows.

**Comment by daanx** [comment]
I looked into it but it would adding explicit calling convention `mi_cdecl` to every declaration; I feel that is not worth it at this time.
