### ISSUE TITLE
Suspicious looking if statement in arena.c

### ISSUE THREAD

**Issue by MrSmith33** [microsoft/mimalloc#197]
https://github.com/microsoft/mimalloc/blob/master/src/arena.c#L138

```C
  else if (commit) {
```
`commit` is `bool*` here and caller ensures that it is not null.
Should be replaced with `*commit` IMO.

**Comment by daanx** [comment]
Yes! thanks for spotting this -- I happened  to see it too just yesterday. However, currently that code path is never reached so it's fine for previous versions but glad we found it in time. (It's fixed in #ecece572 (to be pushed soon))
