### ISSUE TITLE
Build failures when enable 'MI_SECURE'

### ISSUE THREAD

**Issue by PhoebeHui** [microsoft/mimalloc#203]
Hello mimalloc developers,

mimalloc is avaliable in vcpkg, I tried to upgrade it to latest release revision 1.6, however it failed with following error when enable feature 'MI_SECURE' on windows, could you please help take a look?

The failures like:
E:\VCPKG\src\buildtrees\mimalloc\src\9abd552175-ebb54a58f9\src\page.c(108): error C2039: 'key': is not a member of 'mi_page_s'
E:\VCPKG\src\buildtrees\mimalloc\src\9abd552175-ebb54a58f9\include\mimalloc-types.h(203): note: see declaration of 'mi_page_s'
[2/16] C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1422~1.279\bin\Hostx64\x86\cl.exe   /TP -DMI_DEBUG=3 -DMI_SECURE=4 -DMI_SHARED_LIB -DMI_SHARED_LIB_EXPORT -Dmimalloc_EXPORTS -IE:\VCPKG\src\buildtrees\mimalloc\src\9abd552175-ebb54a58f9\include /DWIN32 /D_WINDOWS /W3 /utf-8 /GR /EHsc /MP  /D_DEBUG /MDd /Z7 /Ob0 /Od /RTC1    -std:c++17 /showIncludes /FoCMakeFiles\mimalloc.dir\src\heap.c.obj /FdCMakeFiles\mimalloc.dir\ /FS -c E:\VCPKG\src\buildtrees\mimalloc\src\9abd552175-ebb54a58f9\src\heap.c
Microsoft (R) C/C++ Optimizing Compiler Version 19.22.27905 for x86

**Comment by PhoebeHui** [comment]
This issue involved by commit https://github.com/microsoft/mimalloc/commit/aa68b8cbc7830bebbaec98f8c851a5f358993614#diff-5eb538092226d500a3adcf613bc91995, it rename key to keys, but doesn't update it when use it.

**Comment by daanx** [comment]
Ah great for spotting this -- I just pushed a fix to `dev`. I will make a few more fixes and then hopefully push out `1.6.1` today or tomorrow which should then integrate better with `vcpkg` -- great you are working  on this!

**Comment by daanx** [comment]
As an aside: usually one uses `MI_SECURE=ON` without debugging enabled as well; I wonder how that is configured in `vcpkg` ?

**Comment by PhoebeHui** [comment]
@daanx, thanks for fixing this issue!

In VCPKG we enabled the secure feature by setting MI_SECURE=ON. And install the feature if needed via command: vcpkg install mimalloc[secure].

https://github.com/microsoft/vcpkg/tree/master/ports/mimalloc
