### ISSUE TITLE
DLL deallocation with static variables

### ISSUE THREAD

**Issue by Invander29** [microsoft/mimalloc#207]
Hello, I am experiancing issue when I want to create shared library (Windows 10, v141 and v142) which uses mimalloc-static. When library is unloaded, heap is probably destroyed before dealocation and in Debug mode it crashes with:

v1.4.0
> mimalloc: assertion failed: at "C:\Projects\mimalloc\src\alloc.c":237, _mi_free_block_mt
  assertion: "heap != NULL"

v1.6.1
> mimalloc: assertion failed: at "C:\Projects\MiTest\mimalloc-1.6.1\src\alloc.c":214, mi_page_usable_size_of
  assertion: "ok"

A have attached demo project to show you what I mean.
[MiTest.zip](https://github.com/microsoft/mimalloc/files/4218419/MiTest.zip)

Thank you

**Comment by daanx** [comment]
Thanks -- I will take a look later; probably the same issue as #208

**Comment by daanx** [comment]
I think it is fixed in latest dev, it only occurred in debug mode which would free up the main thread's heap when done. However, if statically linked in a DLL it seemed there were still later calls from the C++ runtime to `delete`; the fix is to not clean up the main thread's metadata even in Debug mode.

**Comment by adamzl** [comment]
Hello @daanx, I wanted to confirm that this issue and your resolution are the reason that mimalloc statically linked to a DLL, would cause the DLL to fail app verifier's leak detection. We are failing to free VirtialAlloc pages, I've tracked them back to the mi_thread_data_t's. I can provide more detail and open a Github issue, but wanted to find out if this is an expected app verifier result given your above comment.
