### ISSUE TITLE
Windows VirtualAlloc fails with the "hint" address when multiple dlls with statically linked mimalloc are used.

### ISSUE THREAD

**Issue by rob-turner** [microsoft/mimalloc#210]
Dear mimalloc team,

I ran into an issue when using the statically linked version of mimalloc in an exe, client.dll and server.dll  all running in the same process.  The issue happened in os.c in the following code:
  if (addr == NULL && (hint = mi_os_get_aligned_hint(try_alignment,size)) != NULL) {
	void * memPtr =  VirtualAlloc(hint, size, flags, PAGE_READWRITE);

The hint address passed in to VirtaulAlloc was successful in the first instance of mimalloc.  The second instance of mimalloc in a dll calculated the same hint address and VirtualAlloc returned a NULL pointer.  It may be related to this issue described by MSFT:  "If the address in within an enclave that you initialized, then the allocation operation fails with the ERROR_INVALID_ADDRESS error.".

To work around the issue I modified the code retry the call for a fixed number of times with a new hint.  The workaround code resolved the issue and the 2nd call to VirtualAlloc with a new hint address was successful.

Thank you for providing mimalloc as it really solved a HUGE performance problem I was having on Windows in a highly threaded environment.

Take care and have a great day!

**Comment by daanx** [comment]
> Thank you for providing mimalloc as it really solved a HUGE performance problem I was having on Windows in a highly threaded environment.
 
Good to hear that :-)

I see what is going wrong -- there are really two instances of mimalloc running (one for each DLL) and they both try to use the same virtual area. Mmm, best solution is to avoid that by using mimalloc as a DLL :-)  but it should be fixed anyways as this can easily happen with multiple libraries independently using mimalloc. The hint is good for performance but perhaps we should on Windows just prefer using `VirtualAlloc2` that can do aligned allocation anyways. I am looking into it.

**Comment by daanx** [comment]
I think it is fixed now -- it automatically falls back to `VirtualAlloc2` if an area was already claimed. Note that this mostly happens in Debug mode as `release` and `secure` mode use randomized starting areas.

**Comment by rob-turner** [comment]
Thank you for the fix! :-)
