### ISSUE TITLE
Overhead on allocations with empty page, again for large buffers

### ISSUE THREAD

**Issue by buybackoff** [microsoft/mimalloc#212]
This is related to https://github.com/microsoft/mimalloc/issues/187

Since the commit mentioned in the issue the code has changed, and now the relevant code is on [this line](https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/page.c#L405).

If I use buffers below `MI_MAX_RETIRE_SIZE`, which is `4096=4*8*128`, performance is good, but as soon as I exceed this size performance drops **by 30 times**. The workaround of pre-allocating a buffer is not good, because it has to be pre-allocated on every thread, not once. 

Also, in my case I use mimalloc as an allocator for a buffer pool in .NET, used for all blittable types to store them off-heap (BTW, I ported full API in .NET [here](https://github.com/Spreads/Spreads.Native)). Since the size of the types could differ a lot, I will need to pre-allocate a thread-static buffer for every type `T` and every pool bucket size. But there will be overlap of native buffers size in bytes for different buckets of different `T`s, e.g. native buffer for `byte[4096]` is the same as for `int[1024]`. This already slows down pool implementation and requires lots of unused buffer just as a workaround. If I add some logic to avoid pre-allocating native buffers of the same size the overheads for the hot path might be even more. But, most importantly, this workaround is a hack, not a real solution.

So my questions are:

* Could that be fixed for all buffer sizes?
* Could I just increase `MI_MAX_RETIRE_SIZE` in source code e.g. to 1MB and recompile, or something could break somewhere?
* Could you expose `MI_MAX_RETIRE_SIZE` as an environment/CMake option if it's safe to just change its value? Now it's defined [here](https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/page.c#L383) without any checks if it is already defined.

Settings I use for benchmarking:

```
Mem.OptionSetEnabled(Mem.Option.EagerCommit, true);
Mem.OptionSetEnabled(Mem.Option.LargeOsPages, true);
Mem.OptionSetEnabled(Mem.Option.ResetDecommits, true);
Mem.OptionSetEnabled(Mem.Option.PageReset, true);
Mem.OptionSetEnabled(Mem.Option.SegmentReset, true); // without it memory usage increases up to OOM
Mem.OptionSetEnabled(Mem.Option.AbandonedPageReset, true);
Mem.OptionSetEnabled(Mem.Option.EagerRegionCommit, false); 
Mem.OptionSetEnabled(Mem.Option.ReserveHugeOsPages, true);

```

Mimalloc version 1.6.1.

**Comment by daanx** [comment]
Ah I see -- this is a thorny problem; generally the goal for mimalloc is to have property to not have edge cases that make it perform much worse suddenly. There are few remaining cases where it does not hold, and this is one of them :-( 

It is tricky though: keep a free page around and it can be more performant if it happens to be reused "soon"; or free it right away to allow the memory to be reused by other size-classes or threads?  

Best seems to be if _all_ pages are retained for a while (based on allocation rate), and only then freed. Currently it is still a bit too conservative with the MAX_RETIRE_SIZE; maybe it can be done better; let me ponder on it for a bit and get back to you.

**Comment by daanx** [comment]
Hi @buybackoff , I just pushed a fix (I think) to the `dev` branch. Let me know how it works for you. Basically using retirement now for all object sizes and keeping a min/max to reduce average scan times.
