### ISSUE TITLE
SegFault when freeing on a different thread > 2 MB

### ISSUE THREAD

**Issue by buybackoff** [microsoft/mimalloc#221]
This test fails (using C# P/Invoke).

```
[Test, Explicit]
public void CouldFreeOnDifferentThread()
{
    var length = 2 * 1024 * 1024 + 1; // fails > 2MB
    for (int i = 0; i < 100; i++)
    {
        var pm = Mem.Malloc((UIntPtr) (length));
        // Mem.Free(pm); // works
        Task.Run(() =>
        {
            Mem.Free(pm); // fails
        }).Wait();
    }
}
```

This escaped my original testing due to small buffers, but same behavior with real threads, not tasks:

```
[Test]
public void CouldAllocFreeFromDifferentThreads()
{
    var bc = new BlockingCollection<IntPtr>();
    var are = new AutoResetEvent(false);
    var count = 100;
    var t1 = new Thread(() =>
    {
        for (int i = 0; i < count; i++)
        {
            var ptr = Mem.MallocAligned((UIntPtr) (2 * 1024 * 1024 + 1), (UIntPtr) (8));
            bc.Add((IntPtr) ptr);
            are.WaitOne();
        }

        bc.CompleteAdding();
    });
    t1.Start();

    var t2 = new Thread(() =>
    {
        foreach (var intPtr in bc.GetConsumingEnumerable())
        {
            Mem.Free((byte*) intPtr);
            are.Set();
        }
    });
    t2.Start();
    t1.Join();
    t2.Join();
}
```

I'm still using 1.6.1 release, haven't yet recompiled for #212.

**Comment by daanx** [comment]
Yikes --  that would be terrible as it is a basic use case. Also, this use case should normally probed by "test-stress" on every build. I tried to reproduce it in the latest `dev`; I checked in a test case on the latest `dev` branch in `main-override.cpp` (use the `mimalloc-test-override` project in VS2019 to repro), as: 
```
// Issue #221
void* shared_p;

void heap_thread_free_large_worker() {
  mi_free(shared_p);
}

void heap_thread_free_large() {
  for (int i = 0; i < 100; i++) {
    shared_p = mi_malloc(2*1024*1024 + 1);
    auto t1 = std::thread(heap_thread_free_large_worker);
    t1.join();
  }
}
```
but it all just works.  Can you try to run it with debug mode on? I wonder if the bug is on the C# side perhaps?. Mmm, on the other hand it is suspicious though it happens with over 2MiB allocations as that is the point where mimalloc starts to use (abandoned) "huge" page allocations where one pages spans a full segment. Not sure what is happening here.

**Comment by buybackoff** [comment]
There could be something wrong with native build config, I copied it from somewhere on GitHub and reviewed it to my quite limited knowledge of native compiler flags. Other than that it's direct P/Invoke call to a shared native lib and I verified the signatures for DllImport are correct. I will rebuild to test #212 and review the config once more.

**Comment by buybackoff** [comment]
Could you please run the test with `MI_DEBUG=0` if it's not at 0 already? I had it set to 0, if I set `MI_DEBUG_FULL=1` the test works. Using latest dev branch.

**Comment by daanx** [comment]
Will try

**Comment by daanx** [comment]
Ah, too strange. I cannot repro; tried various MI_DEBUG setting, in release and debug mode, also tried `mi_malloc_aligned` vs. `mi_malloc`.
In the first `Task` example, can you check the pointer passed to `MemFree`, i.e. `pm` is actually the correct one? Perhaps it is captured by value or not updated after the first run?   
(btw. did you know I wrote the original `Task` abstraction and `Task.Parallel` etc. with its work stealing queues :-); after it landed in .NET lots of people contributed and it changed quite a bit over the years but the core is still there -- still make me happy every time I see it in action, and glad that I chose a nice short name like `Task` instead of ThreadedWorker or something  :-) )

**Comment by daanx** [comment]
just to confirm: it works if you pass less than 2MiB ? and also it works if you use the Debug version?  and also if you free in the same thread.  But it always crashes in Release + more than 2MiB + free from different thread?

**Comment by buybackoff** [comment]
> In the first Task example, can you check the pointer passed to MemFree, i.e. pm is actually the correct one? Perhaps it is captured by value or not updated after the first run?

It fails on the first iteration. Originally it failed from a finalizer where it's properly stored as a field.

> (btw. did you know I wrote the original Task abstraction and Task.Parallel etc. with its work stealing queues :-); after it landed in .NET lots of people contributed and it changed quite a bit over the years but the core is still there -- still make me happy every time I see it in action, and glad that I chose a nice short name like Task instead of ThreadedWorker or something :-) )

Cool! :) I didn't know.

> just to confirm: it works if you pass less than 2MiB ? and also it works if you use the Debug version? and also if you free in the same thread. But it always crashes in Release + more than 2MiB + free from different thread?

It works when I set `MI_DEBUG_FULL=1`. It fails if I do not touch the flags or set `MI_DEBUG=0`.

I have cflags for Release:

```
/DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2
```
and for Debug:
```
`/DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1`
```

But Relase/Debug doesn't change anything, or commenting out those flags and leaving CMake's default. Only `MI_DEBUG_FULL=1` fixes the test so far.

**Comment by daanx** [comment]
Ah, that is so strange that `MI_DEBUG_FULL=1` works but without it fails -- let me think on this what could possibly be different (as `MI_DEBUG_FULL` just adds assertion as far I as I can tell)

**Comment by daanx** [comment]
Is there any way you could attach the Visual Studio debugger to see where it crashes?

**Comment by buybackoff** [comment]
> Is there any way you could attach the Visual Studio debugger to see where it crashes?
(or send me detailed build instructions so I can reproduce it locally?)

It's more complex. I build a number of useful C libraries into one shared library via Rust's cargo, with some additional glue code in Rust. For mimalloc it's pass-through and I checked there is nothing that starts with `MI_` in other libraries.

I will now try to reproduce this is Rust test to rule out C# side and find a way to build .pdb.

**Comment by daanx** [comment]
Ah I see. Is the `mimalloc-redirect.dll` used to override `malloc`/`free` ? Or are you using direct `mi_` prefixed calls? (= better).  I wonder if there is some interaction between the runtime systems?

**Comment by buybackoff** [comment]
I use direct `mi_` calls. Also I linked C runtime statically, but I tried mimalloc's cflags with `/MT` as well. I also did a number of stress tests (all with small buffers), so if linkage was incorrect it should have blown up somewhere for sure. Rust toolchain is msvc, not gnu.

On Rust side it fails as well

```
    fn it_could_free_on_different_thread() {
        let x = spreads_mem_malloc(2 * 1024 * 1024 + 1) as i64;

        let t = std::thread::spawn(move || {
            spreads_mem_free(x as *mut libc::c_void);
        });
        t.join();
    }
```

with debugger stopping at the second from the end line below:

```
; id = {0x000008be}, range = [0x00000001400c1550-0x00000001400c16ce), name="void _mi_segment_huge_page_free(struct mi_segment_s *, struct mi_page_s *, struct mi_block_s *)", mangled="?_mi_segment_huge_page_free@@YAXPEAUmi_segment_s@@PEAUmi_page_s@@PEAUmi_block_s@@@Z"
; Source location: unknown
7FF719771550: 48 89 5C 24 10             movq   %rbx, 0x10(%rsp)
7FF719771555: 48 89 6C 24 18             movq   %rbp, 0x18(%rsp)
7FF71977155A: 56                         pushq  %rsi
7FF71977155B: 48 83 EC 20                subq   $0x20, %rsp
7FF71977155F: 44 8B 0D 2A D0 06 00       movl   0x6d02a(%rip), %r9d  ; _tls_index
7FF719771566: 48 8B EA                   movq   %rdx, %rbp
7FF719771569: 65 48 8B 04 25 58 00 00 >  movq   %gs:0x58, %rax
7FF719771572: 48 8B D9                   movq   %rcx, %rbx
7FF719771575: BE E8 00 00 00             movl   $0xe8, %esi
7FF71977157A: 4A 8B 04 C8                movq   (%rax,%r9,8), %rax
7FF71977157E: 48 8B 34 06                movq   (%rsi,%rax), %rsi
7FF719771582: 33 C0                      xorl   %eax, %eax
7FF719771584: 4C 8B 8E 20 0B 00 00       movq   0xb20(%rsi), %r9
7FF71977158B: F0                         lock   
7FF71977158C: 4C 0F B1 49 68             cmpxchgq %r9, 0x68(%rcx)
7FF719771591: 0F 85 27 01 00 00          jne    0x7ff7197716be  ; <+366>
7FF719771597: 48 8B 42 08                movq   0x8(%rdx), %rax
7FF71977159B: 48 8B CA                   movq   %rdx, %rcx
7FF71977159E: 49 89 00                   movq   %rax, (%r8)
7FF7197715A1: FF 4A 10                   decl   0x10(%rdx)
7FF7197715A4: 80 62 07 FE                andb   $-0x2, 0x7(%rdx)
7FF7197715A8: 4C 89 42 08                movq   %r8, 0x8(%rdx)
7FF7197715AC: 48 8B 36                   movq   (%rsi), %rsi
7FF7197715AF: 48 89 7C 24 30             movq   %rdi, 0x30(%rsp)
7FF7197715B4: 48 8D 7E 20                leaq   0x20(%rsi), %rdi
7FF7197715B8: E8 83 05 00 00             callq  0x7ff719771b40
7FF7197715BD: 48 3D 00 00 00 04          cmpq   $0x4000000, %rax  ; imm = 0x4000000 
7FF7197715C3: 41 B8 40 01 00 00          movl   $0x140, %r8d  ; imm = 0x140 
7FF7197715C9: B9 20 01 00 00             movl   $0x120, %ecx  ; imm = 0x120 
7FF7197715CE: 48 8B D0                   movq   %rax, %rdx
7FF7197715D1: 41 0F 47 C8                cmoval %r8d, %ecx
7FF7197715D5: 48 03 8E 90 00 00 00       addq   0x90(%rsi), %rcx  <-- debugger stop here
7FF7197715DC: E8 8F D2 FF FF             callq  0x7ff71976e870  ; void _mi_stat_decrease(struct mi_stat_count_s *, unsigned __int64)
```

**Comment by daanx** [comment]
Thanks for the trace -- I cannot see why it is going wrong though :-(  -- nevertheless, I checked in a possible fix, can you try the latest `dev`?   The weird part is that it seems to crash at maintaining statistics (which may explain why it works in debug mode)

**Comment by daanx** [comment]
Ah, I have a repro! It happens when static linking on Windows in release mode. Investigating now! :-)

**Comment by buybackoff** [comment]
> btw. why does the debugger stop? is it a seg fault (no write permission? or read permission?)

It shows: Stop reason: Exception 0xc0000005 encountered at address 0x7ff6993ef550: Access violation reading location 0x000001e8

The stack trace changed after your change, but this time no symbols:

```
; No Symbol Info
; Source location: unknown
7FF6993EF550: 48 8B 49 18                movq   0x18(%rcx), %rcx    <-- stopped here
7FF6993EF554: 49 03 C9                   addq   %r9, %rcx
7FF6993EF557: 49 89 48 18                movq   %rcx, 0x18(%r8)
7FF6993EF55B: 49 3B 48 10                cmpq   0x10(%r8), %rcx
7FF6993EF55F: 7E 04                      jle    0x7ff6993ef565
7FF6993EF561: 49 89 48 10                movq   %rcx, 0x10(%r8)
7FF6993EF565: 4D 85 C9                   testq  %r9, %r9
7FF6993EF568: 7E 04                      jle    0x7ff6993ef56e
7FF6993EF56A: 4D 01 08                   addq   %r9, (%r8)
7FF6993EF56D: C3                         retq   
7FF6993EF56E: 4D 29 48 08                subq   %r9, 0x8(%r8)
7FF6993EF572: C3                         retq   
7FF6993EF573: CC                         int3   
7FF6993EF574: CC                         int3   
7FF6993EF575: CC                         int3   
7FF6993EF576: CC                         int3   
7FF6993EF577: CC                         int3   
7FF6993EF578: CC                         int3   
7FF6993EF579: CC                         int3   
7FF6993EF57A: CC                         int3   
7FF6993EF57B: CC                         int3   
7FF6993EF57C: CC                         int3   
7FF6993EF57D: CC                         int3   
7FF6993EF57E: CC                         int3   
7FF6993EF57F: CC                         int3   
7FF6993EF580: 48 3B CA                   cmpq   %rdx, %rcx
7FF6993EF583: 0F 84 C3 03 00 00          je     0x7ff6993ef94c
7FF6993EF589: 48 8B 02                   movq   (%rdx), %rax
7FF6993EF58C: F0                         lock   
7FF6993EF58D: 48 0F C1 01                xaddq  %rax, (%rcx)
7FF6993EF591: 48 8B 42 18                movq   0x18(%rdx), %rax
7FF6993EF595: F0                         lock   
7FF6993EF596: 48 0F C1 41 18             xaddq  %rax, 0x18(%rcx)

```

**Comment by buybackoff** [comment]
It works! :)

**Comment by daanx** [comment]
I think I got it fixed now with afc4f79 -- tricky issue! Glad you found it. Initialization of thread local data is very tricky to get right across all configurations and I missed a case here for static initialization. 

Ah, you tested it before I could even finish the comment lol 👍

**Comment by daanx** [comment]
I will push a new release (1.6.2) soon with this fix in.

**Comment by buybackoff** [comment]
> Ah, you tested it before I could even finish the comment lol 👍

Quarantine time! Online 24/7 :)

> I will push a new release (1.6.2) soon with this fix in.

Thanks again! I waited for a release for previous performance issue, but it was not blocking.
