### ISSUE TITLE
`mi_strndup` broken or slow for strings with no nul-terminator in first `n` bytes.

### ISSUE THREAD

**Issue by thomcc** [microsoft/mimalloc#228]
https://github.com/microsoft/mimalloc/blob/6e1ca96a4965c776c10698c24dae576523178ef5/src/alloc.c#L646

It just does a strlen.

If no nul-terminator exists at all, this is clearly broken and will either crash or find some lonely nul off in the great yonder.

If that doesn't bother you (IDK, maybe that's undefined behavior) then at the very least it could be quite a while before the NUL is met, which might be very slow.

I imagine this is just a case of using `strnlen` instead of `strlen`, but maybe that's not as portable as I might hope.

**Comment by daanx** [comment]
Ouch! -- I'll fix it right away. Yes, we cannot use `strnlen` so we need do our own version of that.

**Comment by daanx** [comment]
Thanks, I think is is fixed now. Since this is a semi security issue I'll do a new release of `mimalloc` soon
