### ISSUE TITLE
Doc note about fork() and huge OS pages

### ISSUE THREAD

**Issue by jasongibson** [microsoft/mimalloc#229]
When a program has MIMALLOC_RESERVE_HUGE_OS_PAGES set and executes the fork() system call, the child process will get its own 1GB allocations on top of what the parent already had.  For server programs that fork() to distribute work, this will cause a lot of unexpected memory growth.

As discussed, this appears to be correct, if unexpected.  A comment in the documentation for MIMALLOC_RESERVE_HUGE_OS_PAGES describing this behavior would be helpful.

Thanks.

**Comment by daanx** [comment]
Hi @jasongibson -- great to see you here :-)  Yes, I remember talking about this and we should indeed add a note about it as it is not obvious I think. I believe, the behavior is:

- on fork, the whole process is copy-on-write (i.e. all pages are marked as read-only)
- while the parent and child execute any pages they write to are copied in (and take up memory)
- if those happen to be huge OS pages (of 1GiB) then the child process memory usage may grow in 1GiB increments for random writes until all huge OS page memory is copied in. 

So, I guess the note should recommend that huge OS page allocation is not recommended when forking. Enabling large OS pages (2MiB) may be ok.  I'll try to  write that down nicely

**Comment by jasongibson** [comment]
Hello :)

That description matches my understanding as well.

**Comment by daanx** [comment]
Thanks!
