### ISSUE TITLE
Global object initialization instability on Windows 7

### ISSUE THREAD

**Issue by jasongibson** [microsoft/mimalloc#230]
Occasionally on Windows 7 (but not newer versions), the initialization of global
objects will fail with a nullptr.  This happens once out of thousands of program executions, but is enough to be noticeable on large test suites.  This is similar to #210, but the fix appears to be different - here, when the first call to VirtualAlloc() fails, a second call to mi_os_get_aligned_hint() and VirtualAlloc() is necessary.

Here's the source for two programs to demonstrate this.  The first (spawn.cc) just creates some global objects that allocate memory.  The second (spawner.cc) repeatedly runs the first.  These will fail reliably after a few minutes.  With the second change to the second call to VirtualAlloc(), they'll run for as long as one cares.

This behavior appears to be new somewhere around the mimalloc 1.4+ range (present still in 1.6.1).  It did not occur in the early 1-s.

Thanks.

///////////
```
  /*
  cl spawn.cc ws2_32.lib User32.lib advapi32.lib kernel32.lib mimalloc-static.lib -I mimalloc/include /EHsc
   */

  # include <iostream>
  # include <mimalloc.h>

  using namespace std;

  class G
  {
  public:
    G( const size_t s )
    {
      ptr = mi_malloc( s );
      if( !ptr )
        {
          cout << "nullptr!" << endl;
          abort();
        }
    }
    ~G() { mi_free( ptr ); }
    void* ptr = nullptr;
  };

  G a( 1 );
  G b( 1 );
  G c( 1 );
  G d( 1 );
  G e( 1 );
  G f( 1 );
  G h( 1 );
  G i( 1 );
  G j( 1 );
  G k( 1 );
  G l( 1 );
  G m( 1 );
  G n( 1 );
  G o( 1 );
  G p( 123 );
  G q( 123 );
  G r( 123 );
  G s( 123 );
  G t( 123 );
  G u( 123 );
  G v( 123 );
  G w( 123 );
  G x( 123 );
  G y( 123 );
  G z( 123 );


  int main( int argc, char** argv )
  {
    void* x = mi_malloc( 1234567 );
    memset( x, '\0', 1234566 );
    cout << "I made it " << &x << endl;
    mi_free( x );
    return 0;
  }

//////////////////

  /*
  cl spawner.cc /EHsc
   */

  # include <chrono>
  # include <climits>
  # include <iostream>
  # include <thread>
  # include <vector>
  # include <windows.h>

  using namespace std;

  void run( const char* cmd )
  {
    STARTUPINFO si;
    PROCESS_INFORMATION pi;

    ZeroMemory( &si, sizeof(si) );
    si.cb = sizeof(si);
    ZeroMemory( &pi, sizeof(pi) );

    // Start the child process.
    if( !CreateProcess( NULL,   // No module name (use command line)
                        (LPSTR)cmd,        // Command line
                        NULL,           // Process handle not inheritable
                        NULL,           // Thread handle not inheritable
                        FALSE,          // Set handle inheritance to FALSE
                        0,              // No creation flags
                        NULL,           // Use parent's environment block
                        NULL,           // Use parent's starting directory
                        &si,            // Pointer to STARTUPINFO structure
                        &pi )           // Pointer to PROCESS_INFORMATION structure
        )
      {
        printf( "CreateProcess failed (%d).\n", GetLastError() );
        return;
      }

    // Wait until child process exits.
    WaitForSingleObject( pi.hProcess, INFINITE );

    // Close process and thread handles.
    CloseHandle( pi.hProcess );
    CloseHandle( pi.hThread );
  }

  int main( int argc, char** argv )
  {
    vector< thread > ts;
    ts.reserve( 100 );

    for( ; ; )
      {
        for( int i = 0; i < 100; i++ )
          {
            cout << i << endl;
            ts.emplace_back( thread( run, "spawn" ) );
          }

        for( auto& t : ts )
          t.join();

        ts.clear();
      }

    return 0;
  }
```

**Comment by daanx** [comment]
@jasongibson: Ah ,that is awesome you found this! I will try to repro on my machine. I think I understand your fix but can you post it here so I can see exactly what you have in mind?  Thanks!
I still like to investigate to see what the error codes are that are returned.

**Comment by daanx** [comment]
Ah, I don't have easy acces to Windows 7 and I see that it does not happen on later Windows versions. It would be nice if you post the fix that worked for you. Perhaps we should enable it always just to be more robust (as long as we don't negatively influence multiple statically linked mimalloc's)

**Comment by jasongibson** [comment]
This is with master@6e1ca96a4965c776c10698c24dae576523178ef5 with a non-debug, non-secure-mode build.

In os.c line 212 (mi_win_virtual_allocx()), the call to VirtualAlloc() almost always returns ERROR_INVALID_PARAMETER (87), but can sometimes return ERROR_INVALID_ADDRESS (487) as well.  Adding another call to mi_os_get_aligned_hint() and VirtualAlloc() often succeeds, but it's not always enough - sometimes it'll fail no matter how many times it's retried, and the part that makes it reliable is to just fall through to the VirtualAlloc() on line 226.  E.g.:

```
diff --git a/src/os.c b/src/os.c
index 0aa85bd..3565021 100644
--- a/src/os.c
+++ b/src/os.c
@@ -209,7 +209,8 @@ static void* mi_win_virtual_allocx(void* addr, size_t size, size_t try_alignment
   // on 64-bit systems, try to use the virtual address area after 4TiB for 4MiB aligned allocations
   void* hint;
   if (addr == NULL && (hint = mi_os_get_aligned_hint(try_alignment,size)) != NULL) {
-    return VirtualAlloc(hint, size, flags, PAGE_READWRITE);
+    void* p = VirtualAlloc(hint, size, flags, PAGE_READWRITE);
+    if (p) return p;
   }
 #endif
 #if defined(MEM_EXTENDED_PARAMETER_TYPE_BITS)
```

**Comment by daanx** [comment]
Hi Jason, thanks again -- I might have a fix in the latest `dev` branch extending on issue #210. I now check for both error conditions which may be just right; but we could be even more aggressive by always ignoring the error and fall through to a bare VirtualAlloc... but if the current solution work I think it is preferable. Can you try?

**Comment by jasongibson** [comment]
It appears to be fixed.  The test has been running for half an hour without issue (where the prior version would fail within a minute or so).

Thank you!
