### ISSUE TITLE
"mi_usable_size" has invalid memory access.

### ISSUE THREAD

**Issue by meltybk** [microsoft/mimalloc#231]
Hi. I found invalid memory access at "mi_usable_size".

"mi_heap_malloc_zero_aligned_at" adjust pointer address to align pointer address.
and "mi_usable_size" does not use "_mi_page_ptr_unalign" to call "mi_page_usable_size_of".
so, "mi_page_decode_padding" read invalid memory(buffer-overrun).

e.g. Allocate 32 bytes, it aligned by 64 bytes.
_mi_heap_malloc_zero returns 0x0000040000040070.(variable p)
and aligned_p became 0x0000040000040080.
finally, "mi_malloc_aligned" returns 0x0000040000040080, and use 0x0000040000040080 to call "mi_usable_size".

https://github.com/microsoft/mimalloc/blob/master/src/alloc-aligned.c#L56

**adjust memory address.**
```C++
  void* aligned_p = (adjust == alignment ? p : (void*)((uintptr_t)p + adjust));
  if (aligned_p != p) mi_page_set_has_aligned(_mi_ptr_page(p), true); 
  mi_assert_internal(((uintptr_t)aligned_p + offset) % alignment == 0);
  mi_assert_internal( p == _mi_page_ptr_unalign(_mi_ptr_segment(aligned_p),_mi_ptr_page(aligned_p),aligned_p) );
  return aligned_p;
```

https://github.com/microsoft/mimalloc/blob/master/src/alloc.c#L471
**Use "_mi_page_ptr_unalign" only for calculate block size.**
```C++
// Bytes available in a block
size_t mi_usable_size(const void* p) mi_attr_noexcept {
  if (p==NULL) return 0;
  const mi_segment_t* const segment = _mi_ptr_segment(p);
  const mi_page_t* const page = _mi_segment_page_of(segment, p);
  const mi_block_t* const block = (const mi_block_t*)p;
  const size_t size = mi_page_usable_size_of(page, block);
  if (mi_unlikely(mi_page_has_aligned(page))) {
    ptrdiff_t const adjust = (uint8_t*)p - (uint8_t*)_mi_page_ptr_unalign(segment,page,p);
    mi_assert_internal(adjust >= 0 && (size_t)adjust <= size);
    return (size - adjust);
  }
  else {
    return size;
  }
}
```

**I think, it should to use "_mi_page_ptr_unalign" to call "mi_page_usable_size_of", too.**
```C++
// Bytes available in a block
size_t mi_usable_size(const void* p) mi_attr_noexcept {
  if (p==NULL) return 0;
  const mi_segment_t* const segment = _mi_ptr_segment(p);
  const mi_page_t* const page = _mi_segment_page_of(segment, p);
  const mi_block_t* block = NULL;
  ptrdiff_t adjust = 0;
  if (mi_unlikely(mi_page_has_aligned(page))) {
	  block = _mi_page_ptr_unalign(segment, page, p);
	  adjust = (uint8_t*)p - (uint8_t*)block;
  }
  else {
	block = (const mi_block_t*)p;
  }
  const size_t size = mi_page_usable_size_of(page, block);
  mi_assert_internal(adjust >= 0 && (size_t)adjust <= size);
  return (size - adjust);
}
```

Thank you.

**Comment by daanx** [comment]
Hi @meltybk , thanks for finding this and giving a fix as well! However, I think this issue was fixed in commit 0047b27 (on the `dev` branch). I should have updated master more early :(  I am about to do a fresh release -- apologies if this caused much trouble.
