### ISSUE TITLE
MIMALLOC_RESERVE_HUGE_OS_PAGES has no effect

### ISSUE THREAD

**Issue by asl** [microsoft/mimalloc#241]
The reason is very simple: the value is checked in ``mi_process_init``, however, the options are processed later in ``mi_process_load``.

**Comment by asl** [comment]
Here is the relevant sequence of events: I'm having mimalloc linked statically with libgomp linked in as a shared library. It looks like libgomp does memory allocation during the load (because is uses sysconf to query for number of CPUs). As a result, mi_thread_init is called before mimalloc's static ctor (and the order of ctors is undefined) that calls ``mi_process_load`` and processes the options....

**Comment by asl** [comment]
So, maybe the handling of huge pages should be moved to mi_process_load?

**Comment by daanx** [comment]
mmm, I am not sure this is correct. When an option is checked for the first time it is `UNINIT` and will call `options.c:mi_option_init` which will get it from the environment. So it should read it correctly. 
At some point, all options are initialized (in `options.c:_mi_options_init`) but this just reads every one of them -- already initialized ones are left alone; this `_mi_options_init` is then mostly just to display all the options that are set in verbose mode. Can you try running with `MIMALLOC_VERBOSE=1`?

**Comment by daanx** [comment]
Some other causes might be, misspelled environment? wrong permissions (see [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/5/html/tuning_and_optimizing_red_hat_enterprise_linux_for_oracle_9i_and_10g_databases/sect-oracle_9i_and_10g_tuning_guide-large_memory_optimization_big_pages_and_huge_pages-configuring_huge_pages_in_red_hat_enterprise_linux_4_or_5) ) although MIMALLOC_VERBOSE should  show a warning in those cases.

**Comment by asl** [comment]
Nope :)

Here we go:
```
mimalloc: process init: 0x7f2af775b1c0                                                                                                                                          mimalloc: secure level: 0                                                                                                                                                       mimalloc: using 4 numa regions
mimalloc: option 'show_errors': 1
mimalloc: option 'show_stats': 0                                                                                                                                                mimalloc: option 'eager_commit': 1
mimalloc: option 'eager_region_commit': 1
mimalloc: option 'reset_decommits': 0
mimalloc: option 'large_os_pages': 0
mimalloc: option 'reserve_huge_os_pages': 10
mimalloc: option 'segment_cache': 0
mimalloc: option 'page_reset': 1
mimalloc: option 'abandoned_page_reset': 0
mimalloc: option 'segment_reset': 0                                                                                                                                             mimalloc: option 'eager_commit_delay': 1
mimalloc: option 'reset_delay': 100
mimalloc: option 'use_numa_nodes': 0
mimalloc: option 'os_tag': 100
mimalloc: option 'max_errors': -1
```

**Comment by asl** [comment]
And yes, I certainly double checked that:

1. mi_process_init is called before mi_process_load
2. mi_option_is_enabled(mi_option_reserve_huge_os_pages) returns false inside mi_process_init

**Comment by asl** [comment]
So, the options are not initialized due to this:
```
  #ifndef _WIN32
  // cannot call getenv() when still initializing the C runtime.
  if (_mi_preloading()) return;
  #endif
```

**Comment by daanx** [comment]
Ah right: the offending code is:
```
#ifndef _WIN32
  // cannot call getenv() when still initializing the C runtime.
  if (_mi_preloading()) return;
  #endif
```
in `options.c`. Tricksy..   I have been thinking about changing this. Already on Windows mimalloc uses `GetEnvironmentVariableA` so it can read the environment even before the CRT is loaded. On Linux we could use

**Comment by asl** [comment]
well, maybe ensure that no options are used during the initialization? And perform kind of two-step init?

**Comment by daanx** [comment]
I considered that but some options are difficult to delay initialization on. Like `use_numa_nodes`, or `eager_commit`. So, the options are now robust against reading "too early" but may return default values while the C runtime is still loading. I think it is better to just make reading the environment possible even before the CRT is loaded.

**Comment by daanx** [comment]
For now, I could try to comment out the `#ifdef` and see if it happens to work? :-)

**Comment by daanx** [comment]
Pushed a possible fix; let me know how it goes.

**Comment by asl** [comment]
So, just removing the ifdef worked, but I guess because I had libc.so loaded by dynamic linker first. Not sure how it'd work if libc would be loaded statically or on some other implementations (e.g. musl or Apple's libc :))

**Comment by daanx** [comment]
Thanks. Did the latest `dev` fix the issue as well?

**Comment by the-oaks** [comment]
@daanx apparently the issue remained in the latest dev, I see the same "warning error" as well

**Comment by daanx** [comment]
Hi @the-oaks, that is strange -- it should work now. Can you provide more information: What platform are you using? What was the environment variable that didn't work? Can you run with `MIMALLOC_VERBOSE` so we can see what was read from the environment. (Do have more than 256 environment variables?).   Thanks!
