### ISSUE TITLE
About experimental environment

### ISSUE THREAD

**Issue by htjung94** [microsoft/mimalloc#250]
Could you tell us more accurately about the experimental environment? For example, what microarchitecture Intel used, hyperthreading, AMD EPYC Naples or ROME, and so on.

**Comment by daanx** [comment]
The tests were done on standard Amazon EC2 instances (like [c5.18xlarge](https://aws.amazon.com/ec2/instance-types/#Compute_Optimized)) so you can find out all information from there.
