### ISSUE TITLE
how does mimalloc calculate the page and segment through the mask when releasing memory？

### ISSUE THREAD

**Issue by diricse** [microsoft/mimalloc#256]
how does mimalloc calculate the page and segment through the mask when releasing memory？That codes what I do not  understand
// Segment that contains the pointer
static inline mi_segment_t* _mi_ptr_segment(const void* p) {
  // mi_assert_internal(p != NULL);
  return (mi_segment_t*)((uintptr_t)p & ~MI_SEGMENT_MASK);
}

**Comment by daanx** [comment]
Ah, it is a bit tricky, but essentially, mimalloc aligns all segments on a 4MiB boundary to find the metadata belonging to a pointer. The technical gives more details if you are interested:
<https://www.microsoft.com/en-us/research/publication/mimalloc-free-list-sharding-in-action>

**Comment by diricse** [comment]
thank you,becase  mimalloc get memory from OS,so segments boundary is zero?
