### ISSUE TITLE
iOS Best Practices

### ISSUE THREAD

**Issue by victorstewart** [microsoft/mimalloc#260]
Just thought it would be helpful to amalgamate the instructions here so that anyone else in the future can find this via google.

So am I correct that because `MI_INTERPOSE` and `MI_OVERRIDE` are on by default, that all I need to do is compile and link the object file to my application, and then the interposition will automatically occur upon boot? 

And for C++, also include the `mimalloc-new-delete.h` header in a single file (say main.c).

**Comment by daanx** [comment]
I close this issue to consolidate porting to iOS in #263
