### ISSUE TITLE
Documentation is out of date (e.g. mi_option_enable())

### ISSUE THREAD

**Issue by rgal** [microsoft/mimalloc#266]
On the page: https://microsoft.github.io/mimalloc/group__options.html, mi_option_enable is listed as:
```
void mi_option_enable (mi_option_t option, bool enable)
```
with 2 parameters. This is an old format which was replaced with a single parameter in 03d994648af1df2104858aac2eb08f1433894734.

Please can you update the documentation?

This also looks wrong here: https://github.com/microsoft/mimalloc/blob/07c6e60a5a3bd7de09e4a170cd97bafba59cfafd/docs/group__options.html

Thanks
Russ

**Comment by thomcc** [comment]
Also has the wrong order (or is misleading) for `mi_option_show_errors` and `mi_option_show_stats`.

**Comment by daanx** [comment]
Apologies for the late reply, I merged the fix in the `dev` branch.
