### ISSUE TITLE
realloc() crash that could be avoided - like you do it for free()

### ISSUE THREAD

**Issue by Frank-Vog** [microsoft/mimalloc#269]
Hi, we have evaluated Mimalloc and have seen that a protection done for free() is missing for realloc() - hence a crash that could be avoided (for free(), you check if the pointer alignment is matching your mimalloc-page's alignment). Here is the test-case:
```
  {  
     char *p1 = malloc(16); free(p1);
     puts("--- test double-free() ------------------------------------------");
     free(p1);
     
     puts("--- test free(NULL) ---------------------------------------------");
     free(NULL);

     puts("--- test free(0xbadbeef) ----------------------------------------");
     free((void*)0xBADBEEF);

     puts("--- test realloc(0xbadbeef) -------------------------------------");
     p1 = realloc((void*)0xBADBEEF, 123); 
  }
```
Keep up the good work!

Cheers from Switzerland.

**Comment by daanx** [comment]
Thanks for the feedback, I do the same check now for `mi_realloc`, `mi_usable_size` and `mi_expand` (all of which take pointer arguments). Best, Daan
