### ISSUE TITLE
`posix_memalign` should not modify returned pointer on errors

### ISSUE THREAD

**Issue by Lastique** [microsoft/mimalloc#27]
In [`posix_memalign`](https://github.com/microsoft/mimalloc/blob/06f8da4218a6e86f0418e249a99faa9957c2ec5f/src/alloc-override.c#L132) override, the function modifies the resulting pointer, even if the allocation fails due to `ENOMEM`. Accodring to [docs](http://man7.org/linux/man-pages/man3/posix_memalign.3.html), `posix_memalign` should not modify the returned pointer on failure.

**Comment by Lastique** [comment]
Actually, it modifies the pointer when it returns `EINVAL` too.

**Comment by daanx** [comment]
Great catch! I am not sure I personally agree with this behaviour but I pushed a fix to be posix compliant (almost, I don't return EINVAL when alignment is not a power of 2.. todo...)
