### ISSUE TITLE
Clarify the version of glibc tested in the benchmarking figures in README.md?

### ISSUE THREAD

**Issue by codonell** [microsoft/mimalloc#270]
The glibc version quoted in the README.md benchmark figures says "2.7.0" but this is likely just the point at which the sources for glibc were forked from Doug Lea's ptmallo2, hence the "based on:" part of the comment.

It would be good to know the released version of glibc that was used for testing and which distribution it came from to determine exactly what was being tested i.e. does it have tcache enhancements or not.

Thank you!

**Comment by daanx** [comment]
Hi, thanks for bringing this up. I believe it is the version of ptmalloc2 that has the enhancements as I remember seeing improved performance with respect to Ubuntu 16 (which I used before). The benchmarks are on a standard Ubuntu 18.04.1 image provided by EC2. I just logged in to a `r5a.12xlarge` instance and got:
```
ubuntu@ip-xxx:~$ linuxinfo
Linux ip-xxx 5.3.0-1017-aws #18~18.04.1-Ubuntu SMP Wed Apr 8 15:12:16 UTC 2020
48 AMD Unknown 3010MHz processors, 211199.44 total bogomips, 383569M RAM
System library 2.27.0
```
and
```
ubuntu@ip-xxx:~$ ldd --version
ldd (Ubuntu GLIBC 2.27-3ubuntu1) 2.27
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
(I am not sure where I got my `2.7.0` from? Perhaps a typo?).   Can you clarify if this (`2.27.0`) is the version with the improvements?

**Comment by daanx** [comment]
And also (not sure if this helps):
```
ubuntu@ip-xxx:~$ /lib/x86_64-linux-gnu/libc.so.6 --version
GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.2) stable release version 2.27.
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 7.5.0.
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.
```

**Comment by codonell** [comment]
@daanx You got it right, it's release glibc 2.27 with any Ubuntu specicific patches. I expect it should behave almost identically to a stock glibc 2.27, so it would be most accurate to mark it as `(glibc, 2.27)` (without a zero at the end).

**Comment by daanx** [comment]
Great, I'll update the readme. Thanks.
