### ISSUE TITLE
functions not defined.

### ISSUE THREAD

**Issue by Soumendu003** [microsoft/mimalloc#273]
I was building a static library by creating .a file compiling src files.

It shows that 
1. pthread_key_create method is called in init.c (line 324) but not defined.
2. pthread_setspecific method is called in init.c (line 391) but not defined.

**Comment by daanx** [comment]
Hi, apologies for the late reply. Those functions are from the Posix threads library; you need to link with `-lpthread` when building your final executable. (this should happen automatically when using `cmake` though...). 
Hope this helps
