### ISSUE TITLE
Arm64 Musl stress test fails

### ISSUE THREAD

**Issue by Tyler-IN** [microsoft/mimalloc#275]
(With https://github.com/microsoft/mimalloc/pull/274)

- [x] x86_64 GLibC builds
- [x] x86_64 GLibC test succeeds
- [x] x86_64 Musl builds
- [x] x86_64 Musl test succeeds
- [x] Arm64 GLibC builds
- [x] Arm64 GLibC test succeeds
- [x] Arm64 Musl builds
- [ ] Arm64 Musl test succeeds
```
Running tests...
Test project /app
    Start 1: test_api,
1/2 Test #1: test_api, ........................   Passed    0.02 sec
    Start 2: test_stress,
2/2 Test #2: test_stress, .....................***Exception: SegFault  0.02 sec

50% tests passed, 1 tests failed out of 2

Total Test time (real) =   0.07 sec

The following tests FAILED:
          2 - test_stress, (SEGFAULT)
```

**Comment by daanx** [comment]
Thank you for your report (and PR for musl support :-)).  Ah, that is scary it only fails for the ARM build of musl. Can you provide more information? i.e. build with `-DMI_DEBUG_FULL=ON` and run `./mimalloc-test-stress` directly (or in `gdb`) to see a stack trace?

**Comment by daanx** [comment]
I am going to close this for now -- if you can repro in debug mode or give a stack trace we can look at this again. Thanks.

**Comment by Tyler-IN** [comment]
@daanx would you like a PR w/ GitHub Actions (and https://github.com/marketplace/actions/docker-buildx ) that builds and runs tests on these platforms?
