### ISSUE TITLE
aligned_alloc is not overriden unless a C++ compiler is used

### ISSUE THREAD

**Issue by oliver-giersch** [microsoft/mimalloc#276]
in `alloc_override.c` the override of `aligned_alloc` is conditioned as follows:

```c
// on some glibc `aligned_alloc` is declared `static inline` so we cannot override it (e.g. Conda). This happens
// when _GLIBCXX_HAVE_ALIGNED_ALLOC is not defined. However, in those cases it will use `memalign`, `posix_memalign`, 
// or `_aligned_malloc` and we can avoid overriding it ourselves.
#if _GLIBCXX_HAVE_ALIGNED_ALLOC
void* aligned_alloc(size_t alignment, size_t size)   { return mi_aligned_alloc(alignment, size); }
#endif
```
From what I can see, this makes it impossible to override `aligned_alloc` when compiling mimalloc with a C compiler. When I set the `MI_USE_CXX` option, the override was correctly compiled. This was with both GCC 10.1.0 and clang 10.

**Comment by daanx** [comment]
Thanks for the report, and apologies for the late reply. Ah, `aligned_alloc` causes much trouble :-(   I looked around a bit and it seems it should be ok to do a check for `__cplusplus` here but I am still a bit worried that it may lead to a compilation error with Conda; not sure...

```
#if _GLIBCXX_HAVE_ALIGNED_ALLOC || !defined(__cplusplus)
```

**Comment by daanx** [comment]
Fixed in the latest `dev` -- fingers crossed it won't cause compilation errors on other configurations

**Comment by asl** [comment]
For the record: looks like conda is using 11-year old glibc that implements some C11 features (including `aligned_alloc`) in a standard non-compliant way.
