### ISSUE TITLE
Vista compatibility

### ISSUE THREAD

**Issue by jeroen** [microsoft/mimalloc#277]
When we run a program on Windows Server 2008 / Vista, I see:

<img width="528" alt="Screen Shot 2020-07-20 at 12 01 35 AM" src="https://user-images.githubusercontent.com/216319/87920717-df093e80-ca79-11ea-8b04-81100bcec2a2.png">

I see that a polyfill for this function is declared, but not implemented, on vista? Is this expected to work?

https://github.com/microsoft/mimalloc/blob/07c6e60a5a3bd7de09e4a170cd97bafba59cfafd/src/os.c#L1022-L1034

**Comment by daanx** [comment]
Thanks for the report; I think I have fixed the issue in the latest `dev` branch by using a dynamic fallback. Let me know if this works for you.
