### ISSUE TITLE
statically linked mimalloc to a dll, leaks memory in release mode

### ISSUE THREAD

**Issue by priyeshwadhwa** [microsoft/mimalloc#281]
In this case mimalloc is statically built and linked to a dll, which is loaded and unloaded frequently in a long running process.
In the files init.c and heap.c there are code blocks that free up the memory in debug mode. Why is it not enabled for release mode. 
With a simple one mi_malloc(8192) allocation, a region (256MB) is lost with every load-unload event.

#init.c
  #ifndef NDEBUG
  mi_collect(true);
  #endif

heap.c

  #ifndef NDEBUG
  // collect regions
  if (collect >= MI_FORCE && _mi_is_main_thread() && mi_heap_is_backing(heap)) {
    _mi_mem_collect(&heap->tld->os);
  }
  #endif

Not sure if I am doing something wrong or is this a bug.

**Comment by daanx** [comment]
Hi @priyeshwadhwa, thanks for the report. I am not sure if it is a bug or feature yet :-)   Generally, when a process is terminated `mimalloc` does not collect as the resources (i.e. mmap'd memory) is freed anyway. We call `mi_collect` in debug mode just for extra debugging. If mimalloc is statically linked into a DLL that is dynamically loaded/unloaded I feel it is best if the DLL calls `mi_collect(true)` explicitly itself.  However, I realize now that might be not entirely right -- the DLL itself could still have allocated memory that is only freed when, say, static destructors are called, and the `mi_collect` should really be handled by mimalloc in that case as it will be last thing to run before unloading.  We may indeed want to remove the `#ifndef NDEBUG` in both places to just always collect on process termination. I need to think a bit more about this as it would impact performance for regular executables which could skip this step on termination.

**Comment by daanx** [comment]
I fixed the issue for now by enabling collection on process exit by default for a statically linked mimalloc. However, the best solution would be to detect if the exit is truly the process exit or an exit caused by a shared library unload. I do not know yet of a way to detect this though -- if it is not possible we may make this a configuration option in the future.

**Comment by priyeshwadhwa** [comment]
Thanks @daanx, Appreciate the quick response and fix 👍

**Comment by LuJyKa** [comment]
Accoring to https://github.com/microsoft/mimalloc/blob/db3d8485d2f45a6f179d784f602f9eff4f60795c/src/init.c#L706
use mi_thread_done() is better
