### ISSUE TITLE
Incorrect number of numa nodes detected on windows

### ISSUE THREAD

**Issue by myrsloik** [microsoft/mimalloc#282]
The number of numa nodes is incorrectly detected in some cases. Most likely due to the misuse of GetNumaHighestNodeNumber() which can't be used by itself and needs additional checks to determine the real number of nodes.

On windows 10 when running on a threadripper 1950x CPU in UMA mode GetNumaHighestNodeNumber() returns 1 (interpreted as 2 nodes) but if you actually look at how the threads are distributed all 32 of them end up in the first node. It's obvious the second one should be disregarded.

```
    ULONG maxNumaNode;
    if (GetNumaHighestNodeNumber(&maxNumaNode)) {
        for (ULONG i = 0; i <= maxNumaNode; i++) {
            ULONGLONG mask;
            if (GetNumaNodeProcessorMask(i, &mask)) {
                printf("%#016llX\n", mask);
            }
        }
    }
```

Output:
```
0X000000FFFFFFFF
0000000000000000
```

**Comment by daanx** [comment]
Thanks for the report -- that is no good. A workaround for this is to set the nodes explicitly to 1, as `MIMALLOC_USE_NUMA_NODES=1` in the environment (or programmatically). But clearly this needs to be fixed -- perhaps by checking explicitly if the processor mask returns 0 ?  

(ps. I wonder what Linux reports for the NUMA nodes in this case? If you happen to have Linux installed, could you try running a mimalloc program with `MIMALLOC_VERBOSE=1` see how many nodes it uses?)

**Comment by daanx** [comment]
I think the latest `dev` should fix the issue. Let me know.

**Comment by myrsloik** [comment]
Yes, the correct number is now used for me. I'll try to test it on linux as well when I have time.
