### ISSUE TITLE
ASLR entropy is very low in mimalloc-secure

### ISSUE THREAD

**Issue by pr0cf5** [microsoft/mimalloc#289]
The execution environment is ubuntu 18.04 latest.
```c
// address range [0x40000802000 - 0x40000917021] is allocated at a rate of 0.570000
// address range [0x40000942000 - 0x40000a57021] is allocated at a rate of 0.430000
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <malloc.h>

void* p[256];
uintptr_t buf[256];

int main() {
  p[0] = malloc(378200);
  p[1] = malloc(1134626);
  return 0;
}
```

When executing the code above, the heap memory range is quite predictable. It is, by 100% either one of 0x40000802000 - 0x40000917021 or 0x40000942000 - 0x40000a57021, so it may be prone to heap spray attacks. The main reason is because the base address is fixed to 0x40000000000.

**Comment by daanx** [comment]
Ah that is unexpected; Did you run in debug mode? In that case ASLR is disabled for `mimalloc` to be more deterministic.

**Comment by daanx** [comment]
I tested this and I think you were running in debug mode.

**Comment by insuyun** [comment]
Hi. I think that would be nice if you mention this in the documentation.
I checked documentation but fails to find this until I read code.

**Comment by daanx** [comment]
Hi @insuyun, 

Yes you are right; I'll add it to the documentation. 

Hmmm, on the other hand, maybe it is better to always enable ASLR in secure mode just to avoid this kind of surprise. 
(and if you need determinism for debugging then one can always compile outside secure mode).  I'll sleep on it but I think that is probably a better solution.  Thanks for bringing this to attention again :-)

**Comment by insuyun** [comment]
Thank you :)

**Comment by daanx** [comment]
Thanks Insu -- I just pushed a commit to make ASLR to be always on in secure mode to avoid future security surprises.
Good luck with the paper and send me a draft when you can :-) -- let me know if there are any further issues that I can address.

**Comment by daanx** [comment]
Ouch, looking at the commit I realized my logic was wrong -- it was already fixed! The test
```C
#if (MI_SECURE>0 || MI_DEBUG==0)
```
should always trigger in either secure or non-debug mode so it should already always do ASLR in secure mode even with debugging enabled. However, when I look back in the repo to 2020-08-09, it looks like it was already like this when the issue was raised so I wonder how that came about?
(see: <https://github.com/microsoft/mimalloc/blob/5805c399168a8a6c02d787741239481f69f920dc/src/os.c#L472>)

**Comment by insuyun** [comment]
Oh, I checked that my student said that he used older version.
I think now it seems ok.
Thank you for letting us know.

Best,
Insu Yun
