### ISSUE TITLE
Memory usage increases even through blocks are freed

### ISSUE THREAD

**Issue by dcristoloveanu** [microsoft/mimalloc#292]
Hi!

We are using mimalloc in a service and have noticed that over time there is less and less memory available on the machine where the service runs.
We are doing some in isolation experiments, to narrow down whether the issue is really and issue or it is just an expected behavior from mimalloc for our workload.

We ended up with the following (rather simple) sequence as a repro:
- Repeat for 100 times (or more):
  - Allocate an array of 300000 pointers
  - Allocate 300000 memory blocks. Each odd memory allocation is 128K, the even ones are 512 bytes. Effectively interleaving 128K and 512 bytes allocations
  - Free all 300000 blocks

After running our process still shows the memory in use even though free has obviously been called.

We tried calling mi_collect at each iteration of 300000 allocations to force reclaiming the memory, but it did not help (with or without force).

Is there something I am doing wrong or is there some way I can mitigate this?

Also an interesting aspect is that stats say that "Not all freed" for the reserved and committed rows of the stats:

```
heap stats:     peak      total      freed       unit      count
  reserved:    19.0 gb    19.0 gb       0 b        1 b              not all freed!
 committed:    19.0 gb    19.0 gb       0 b        1 b              not all freed!
     reset:       0 b        0 b        0 b        1 b              ok
   touched:       0 b        0 b   1838.8 gb       1 b              ok
  segments:     4.7 k    476.4 k    476.4 k                         ok
-abandoned:       0          0          0                           ok
   -cached:       0          0          0                           ok
     pages:    39.1 k      3.8 m      3.8 m                         ok
-abandoned:       0          0          0                           ok
 -extended:       0
 -noretire:       0
     mmaps:       0
   commits:     4.8 k
   threads:       0          0          0                           ok
  searches:     0.0 avg
numa nodes:       1
   elapsed:       4.078 s
   process: user: 3.234 s, system: 0.843 s, faults: 1548488, reclaims: 0, rss: 5.8 gb, commit charge: 19.0 gb
```

The code is below, let me know if more information is needed!

Thanks,
/Dan

```c
// Copyright (c) Microsoft. All rights reserved.

#include <stddef.h>
#include <stdlib.h>
#include <stdint.h>
#include <mimalloc.h>

#define ALLOC_COUNT                 300000
#define ALLOC_CYCLES                100

int main(void)
{
    size_t iter;
    // loop several times
    for (iter = 0; iter < ALLOC_CYCLES; iter++)
    {
        // arrange
        uint32_t i;

        // allocate an array of pointers
        void** blocks = (void**)mi_malloc(sizeof(void*) * ALLOC_COUNT);

        // act
        // allocate the memory by alternating 128K and 512 blocks
        for (i = 0; i < ALLOC_COUNT; i++)
        {
            blocks[i] = mi_malloc(i % 2 ? (128 * 1024) : 512);
        }

        // assert
        // free all blocks
        for (i = 0; i < ALLOC_COUNT; i++)
        {
            mi_free(blocks[i]);
        }

        // free the array of pointers
        mi_free(blocks);

        // force mimalloc to collect (aggresively)
        mi_collect(true);
    }

    // print stats - this shows that not all are free???
    mi_stats_print_out(NULL, NULL);

    // just loop while collecting - just in case
    while (1) mi_collect(true);//    size_t failedTestCount = 0;
}
```

**Comment by daanx** [comment]
Hi @dcristoloveanu ,  thanks for your report and working with me :-)  As we discussed this is expected behaviour from this program but I respond here to document it. Because it is not touching the memory it allocates , at first we only see the use for OS pages that are touched due to metadata. For the segments of 4MiB some contain small mimalloc pages and others big ones. When segments get reused, slowly all segments will at some time be used for small mimalloc pages (instead of the original big ones) and thus OS page touching increases until all metadata for all small pages is touched at which point it stabilizes.

**Comment by dcristoloveanu** [comment]
Ty @daanx!
