### ISSUE TITLE
`mi_heap_check_owned` and `mi_heap_contains_block` both return false for large allocation.

### ISSUE THREAD

**Issue by playXE** [microsoft/mimalloc#299]
I'm using Rust bindings for mimalloc and when I try to allocate some large pointer ( >= ~2mb) both functions return false. Testing code is:
```rust
        let heap = mi_heap_new();
        let p = mi_heap_malloc(heap, 4 * 1024 * 1024);
        println!("{:p}", p);
        println!(
            "{}",
            mi_heap_contains_block(heap, p) && mi_heap_check_owned(heap, p)
        );
        println!("{}", mi_heap_contains_block(heap, p));
        println!("{}", mi_heap_check_owned(heap, p));
```
And result is:
```
0x6b5ccc02000
false
false
false
```

This thing should probably return true for even such large pointers? Usefull for this issue #298

**Comment by daanx** [comment]
large blocks are not owned by a heap (but considered abandoned) so it is expected.

You should try `mi_is_in_heap_region` instead -- I discussed this in #298.  (closing this issue for now)

Thanks!
