### ISSUE TITLE
Prefix CMake variables/options

### ISSUE THREAD

**Issue by seanmiddleditch** [microsoft/mimalloc#3]
The `CMakeLists.txt` currently unprefixed variables like `SECURE` or `OVERRIDE`. This can be messy and problematic when mimalloc is added to a project via `add_subdirectory`. Library projects like this ideally should use prefixed variables, e.g. `MIMALLOC_SECURE` rather than `SECURE`, so that amalgamations of multiple third-party dependencies used in larger monolithic projects don't end up with name conflicts or messy configuration pages.

**Comment by daanx** [comment]
Thanks for the suggestion! Currently, mimalloc provides two functions for this, `mi_usable_size` and `mi_good_size`, see:
<https://github.com/microsoft/mimalloc/blob/master/include/mimalloc.h#L107>

I think it is better to have these as separate functions to avoid duplicating all allocation API functions.

Soon, I'll have the full doxygen docs online that gives an easier overview of the whole API
Thanks!

**Comment by daanx** [comment]
Fixed it by prefixing all options with MI_
