### ISSUE TITLE
assertion: "tld->pages_reset.first == NULL"

### ISSUE THREAD

**Issue by jasongibson** [microsoft/mimalloc#310]
Occasionally when a multithreaded process linked with mimalloc is interrupted on
Windows via ctrl-c, it hits the following exception:

  mimalloc: assertion failed: at "C:\mimalloc\segment.c":539, _mi_segment_thread_collect
    assertion: "tld->pages_reset.first == NULL"

Commit 58fdcbb0cd6fbe426237f334ba4a7cf8decebf35 added the assert.  This
is this with v1.6.4.

Is this worth looking into?

**Comment by daanx** [comment]
Hi Jason -- as always, thanks so much for all your help on mimalloc!  

This is benign (I think): in full debug mode all threads always clean up the full memory on termination so during a regular run without memory leaks, the page reset lists should be empty on termination. However, if you ctrl+c / `abort` / `longjmp` out of it with unfreed memory, there may be segments still alive with resettable pages. So, the assertion is too strong really -- I already added the `if (!mi_is_main_thread())` check to avoid this assertion for the main thread that often has still live memory allocated by the C runtime or loader and thus usually fails this check as well.

**Comment by jasongibson** [comment]
Thank you for the explanation.  It's a harmless thing where it's showing up, so we'll just ignore it.
