### ISSUE TITLE
mi_usable_size Utility

### ISSUE THREAD

**Issue by victorstewart** [microsoft/mimalloc#319]
I'm trying to ascertain whether it's beneficial to make core usage of `mi_usable_size`.

Say I'm running on Linux and x86, and I ask for 64 bytes... might I receive 70 bytes, or might I receive 1000 bytes? (I know those values make no sense but I'm just asking what kind of secret extra capacity might be lurking).

I assume memory is allocated about a new fixed sized blocks? What are those sizes?

**Comment by daanx** [comment]
Well, there is not much use for `mi_usable_size` in general; for example, in debug mode the usable size is exactly the requested size. In release mode though you may have a bit more, but generally at most 12.5% of the requested size; i.e. the 70 bytes will be rounded to 80 bytes. (The only use for `mi_usable_size`  I know of is for systems that need to generally access heap blocks and can thus use it to get the safe size that can be accessed.)  If you need a larger block than requested, of course use `mi_realloc` which will realloc in-place when it can.

Maybe `mi_good_size` is more useful to you? It returns for given request the size that mimalloc will round to internally. So, if you want to allocate a buffer of, say, 1300 bytes, it may be better to use `mi_good_size(1300)` and use the next largest size without wasting a potential 12.5%.

Hope that helps

**Comment by victorstewart** [comment]
thank you!
