### ISSUE TITLE
mingw shared lib 32bits doesn't link

### ISSUE THREAD

**Issue by yamashi** [microsoft/mimalloc#328]
Hello,

Using mingw in 32bits fails to link due to a linker error:
```
D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/mimalloc.dir/objects.a(init.c.obj):init.c:(.text+0x40): undefined reference to `_imp__mi_allocator_done'
D:/a/_temp/msys/msys64/mingw32/lib/gcc/i686-w64-mingw32/10.2.0/../../../../i686-w64-mingw32/bin/ld.exe: CMakeFiles/mimalloc.dir/objects.a(init.c.obj):init.c:(.text+0x795): undefined reference to `_imp__mi_allocator_init'
```

Running the exact same build on 64 bits works perfectly.

Using release: 1.6.7

See: https://github.com/xmake-io/xmake-repo/pull/108/checks?check_run_id=1360578102

**Comment by daanx** [comment]
Ah, I think that is because you link with `mimalloc-redirect` and not `mimalloc-redirect32`. That should fix it.

**Comment by giordano** [comment]
> Ah, I think that is because you link with `mimalloc-redirect` and not `mimalloc-redirect32`. That should fix it.

Well, the CMake file links to `mimalloc-redirect` and not `mimalloc-redirect32`:
https://github.com/microsoft/mimalloc/blob/b19da8e362acae8944c60a40cf5c40c8f5ebeb44/CMakeLists.txt#L268

**Comment by miguelraz** [comment]
It's possible a renaming was also missed on the line just below as well, it's missing a `mimalloc-redirect32`.
https://github.com/microsoft/mimalloc/blob/b19da8e362acae8944c60a40cf5c40c8f5ebeb44/CMakeLists.txt#L270
