### ISSUE TITLE
mimalloc cannot compile in gcc 4.8

### ISSUE THREAD

**Issue by ydch1014** [microsoft/mimalloc#330]
https://github.com/microsoft/mimalloc/blob/13a4030619edada133e1a3c06c6287ad5a9c74c1/src/alloc.c#L749

Hi, I am testing in centos7. gcc 4.8. And no stdatomic.h header file. 
So I turn to use g++ to compile mimalloc. That's almost ok. 
Only one issue found: in gcc 4.8 , no std:get_new_handler 

I modify locally like this:
 ```c++
#if __cplusplus >= 201103L
  std::new_handler h = std::get_new_handler();
#else
  std::new_handler h = std::set_new_handler();
  std::set_new_handler(h);
#endif
```

**Comment by daanx** [comment]
Thanks so much :-) Fixed.
