### ISSUE TITLE
Building on 32bit Linux in C++ mode fails due to type mismatch

### ISSUE THREAD

**Issue by NickPoole** [microsoft/mimalloc#337]
```
In file included from ../mimalloc/mimalloc-types.h:13,
                 from ../mimalloc/mimalloc-internal.h:11,
                 from ../mimalloc/static.c:17:
../mimalloc/os.c: In function 'void* mi_unix_mmap(void*, size_t, size_t, int, bool, bool, bool*)':
../mimalloc/mimalloc-atomic.h:48:104: error: no matching function for call to 'atomic_store_explicit(std::atomic<unsigned int>*, long unsigned int, std::memory_order)'
 #define mi_atomic_store_release(p,x)             mi_atomic(store_explicit)(p,x,mi_memory_order(release))
                                                                                                        ^
../mimalloc/os.c:424:11: note: in expansion of macro 'mi_atomic_store_release'
           mi_atomic_store_release(&large_page_try_ok, 10UL);  // on error, don't try again for the next N allocations
           ^~~~~~~~~~~~~~~~~~~~~~~
```

In `os.c:424` there's a call to `mi_atomic_store_release(&large_page_try_ok, 10UL);` which is fine on 64bit Linux where uintptr_t is a long unsigned int. On 32bit, uintptr_t is just an unsigned int.

My workaround was to just cast to uintptr_t: `mi_atomic_store_release(&large_page_try_ok, (uintptr_t)10);`. 

If that fix seems suitable, I can PR the diff.

**Comment by daanx** [comment]
Thanks for catching this :-)  Darn, constants are always troublesome. Does writing `10U` work? then it could be extended to 10UL by the compiler on  64-bit and also work. I'll give it a try and otherwise use your solution :-)

**Comment by NickPoole** [comment]
Unfortunately `10U` causes the same error, but on 64bit.

I think the exact type matching requirement is the defect mentioned on https://en.cppreference.com/w/cpp/atomic/atomic_store

**Comment by daanx** [comment]
Fixed :-) Thanks.
