### ISSUE TITLE
-march=native should be a user choice

### ISSUE THREAD

**Issue by rpavlik** [microsoft/mimalloc#361]
This part of the build system:

https://github.com/microsoft/mimalloc/blob/92ead2d88061dde1264800b389b744ac1b79cf39/CMakeLists.txt#L194-L199

caused SolveSpace ("us") to trigger an "error" in the Debian QA process build log scanner: see

- https://github.com/solvespace/solvespace/issues/934
- https://qa.debian.org/bls/packages/s/solvespace.html - with details of why this is scanned and errored: https://qa.debian.org/bls/bytag/E-march-native.html
- the pretty trivial patch I applied in the SolveSpace package to fix it: https://salsa.debian.org/science-team/solvespace/-/blob/master/debian/patches/0007-Remove-march-native-from-mimalloc-build.patch

**Comment by devnexen** [comment]
reminds me of a PR merged weeks ago ... wonders if the dev branch works better ?

**Comment by rpavlik** [comment]
It's just the existence of the code adding the build flag `-march=native` that is the problem: not how it's guarded. (It's guarded in master differently than in 2.0.0). Dev has the same thing. That entire chunk of CMake code should go away: it silently optimizes for the build machine.

**Comment by devnexen** [comment]
ah right this is understandable from wide package build for so many possible targets.

**Comment by daanx** [comment]
Let's continue  this in the PR #362
