### ISSUE TITLE
Is it safe to invoke `mi_free` inside `mi_heap_visit_blocks`?

### ISSUE THREAD

**Issue by playXE** [microsoft/mimalloc#369]
I invoke this function in GC to sweep objects and all dead objects should be freed, question is is it safe to invoke `mi_free` inside `mi_heap_visit_blocks`?

**Comment by daanx** [comment]
It depends :-)  The visitor functions are written such that the current page can "freed" (if all blocks in there get freed) but it would go wrong if _other_ pages get freed (as it saves the "next" page to visit and that might no longer exist if you call `mi_free` on blocks in the "next" page. But it _is_ safe to call `mi_free` on blocks in the page that is currently visited; However, visitor function is called for each block as it was snapshotted at the start -- if any blocks that are freed inside the visitor functions that will not be reflected.  You can see the code in `src/heap.c` for clarification.

**Comment by playXE** [comment]
I actually found out that mi_heap_visit_blocks is slower than iterating ordered vector, but thanks for answer! :)
