### ISSUE TITLE
please release prebuilt binaries for windows and linux 

### ISSUE THREAD

**Issue by omac777** [microsoft/mimalloc#37]
Hi there, 

For the linux side of things making the .a/.so should be straighforward enough.
For the windows side of things however, it would have been nice to release some pre-build binaries for windows 10 to things out with.

Also, it would have been nice to simply msbuild.exe ide/vs2017/mimalloc.sln
giving examples to build it at the command line with different mstools versions.
How do we query for the available install mstools versions we have to pass it at the msbuild command line and force it to use that?

Thank you for listening.

**Comment by daanx** [comment]
This is now partially addressed through the Azure pipelines. I hope to do a first release early next week

**Comment by omac777** [comment]
```
mkdir build
cd build
cmake -G "Visual Studio 15 2017 Win64" ..
MSBuild libmimalloc.sln /p:Configuration=Release /p:Platform=x64

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:12.06
```
