### ISSUE TITLE
cmake build

### ISSUE THREAD

**Issue by chengm349** [microsoft/mimalloc#387]
I followed the build steps to build on my platform. the script will use /bin/cc which on my platform is of version gcc 4.8.5. And the script will complain no <stdatomic>.  However I have higher GCC compiler installed under /opt/rh/devtoolset-7/root/bin for example. Is there anyway user can inform cmake to use other C compiler?

**Comment by devnexen** [comment]
you can pass to cmake `-DCMAKE_C_COMPILER=/opt/rh/devtoolset-7/root/bin/gcc` (your binary ought to be gcc unless you build it program suffix/prefix option :-))

**Comment by chengm349** [comment]
thanks and it works.
