### ISSUE TITLE
Make aligned heap alloc public

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#39]
currently mi_heap_malloc_zero_aligned_at is not on the public api, and there is no aligned heap api's, it should be fairly simple and useful to have this as a public api right?

I can make a PR if wanted, I just got curious why it isn't so already.

**Comment by daanx** [comment]
Hi Santagada, thanks for your feedback: there are many alignment functions, see:
<https://microsoft.github.io/mimalloc/group__aligned.html>

The `mi_heap_malloc_zero_aligned_at` is the internal function that all the others use.
The function [`mi_zalloc_aligned`](https://microsoft.github.io/mimalloc/group__aligned.html#ga0cadbcf5b89a7b6fb171bc8df8734819) does zero initialized aligned allocation.
Hope that helps :-)

**Comment by santagada** [comment]
none of these take a heap as a parameter, that is my problem, doing aligned allocations on a particular heap

**Comment by daanx** [comment]
Ah I see! I will add this to the API surface.

**Comment by daanx** [comment]
Done in the latest dev branch :-)
