### ISSUE TITLE
Should `docs/` directory be removed from the repository?

### ISSUE THREAD

**Issue by jserv** [microsoft/mimalloc#395]
At the moment, the files in [docs](https://github.com/microsoft/mimalloc/tree/master/docs) are generated by Doxygen, and the name `docs` might confuse someone who discover the `doc/` directory. I think that removing `docs/` directory from the Git repository can make the source tree neater.

**Comment by daanx** [comment]
Ah, the `docs` directory is actually the website for the [documentation](https://microsoft.github.io/mimalloc/) so it would not be good to remove it. It must be named `docs` as well as github expects as specific directory. (it can be done otherwise using a special branch but this seems easiest).

**Comment by jserv** [comment]
I see. I usually use tools such as `grep` to figure out the desired keywords, and the existence of `docs/` directory makes the output of `grep` searching hard to read since it contains the essential functions, structures, and definitions. Thanks for the explanation.
