### ISSUE TITLE
Why #pragma once?

### ISSUE THREAD

**Issue by Gymmasssorla** [microsoft/mimalloc#40]
Why you write `#pragma once` in these header files?
 - https://github.com/microsoft/mimalloc/blob/master/include/mimalloc.h#L7
 - https://github.com/microsoft/mimalloc/blob/master/include/mimalloc-types.h#L7
 - https://github.com/microsoft/mimalloc/blob/master/include/mimalloc-internal.h#L7
 - https://github.com/microsoft/mimalloc/blob/master/include/mimalloc-atomic.h#L7

I think we can eliminate it because first it works only on Windows and second there is no reason to use it because we already have header guards:
```cpp
#ifndef __MIMALLOC_X_H
#define __MIMALLOC_X_H
```

**Comment by Evrey** [comment]
Pragma once works on MSVC, GCC, Clang, and a bunch of other compilers, for many many years, on any OS, without having to add any special compiler flags. If anything, I'd argue that `#ifndef` guards can be thrown out of the window. `#pragma once` is much cleaner.

**Comment by Gymmasssorla** [comment]
Ok, I'll add the pull request which eliminates `#ifndef` guards.

**Comment by santagada** [comment]
No, #pragma once doesn't work when you can't know the path to a file (like compilation distribution) or precompiled headers. Please don't remove those.

**Comment by santagada** [comment]
I don't know why both ifdefs guards and pragma once are being used, but maybe wait for the author to comment... also I wouldn't bother with it.

**Comment by solvingj** [comment]
It's actually not terribly uncommon to use both even though they are redundant. I believe I've even seen it mentioned in a best practice guide somewhere.

**Comment by daanx** [comment]
Thanks for the suggestion; yes, they are there to ensure it compiles well on all platforms and the redundancy does not hurt (except from a beauty perspective). Seems worth the tradeoff.

**Comment by elfring** [comment]
How do you think about to [increase standard compliance also for this implementation detail](https://stackoverflow.com/questions/1695807/why-isnt-c-cs-pragma-once-an-iso-standard "Why isn't C/C++'s “#pragma once” an ISO standard?") by deleting the extra preprocessor directive from the source files?
