### ISSUE TITLE
Understanding not all freed!

### ISSUE THREAD

**Issue by erling-d-andersen** [microsoft/mimalloc#401]
We are trying mimalloc and is exciting about it. Thanks for your work.

I see

 not all freed!

in the committed row of the stats summary. We are very careful about freeing everything. 
And valgrind shows no leaks. So what does that not all freed! means.
There does not seem to be much explanation about the stats anywhere.

Using version 1.7.1

<pre>
heap stats:     peak      total      freed    current       unit      count
  reserved:   256.0 mb   256.0 mb   256.0 mb       0 b        1 b              ok
 committed:     9.0 mb     9.0 mb       0 b      9.0 mb       1 b              not all freed!
     reset:       0 b        0 b        0 b        0 b        1 b              ok
   touched:       0 b        0 b      1.0 mb    -1.0 mb       1 b              ok
  segments:       3          3          3          0                           ok
-abandoned:       0          0          0          0                           ok
   -cached:       0          0          0          0                           ok
     pages:      19         19         19          0                           ok
-abandoned:       0          0          0          0                           ok
 -extended:       0
 -noretire:       0
     mmaps:       0
   commits:      20
   threads:       0          0          0          0                           ok
  searches:     0.0 avg
numa nodes:       2
   elapsed:       0.002 s
   process: user: 0.002 s, system: 0.005 s, faults: 0, rss: 6.4 mb, commit: 9.0 mb
</pre>

**Comment by daanx** [comment]
Ah I can see this is confusing; It means that mimalloc still kept 9MiB of OS memory committed (mmap'd or VirtualAlloc'd). That is fine and it happens for performance reasons since decommit/commit is expensive. So, no worries for this.
You might be able to get mimalloc to decommit it if you call `mi_collect(true)` at the end of the program (but not always if things still get deallocated in atexit routines...)

**Comment by erling-d-andersen** [comment]
That make sense. Thanks.
