### ISSUE TITLE
mimalloc-redirect: error: "unable to find taget moudle"

### ISSUE THREAD

**Issue by nneesshh** [microsoft/mimalloc#404]
mimalloc-redirect: warning: stander malloc is _not_ redirected! -- using regulare malloc/free

what does this mean? I use vs2017 and build my project on window10

**Comment by nneesshh** [comment]
any idea is appreciated, many thanks

**Comment by daanx** [comment]
It does mean that mimalloc is not redirected  and the standard allocator is used. You need to run with MIMALLOC_VERBOSE=3  in the environment and send the output at startup -- that will probably show more clearly what is happening. Make sure to copy&paste the exact output. Thanks
