### ISSUE TITLE
Undefined reference to mi_malloc, mi_free on Windows 10 Cygwin

### ISSUE THREAD

**Issue by alpha-shrehan** [microsoft/mimalloc#407]
Hello, greetings to fellow developers. I recently came across mimalloc and though of using it in my C project. So I cloned the repository and went into it, created a folder out with subfolder release (just like the readme file told me), in that I compiled mimalloc and got few files. This process did not return an error. Here's my directory structure:
C:\Users\USER\Desktop\Github Sources -> This is where I cloned the reposiroty (doing so created a mimalloc folder in it)
C:\Users\USER\Desktop\Github Sources\mimalloc\out\release:
CMakefiles/
test/ -> Directory I created
cmake_install.cmake
CMakeCache.txt
CTestTestfile.cmake
libmimalloc.dll
libmimalloc.dll.a
libmimalloc-static.a
Makefile
mimalloc-redirect.dll
mimalloc-test-api.exe
mimalloc-test-stress.exe

The test folder has a file test.c, the contents of which are:
#include <stdio.h>
#include <assert.h>
#include <mimalloc.h>

int main() {
        int *test_ptr = (int *) mi_malloc(10);
        for (int i = 0; i < 10; i++)
                test_ptr[i] = i;
        for (int i = 0; i < 10; i++)
                printf("%i, ", test_ptr[i]);
        mi_free(test_ptr);
        return 0;
}

I compiled this using the following command:
gcc -o test/test -L "C:\Users\USER\Desktop\Github Sources\mimalloc\out\release" -lmimalloc -I C:\Users\USER\Desktop\Github Sources\mimalloc\include" test/test.c

But this gives an error:
C:\cygwin64\tmp\ccQisqZT.o:test.c:(.text+0x13): undefined reference to `mi_malloc'
C:\cygwin64\tmp\ccQisqZT.o:test.c:(.text+0x86): undefined reference to `mi_free'
collect2.exe: error: ld returned 1 exit status

Could anyone help me out?
I'm using cygwin and Windows 10 (no I am not using Visual Studio)

**Comment by daanx** [comment]
Thanks for the report -- unfortunately `mimalloc` is not supported for cygwin :-(   It is recommended to use visual studio, clang-cl, (or WSL2).  

ps. Supporting cygwin is on my wishlist but I am time constrained; it is tricky as I am not sure how to override malloc/free in that environment;

**Comment by alpha-shrehan** [comment]
Ohk, I see. Thank you soo much for answering my query.
