### ISSUE TITLE
Mimalloc Alignment

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#432]
What is the default alignment for memory allocated by mimalloc? and is it configurable?

For windows I would want to set the alignment to 16 bytes as that makes all fields align to be read by sse instructions.

**Comment by daanx** [comment]
Well, I guess this answer is a bit late (apologies!), but, yes, mimalloc always aligns to at least 16 bytes (set as `MI_MAX_ALIGN_SIZE` in `mimalloc-types.h`), so it is safe for SSE2 instructions.

**Comment by santagada** [comment]
Well, mine also very late response: Thank you! 👍

**Comment by santagada** [comment]
ok I got curious, why is it called MI_MAX_ALIGN_SIZE instead of MI_MIN_ALIGN_SIZE or something like MI_QUANTUM_SIZE? Even the comment on mimalloc-types mentions minimal alignment.
