### ISSUE TITLE
Crash on iOS

### ISSUE THREAD

**Issue by gaxlin** [microsoft/mimalloc#438]
log is:
seems that this is an infinite loop for malloc...

Jul  7 15:32:32 iPhone ReportCrash[17738] <Error>: Thread 0 name:  Dispatch queue: com.apple.main-thread
	Thread 0 Crashed:
	0   dyld                          	0x00000001200bf1bc 0x1200a8000 + 94652
	1   dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	2   dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	3   dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	4   libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	5   libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	6   libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	7   libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	8   libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	9   libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	10  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	11  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	12  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	13  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	14  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	15  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	16  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	17  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	18  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	19  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	20  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	21  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	22  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	23  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	24  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	25  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	26  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	27  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	28  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	29  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	30  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	31  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	32  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	33  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	34  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	35  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	36  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	37  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	38  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	39  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	40  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	41  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	42  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	43  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	44  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	45  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	46  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	47  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	48  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	49  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	50  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	51  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	52  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008

	53  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	54  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	55  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	56  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	57  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	58  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	59  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	60  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	61  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	62  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	63  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	64  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	65  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	66  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	67  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	68  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	69  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	70  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	71  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	72  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	73  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	74  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	75  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	76  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	77  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	78  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	79  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	80  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	81  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	82  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	83  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	84  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	85  libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	86  libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	87  dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	88  dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	89  dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	90  dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	91  dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	92  dyld                          	0x00000001200c0750 0x1200a8000 + 100176
	93  dyld                          	0x00000001200abf64 0x1200a8000 + 16228
	94  libdyld.dylib                 	0x00000001809f4ba0 0x1809f4000 + 2976
	95  libmimalloc.1.7.dylib         	0x00000001019ce030 0x1019b8000 + 90160
	96  libmimalloc.1.7.dylib         	0x00000001019cc15c 0x1019b8000 + 82268
	97  libmimalloc.1.7.dylib         	0x00000001019c89a8 0x1019b8000 + 68008
	98  libmimalloc.1.7.dylib         	0x00000001019c92dc 0x1019b8000 + 70364
	99  libmimalloc.1.7.dylib         	0x00000001019c8678 0x1019b8000 + 67192
	100 libsystem_malloc.dylib        	0x0000000180b3d458 0x180b3c000 + 5208
	101 libsystem_malloc.dylib        	0x0000000180b419dc 0x180b3c000 + 23004
	102 dyld                          	0x00000001200c7860 0x1200a8000 + 129120
	103 dyld                          	0x00000001200a9548 0x1200a8000 + 5448
	104 dyld                          	0x00000001200bc0a0 0x1200a8000 + 82080
	105 dyld                          	0x00000001200bf368 0x1200a8000 + 95080
	106 dyld                          	0x00000001200bf480 0x1200a8000 + 95360
	107 dyld                          	0x0000000120

**Comment by daanx** [comment]
Ah, there is not enough information to address this; However, version v1.7.3 and v2.0.3 have much improved macOS support so please try that.
