### ISSUE TITLE
compile with gcc 4.8 or gcc 7 fail

### ISSUE THREAD

**Issue by Richard-Feng** [microsoft/mimalloc#443]
I try to build mimalloc as you mentioned, but it came out with such errors:
![err1](https://user-images.githubusercontent.com/11372816/125728750-218f8bc6-3bb0-42f0-a831-67155faa5d65.png)

then, I try to upgrade my gcc from 4.8.2 to 7.5.0, but the problem still exists. so I have another try, that copy a stdatomic.h into directory /usr/inlcude, however there are even stranger problems：

![err2](https://user-images.githubusercontent.com/11372816/125728773-c43a16d6-e989-4283-94ef-ede6fb6faa29.png)

would you give me some suggestions？

**Comment by daanx** [comment]
I guess this cannot really be addressed by Mimalloc so I am going to close this issue for now.
(also, note that we recently added the `-DMI_USE_LIBATOMIC=ON` flag that one can pass to cmake tow link with `libatomic`)
