### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by gaxlin** [microsoft/mimalloc#444]
A/libc: Invalid address 0x7752c70d00 passed to free: value not allocated
![image](https://user-images.githubusercontent.com/1112308/125943399-8d6b1c74-2e7d-4b82-bb40-0614edc20963.png)

**Comment by daanx** [comment]
Apologies for the late reply. This issue does not have enough information to say what is going on. (is this combined with jemalloc as I see `je_free`? ).

**Comment by daanx** [comment]
I am going to close this for now.
