### ISSUE TITLE
How do I override maloc on Windows?

### ISSUE THREAD

**Issue by empleat** [microsoft/mimalloc#446]
Hey, 

I read instructions, but they are too brief! I Am not a programmer. I Am gonna need more specific instructions. Please how do I override standard maloc with mi-malloc in Windows? I tried to google this, but I didn't find anything, so...

Thanks for understanding...

**Comment by DerVogel2020** [comment]
checkout the source code and have a look into docs/using.html and docs/overrides.html

**Comment by empleat** [comment]
I read that already, but I Am not a programmer. I don't understand this for example: "The overriding on Windows requires that you link your program explicitly with the mimalloc DLL and use the C-runtime library as a DLL (using the /MD or /MDd switch).". 

How do I link program with mi-malloc and how do I use /MD switch? It is way too abstract. I built mi-malloc in visual studio, but I have no idea how to override an application. Can you help me please?

**Comment by jasongibson** [comment]
Hi @empleat, the mimalloc library is a low-level piece of code that provides features above what the system allocator provides.  The malloc() in the system allocator is good enough for the majority of software, and you don't need mimalloc to use malloc() - it already exists.

Could you describe what you're trying to accomplish?  What's the task you have?

**Comment by empleat** [comment]
I want it for gaming, later who knows... It is much better. I experimented with different mallocs in Arma 3 and it affects fps and input lag! Mi-malloc has much better peformance. Instead of telling me why I don't need it, could you rather simply tell me how to install it? It doesn't complicated, I just don't know how to link program with mimalloc DLL and use the C-runtime library as DLL, also (where do I use some /MD switch?).

**Comment by jasongibson** [comment]
I was not trying to imply that I know better than you, but rather learn what you intended to do with it so I could answer better.  You said you weren't a programmer, and malloc overrides are almost entirely a task programmers do, so I had to ask - sometimes people ask one thing and need another.

Your use-case is a good one, but is likely difficult to do generally.  Performance-oriented games often times have their own allocators, tuned for their own needs, and mixing allocators in a program is a sure-fire way to crash randomly.

Do you have the source code to the game you want to use, and a way to build it?  Overriding on Windows is usually not so easy as it is on Linux - the only documented way is to build the software (and follow the directions linked above).  There's probably some way to edit the binary and fiddle around with things that way, but that's way more involved than can be described here.

**Comment by empleat** [comment]
I heard people doing that for Battlefield for example. If it crashes then I won't use it. I Am sure how you  know that it is difficult to do generally, if you don't know how to override it. Tutorial is short, it doesn't seem that difficult, I just don't know what these 2 steps mean...

**Comment by cs8425** [comment]
I'm a programmer, but not good at Windows programming.
The docs said:
> (Note: in principle, it is possible to even patch existing executables without any recompilation
> if they are linked with the dynamic C runtime (`ucrtbase.dll`) -- just put the `mimalloc-override.dll`
> into the import table (and put `mimalloc-redirect.dll` in the same folder)
> Such patching can be done for example with [CFF Explorer](https://ntcore.com/?page_id=388)).

If I understand correctly, a program not linked with the dynamic C runtime and you don't have source/don't want to recompile (most of the existing program are this type), then there are no easy way to replace allocator.
If there are some easier way to replace allocator without recompile on Windows, please told me,
I would like to try replace allocator in chrome & electron(without recompile) on Windows...

**Comment by variar** [comment]
From the docs it looks like one should open a game executable file using CFF Explorer. Then go to imports section and manually add an entry for mimalloc-override.dll to the top of the list. After that placing mimalloc-redirect.dll and mimalloc-override.dll near the game executable should do the trick. All these is purely theoretical, so I would make a backup copy of game executable before applying any changes.

**Comment by daanx** [comment]
Thanks all for the feedback;  Unfortunately, at this time, on most platforms it is not easy to replace the standard allocator. Replacing it in existing programs can be tricky. On Windows this can work _if_ the C runtime library was linked dynamically. You can see this by opening the executable with CFF explorer and see if `ucrtbase.dll` is in the DLL imports. If so, you can add an import entry at the top for `mimalloc-redirect.dll` (and I think `mimalloc-override.dll`) as described by @variar (and add `mimalloc-redirect.dll` and `mimalloc-override.dll to the executable folder) and this may well work and sometimes speed up things. Nevertheless, no guarantees.
 
I am going to close this issue as it is too esoteric :-)
