### ISSUE TITLE
Support a mi_stats_print interface similar to jemalloc

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#45]
Passing a FILE* to mi_stats_print is very difficult from non console applications. je_malloc has a very simple interface to pass a function that receives a pointer to a buffer and that seems much better for all the cases were writing to a file is complicated. It could by default have a function that writes to stderr for simplicity.

**Comment by daanx** [comment]
Ah, I see, I like this. A bit tricky as I am using all the printf functions to format the output.

**Comment by daanx** [comment]
Hi, I recently added a new interface to redirect output by allowing to pass in an explicit callback. That should at least make it easier to integrate into a UI or something. 
```
typedef void (mi_output_fun)(const char* msg);
void mi_register_output(mi_output_fun* out);  // for verbose messages etc.
void mi_stats_print(mi_output_fun* out);
```

**Comment by santagada** [comment]
This should be enough to close this issue
