### ISSUE TITLE
Build fails. Problem with spaces in the compiler path.

### ISSUE THREAD

**Issue by brmmm3** [microsoft/mimalloc#451]
I'm using latest versions of Rust and mimalloc. Seems to be a problem with spaces in the compiler path.

     Running `D:\Workspace\Rust\a2l-rs\target\release\build\libmimalloc-sys-18e3e26370e69c0c\build-script-build`
error: failed to run custom build command for `libmimalloc-sys v0.1.22`

Caused by:
  process didn't exit successfully: `D:\Workspace\Rust\a2l-rs\target\release\build\libmimalloc-sys-18e3e26370e69c0c\build-script-build` (exit code: 1)
  --- stdout
  OPT_LEVEL = Some("3")
  TARGET = Some("x86_64-pc-windows-msvc")
  HOST = Some("x86_64-pc-windows-msvc")
  CC_x86_64-pc-windows-msvc = None
  CC_x86_64_pc_windows_msvc = None
  HOST_CC = None
  CC = Some("\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\bin\\amd64\\cl.exe\"")
  CFLAGS_x86_64-pc-windows-msvc = None
  CFLAGS_x86_64_pc_windows_msvc = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "\"C:\\Program" "Files" "(x86)\\Microsoft" "Visual" "Studio" "14.0\\VC\\bin\\amd64\\cl.exe\"" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-DMI_DEBUG=0" "-FoD:\\Workspace\\Rust\\a2l-rs\\target\\x86_64-pc-windows-msvc\\release\\build\\libmimalloc-sys-4bb11a23275d7b2a\\out\\c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c"

  --- stderr

  error occurred: Command "\"C:\\Program" "Files" "(x86)\\Microsoft" "Visual" "Studio" "14.0\\VC\\bin\\amd64\\cl.exe\"" "-O3" "-ffunction-sections" "-fdata-sections" "-m64" "-I" "c_src/mimalloc/include" "-I" "c_src/mimalloc/src" "-Wall" "-Wextra" "-DMI_DEBUG=0" "-FoD:\\Workspace\\Rust\\a2l-rs\\target\\x86_64-pc-windows-msvc\\release\\build\\libmimalloc-sys-4bb11a23275d7b2a\\out\\c_src/mimalloc/src/static.o" "-c" "c_src/mimalloc/src/static.c" with args "Program" failed to start.

warning: build failed, waiting for other jobs to finish...
error: build failed
error: cargo failed with code: 101

**Comment by daanx** [comment]
Hi @brmmm3, thanks for the report !  However, it seems that this is not a mimalloc issue, but a bug in the build (cargo) script in Rust for mimalloc -- it looks like it compiles "static.c" which is an easy way to compile all of mimalloc in a single file. I guess you could try to add some quotes around the CC command in the build script?  Good luck
