### ISSUE TITLE
Confusion about cross-platform static library usage (vcpkg+cmake).

### ISSUE THREAD

**Issue by angelfor3v3r** [microsoft/mimalloc#453]
Hi! I've been wanting to use this library in one of my C++ CMake projects across Linux/Windows and I'm a bit confused by the docs and example test projects.

What would be the best way to use this library as a global `malloc` override across Linux/Windows?

The part I'm confused by is the `"mimalloc-override.h"` and `"mimalloc-new-delete.h"` usage. On the docs it says you can use the `mimalloc-new-delete.h` header on Linux/Windows for the "best performance" but then in the test cases (specifically: [here](https://github.com/microsoft/mimalloc/blob/e2c095fad2a1d506712be0b22616f97cc927c05b/test/CMakeLists.txt#L34-L37) & [here](https://github.com/microsoft/mimalloc/blob/e2c095fad2a1d506712be0b22616f97cc927c05b/test/main-override.cpp#L18)) it only includes the operator overrides on Windows.

I would like to do a global override of malloc/free & use the operator overloads since I assume this would be the best way to use it based on what the documentation is telling me.

Currently my CMake project layout is this:
```
find_package(mimalloc 1.6.4 CONFIG REQUIRED)
target_link_libraries(${PROJECT_NAME} PRIVATE mimalloc-static)
```

And in a single source-file I'm doing this (before all other includes):
```
#include "stdlib.h"
#include "mimalloc-override.h"
#include "mimalloc-new-delete.h"
```

However, on Windows this produces an error:
```
C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0\ucrt\string.h(148,1): error C2382: 'mi_strdup': redefinition; different exception specifications
C:\asm\backend\build\vcpkg_installed\x64-windows-static\share\mimalloc\..\..\include\mimalloc.h(109): message : see declaration of 'mi_strdup'
```

And the errors stem from here:
```
// string.h
_Check_return_
_ACRTIMP _CRTALLOCATOR char* __cdecl _strdup(
    _In_opt_z_ char const* _Source
    );

// mimalloc
mi_decl_nodiscard mi_decl_export mi_decl_restrict char* mi_strdup(const char* s) mi_attr_noexcept mi_attr_malloc;

#define _strdup(s)              mi_strdup(s)
```

Any help on this would be really appreciated, thank you :)

**Comment by angelfor3v3r** [comment]
Update:
If this is not the preferred way then I believe I'm going to try the Dynamic way. But sadly my testing can't be completed until Vcpkg fixes some of the ports I need.

**Comment by RT222** [comment]
I have the same issue, when I try to use static overriding on Windows by linking statically to mimalloc and including "mimalloc-override.h" in every source file, I get the same compilation error. I know that dynamic overriding is the recommended way to do it, and it works fine, but according to the documentation static overriding should also be possible on all platforms, so maybe this should be fixed or the documentation should be edited.
