### ISSUE TITLE
Use monotonic rather than realtime clock ticks

### ISSUE THREAD

**Issue by todd-richmond** [microsoft/mimalloc#457]
in stats.c, CLOCK_REALTIME is susceptible to clock changes and slower than a course clock. CLOCK_MONOTONIC_COARSE will have better perf and be continuously accurate. Ifndef CLOCK_MONOTONIC_COARSE or you need better than msec resolution, then use CLOCK_MONOTONIC

**Comment by daanx** [comment]
Thanks for the suggestion; I added support for CLOCK_MONOTONIC; I didn't add the coarse version as we make almost no calls to timers so the posix version is good enough for us :-)
