### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [microsoft/mimalloc#46]
I would like to point out that an identifier like “[`__MIMALLOC_H`](https://github.com/microsoft/mimalloc/blob/464efa80b06f51c994f6e6e092f4231460328275/include/mimalloc.h#L8 "Update candidate")” [does eventually not fit](https://wiki.sei.cmu.edu/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28IncludeGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by daanx** [comment]
Ah, I see. We should fix this in the guards by removing the underscore prefixes on the include guards.
