### ISSUE TITLE
'reserved' and 'committed' stats don't appear to match their descriptions

### ISSUE THREAD

**Issue by jritts** [microsoft/mimalloc#47]
Thank you for making this library available! I'm enjoying playing around with it.

In Windows, the flags MEM_COMMIT and MEM_RESERVE are passed together to VirtualAlloc, yet the 'committed' heap stat does not equal 'reserved'.  It seems like the library's intention is for those stats to have the equivalent API semantics of 'backed by physical' vs 'reserved virtual address space'.

The same bug appears to apply to the other platforms, though I'm not as familiar with mmap and could be wrong.

**Comment by daanx** [comment]
Ah, the stats indeed have nothing to do with Windows reserved and committed. The committed statistic is about memory that is touched by the allocator (and thus the underlying OS pages) while reserved says how much memory is allocated from the OS (but perhaps just virtually until it is touched like on Windows or Linux).  Does that make sense?

**Comment by jritts** [comment]
Ah, it was my misunderstanding - thank you for taking the time to respond.  Closing the issue...
