### ISSUE TITLE
`printf` family format-type mismatches triggering CodeQL

### ISSUE THREAD

**Issue by Th3T3chn0G1t** [microsoft/mimalloc#486]
(I acknowledge this probably isn't too big a concern on your part, but it would make submoduling mimalloc a lot more convenient with regards to Github static analysis and automerge checks).

There are a few places in mimalloc which trigger security vulnerability warnings under GH CodeQL, all to do with format function parameters. This means that a repository which submodules mimalloc must have their failing security check for PRs be set to greater than high (since that is the severity of format type mismatches according to CodeQL).

The following locations report type mismatch:

|File|Line|Specified Type|Provided Type|
|---|---|---|---|
|`mimalloc/src/stats.c`|326|`int`|`unsigned long`|
|`mimalloc/src/os.c`|756|`unsigned int`|`unsigned long`|
|`mimalloc/src/os.c`|831|`unsigned int`|`unsigned long`|
|`mimalloc/src/os.c`|890|`unsigned int`|`unsigned long`|
|`mimalloc/src/alloc.c`|468|`char*`|`void*`|

Also a medium severity format issue: `"Format expects 2 arguments but given 1"` at `mimalloc/src/alloc.c:468`

If this could be fixed it would be nice but I understand that it may not be in your interests, and that the issue could also be on CodeQL's side.

Thanks!

**Comment by daanx** [comment]
Thanks so much! 

> If this could be fixed it would be nice but I understand that it may not be in your interests, and that the issue could also be on CodeQL's side.

These kind of issues are very important to be addressed! thanks so much for reporting this :-).  The medium severity issue was already fixed in #c21b6df5 and I just pushed fixes for the rest to `dev` and `dev-slice`. I hope to do a minor release at the end next week which would include these fixes.
 
Best,
  Daan

**Comment by Th3T3chn0G1t** [comment]
Awesome - thanks!
