### ISSUE TITLE
typo in mi_tls_slot_set?

### ISSUE THREAD

**Issue by IHateGFW** [microsoft/mimalloc#488]
I'm learning tls in mimalloc,it looks like a typo in mi_tls_slot_set() :
__asm__("movl %1,%%fs:%1" : "=m" (*((void**)ofs)) : "rn" (value) : );  // x32 ABI
__asm__("movq %1,%%fs:%1" : "=m" (*((void**)ofs)) : "rn" (value) : );  // x86_64 Linux, BSD uses FS

looks like it should be
__asm__("movl %1,%%fs:%0" : "=m" (*((void**)ofs)) : "rn" (value) : );  // x32 ABI
 __asm__("movq %1,%%fs:%0" : "=m" (*((void**)ofs)) : "rn" (value) : );  // x86_64 Linux, BSD uses FS

**Comment by daanx** [comment]
Yikes -- you are right; thanks so much!  Fortunately for us, the setting of slots is only used on macOS and thus that code is never executed on either x32 or Linux etc. :-)
