### ISSUE TITLE
mimalloc: set SOVERSION for mimalloc shared lib (required for proper unix builds)

### ISSUE THREAD

**Issue by viy2** [microsoft/mimalloc#490]
Those are commented pieces of the proposed patch (proper patch will be added below):
in CMakeLists.txt
1) add SOVERSION ${mi_version_major}

2) remove your hack with symlinks:
-if(NOT WIN32 AND MI_BUILD_SHARED AND NOT MI_INSTALL_TOPLEVEL)
...
endif()

first, it does thing wrong on unix, and, second, when we set SOVERSION, cmake will do it for us, and will do it properly.

3) it is optional, but it would be nice to show .so.version as real version 2.0.3, not 2.0
for this, in cmake/mimalloc-config-version.cmake
-set(mi_version ${mi_version_major}.${mi_version_minor})
+set(mi_version_patch 3)
+set(mi_version ${mi_version_major}.${mi_version_minor}.${mi_version_patch})

**Comment by viy2** [comment]
[mimalloc-2.0.3-soversion.patch.zip](https://github.com/microsoft/mimalloc/files/7613348/mimalloc-2.0.3-soversion.patch.zip)

complete proposed patch file

**Comment by devnexen** [comment]
better would be a proposed PR ;-)

**Comment by viy2** [comment]
> better would be a proposed PR ;-)
hm, sorry, can't decipher what PR is. Maybe FR=Feature Request? 

but what this patch is in essence, it is just to add 2 words "SOVERSION ${mi_version_major}"  after set_target_properties(mimalloc PROPERTIES VERSION ${mi_version} ... in CMakeLists.txt

too few changes and this is just a standard practice for cross-platform libraries.

**Comment by devnexen** [comment]
I meant Pull Request. Because you re right it s better to let cmake doing this and you would be listed as contributor.

**Comment by viy2** [comment]
Sorry to trouble you, it is my first attempt, and I seem to mess it. 
I created a clone repo, and pushed 2 commits there:
https://github.com/viy2/mimalloc/commit/29e5a0d02355ec5604c6ad58b6431f47dc839d0d
https://github.com/viy2/mimalloc/commit/1b5025e05ca3311e7170a479e563f013e81b6682
but I can't made them into a pull request :(

**Comment by devnexen** [comment]
it would be more convenient if you created your PR from the `dev` branch.

**Comment by viy2** [comment]
Created 2 commits in pull_request_on_dev
first  acc64ee5cd58277490a89d4c4f97e3f3839beff5 is just a cherry pick of 29e5a0d
second f82e13ac91716ff60d4e656e1f825ce727b7fd7d is 1b5025e adapted to dev version 1.7.3

**Comment by devnexen** [comment]
you ought to be able to create a pull request from this branch.

**Comment by viy2** [comment]
Unfortunately, no. It seems I messed up and Github does not register my repo as a fork or something. My repo is not in a list of forks :(

**Comment by MarcusJohnson91** [comment]
> Unfortunately, no. It seems I messed up and Github does not register my repo as a fork or something. My repo is not in a list of forks :(

At the top of the page, on the right hand side where it says the number of foks, click the fork button, github will then create a copy of the repo for you.

**Comment by viy2** [comment]
Thanks! Sorry for all the trouble, I's my first time with github's pull requests.

**Comment by MarcusJohnson91** [comment]
> Thanks! Sorry for all the trouble, I's my first time with github's pull requests.

We all gotta start somewhere, glad to help. :)
