### ISSUE TITLE
build for android failed due to unable to find library -lpthread

### ISSUE THREAD

**Issue by leleliu008** [microsoft/mimalloc#496]
I suggest [CMakeLists.txt#L216-L217](https://github.com/microsoft/mimalloc/blob/master/CMakeLists.txt#L216-L217)
```
if(NOT ${CMAKE_C_COMPILER} MATCHES "android")
    list(APPEND mi_libraries pthread)
    ...
endif()
```
change to following:
```
find_library(LIBPTHREAD pthread)
if (LIBPTHREAD)                      
    list(APPEND mi_libraries pthread)
endif()
```

```
if(NOT ${CMAKE_C_COMPILER} MATCHES "android")
```
this check not always as expected. here is a [example](https://github.com/leleliu008/ndk-pkg-formula-repository/runs/4496432025?check_suite_focus=true)

**Comment by daanx** [comment]
Thanks! Just fixed it in `dev`.
