### ISSUE TITLE
Sized deallocation API

### ISSUE THREAD

**Issue by gnzlbg** [microsoft/mimalloc#5]
There does not appear to be a sized-deallocation API (e.g. `free_(void*, size_t)`) where the user promises that the size passed is the size hint in range [requested_size, alloction_size] where allocation size is the maximum of `mi_good_size` and `mi_usable_size`.

**Comment by Lastique** [comment]
Also missing C++ sized deallocation, see `operator delete` taking `size_t` as the second argument [here](https://en.cppreference.com/w/cpp/memory/new/operator_delete).

**Comment by daanx** [comment]
Fixed in the latest dev branch
