### ISSUE TITLE
MI_DEBUG_UNINIT filling condition?

### ISSUE THREAD

**Issue by res2k** [microsoft/mimalloc#501]
Hi,
building in "debug" mode, I don't get blocks filled with `MI_DEBUG_UNINIT` with the "regular" (non-zeroing) alloc functions.

Looking at the code, filling of allocated blocks with `MI_DEBUG_UNINIT` only happens for `page->is_zero`.
This seems odd to me... if the page is zero I'd expect to get "filled" memory, unless I asked for zeroed memory...

But I'm not entirely sure whether this is an actual issue (poorly chosen condition) or whether I misunderstand the intention...
Can someone shed light on this?

**Comment by daanx** [comment]
Hi, I think the relevant code is:
```C
#if (MI_DEBUG>0)
  if (!page->is_zero) { memset(block, MI_DEBUG_UNINIT, size); }
```
So, it fills a block with `MI_DEBUG_INIT` when the page does not have the zero flag set. Doing it when the flag is set is wrong as that assumes the memory is zero-initialized and thus the zeroing allocation functions can skip zero initialization when possible. The `page->is_zero` flag is set for example when getting memory at first from the OS which always zero initializes memory.  

Now, we _could_ in debug mode always set the `page->is_zero` flag to `false` at initialization in which case all blocks in debug mode start out as uninitialized.However, that gives different code paths in the zero'ing allocation functions for release build so I am hesitant to do this.

**Comment by res2k** [comment]
> The `page->is_zero` flag is set for example when getting memory at first from the OS which always zero initializes memory.
This is most likely what happens here.

Hmm, my thinking would be: "in debug, always fill memory, unless the zero-initializing was explicitly requested".
Mainly I see this as a valuable tool - you can quickly spot uninitialized data/members in the debugger.
Returning zero-filled memory, otoh, may hide uninitialized data, since zero is often enough a "sensible" value.
(FWIW, the MSVC debugging `malloc()` behaves like that, possibly other allocators as well.)

I tend to agree that keeping the "already zero initialized" information in debug mode is sensible and forcing it to `false` feels dirty.

But I was wondering if maybe the following approach might work:
1. Pass an `bool zero_data` argument to `_mi_page_malloc`
2. Change logic to `if (!zero_data) memset(...)`
3. Result: filled with "sentinel" values unless zeroing was requested anyway

**Comment by daanx** [comment]
I pushed an initial fix to `dev` and `dev-slice` that ensures blocks are always first filled with MI_DEBUG_UNINIT. I think this will address your issues and seems generally good for debug mode.

**Comment by res2k** [comment]
Tests say it works :)
