### ISSUE TITLE
struct mi_heap_area_t "used" member documentation misleading

### ISSUE THREAD

**Issue by res2k** [microsoft/mimalloc#503]
The documentation of `mi_heap_area_t::used` says: "bytes in use by allocated blocks".
This suggest that the the value is a number of _bytes_.
Actually, though, it appears to be a number of _blocks_; to get a byte value you need to multiply by the block size.

So it seems that either the documentation is not quite correct, or there's a multiplication lacking.
(Though for compatibility reasons it would probably be wiser to adjust the documentation.)

**Comment by daanx** [comment]
Thanks for the PR :-)
