### ISSUE TITLE
All default heaps walk

### ISSUE THREAD

**Issue by santagada** [microsoft/mimalloc#52]
Is there any plans to have a way to walk all per thread default heaps? There seems that all stats and walk functions work either in the current thread heap or on a passed on heap and no way to access all heaps.

**Comment by daanx** [comment]
Yes, that was the plan, but we didn't do this for now as it is unclear what the best approach is: the only way to walk all heaps is to somehow stop all other threads from allocating/freeing in the heap that is being walked.. but we can't do that without a severe performance hit in the fast path. So, for now, the best way seems to allow the walking per thread only and have the application coordinate this among threads.
