### ISSUE TITLE
VS2017 compile fails with latest dev-slice df01e46 

### ISSUE THREAD

**Issue by jackL999** [microsoft/mimalloc#523]
line 616 of init.c,

`extern "C" _mi_crt_callback_t _mi_msvc_initu[] = { &_mi_process_init };`

causes 3 errors,
Error E0040	expected an identifier
Error E0069	integer conversion resulted in truncation
Error C2059	syntax error: 'string'

**Comment by daanx** [comment]
hmm, I changed `extern "C"` to `mi_decl_externc` -- can you try if this works now? 
(I think you are compiling as C and not C++).

**Comment by jackL999** [comment]
Yes that worked. Thanks. WRT compiling as C I am not sure how that is happening since I just opened mimalloc.sln from the ide\vs2017 folder and selected rebuild solution.
