### ISSUE TITLE
Comparison is always true because ret <= -1

### ISSUE THREAD

**Issue by thehans** [microsoft/mimalloc#524]
This logic error on line 223 was detected by LGTM.
https://github.com/microsoft/mimalloc/blob/38a03229c89afbf2722e48c63da696bf11589dee/src/random.c#L222-L223
I believe the intended code should be checking `errno` instead of `ret`

from [syscall manpage](https://man7.org/linux/man-pages/man2/syscall.2.html#:~:text=syscall()%20is%20a%20small,function%20in%20the%20C%20library.
):
> The return value is defined by the system call being invoked.  In general, a 0 return value indicates success.  A -1 return value indicates an error, and an error number is stored in errno.

**Comment by daanx** [comment]
Thanks so much! pushed a fix.
