### ISSUE TITLE
Comparison is always false because max_extend >= 1.

### ISSUE THREAD

**Issue by thehans** [microsoft/mimalloc#526]
Problem found by LGTM:
https://github.com/microsoft/mimalloc/blob/38a03229c89afbf2722e48c63da696bf11589dee/src/page.c#L583

`max_extend` is already guaranteed to be at least `MI_MIN_EXTEND` (defined to be `(1)`) in the line above:
https://github.com/microsoft/mimalloc/blob/38a03229c89afbf2722e48c63da696bf11589dee/src/page.c#L578

**Comment by daanx** [comment]
Thanks again :-)  I like the explicit check but to ensure LGTM is not complaining I removed the check but added further assertions (in case someone changes the code later on and violates the assumptions).
