### ISSUE TITLE
mi_heap_visit_blocks reports used memory in blocks instead of bytes 

### ISSUE THREAD

**Issue by romange** [microsoft/mimalloc#552]
According to [docs](https://microsoft.github.io/mimalloc/group__analysis.html#structmi__heap__area__t):
`mi_heap_area_t.used` shoud report number of used bytes and not blocks.

However, the following code demonstrates that it exposes the number of blocks.

```cpp
auto cb_visit = [](const mi_heap_t* heap, const mi_heap_area_t* area, void* block,
                     size_t block_size, void* arg) {
    assert(area->used == 64);  // fails because area->used = 1.
    return true;
  };

  auto* myheap = mi_heap_new();
  void* p1 = mi_heap_malloc(myheap, 64);
  mi_heap_visit_blocks(myheap, false /* do not visit all blocks*/, cb_visit, nullptr);
  mi_heap_destroy(myheap);
```

**Comment by res2k** [comment]
Unfortunately this would break existing code.
But since the block size is reported in `area->block_size`, you can multiply yourself...

**Comment by romange** [comment]
Of course i can. Besides this, we could add a new field 'used_bytes' and
fix the docs if backward compatibility is required.
