### ISSUE TITLE
Increased resident set size on Azure

### ISSUE THREAD

**Issue by birkmose** [microsoft/mimalloc#560]
Hi!

I am observing strange behavior when running an executable on Azure VMs (Linux O/S - Ubuntu 20.04LTS) using mimalloc as the allocator. Azure's resident set size is far greater with mimalloc. I also observe the same behavior when executing the same code inside Docker containers hosted on various Azure services - such as Azure container apps for instance. It does not make a difference if the VM is Intel or AMD based.
Simply executing a straightforward c program as below:

```c
#include <stdio.h>

int main() {
   char c = getchar();
   return 0;
}
``` 

Compiled using `gcc -lmimalloc  test.c` and executed using `LD_PRELOAD=./libmimalloc.so ./a.out`.

When checking the resident set size on Azure I get about 2MB penalty - this is both on Intel/AMD CPUs.

```sh
test@azure:~$ ps -ao pid,rss,comm | grep a.out
   4499  2636 a.out
```
On AWS (and various other cloud vendors), as well on bare metal I get a much small resident set size
```sh
ubuntu@ip-172-31-5-67:~$ ps -ao pid,rss,comm | grep a.out
   2097   600 a.out
```
This is of course a simple example - when executing a real program (multithreaded embedded webserver) - I see around 12MB higher RSS on Azure. (Same thread-count, idle, etc, so should be an apples-to-apples comparison).

Any thoughts on what could be causing this?
using `MIMALLOC_VERBOSE=1` I can see that the parameters are equivalent in both environments. Also to clarify it is the same physical binary+libmimalloc.so that I am using for tests in all environments.
Could it be some kind of extra hardening on the Azure VMs (spectre, etc) triggering this? It is strange though - if I do not use mimalloc (simply: `./a.out`) I do not observe this behavior on Azure then the RSS is 576KB.

**Comment by daanx** [comment]
Strange -- just to clarify: you are running the same program with the same Ubuntu 20.04 installation, and on bare metal and on an AWS VM you see a smaller RSS than on an Azure VM or Docker container?  

I wonder if it is related to "transparent huge pages" that are 2MiB on Linux?  Mimalloc tends to reserve 4MiB aligned large chunks and if these become huge pages there will be 2MiB increments when the memory is touched (vs 4KiB increments). Not sure how to check this though.

**Comment by birkmose** [comment]
It is not the same installation entirely - merely the ubuntu 20.04 64bit  flavor offered by the individual vendor (AWS, Azure, Equinix, etc) - so naturally, there are some differences in the kernel config. I tried doing diffs on their kernel config, but the diff it is rather large, and without knowing what to look for it is like looking for a needle in a haystack.

I tried to execute the test program with MIMALLOC_VERBOSE=1 - and the outputs are identical - so it seems to be external to what is possible to configure with mimalloc.

If I test it with programs with multiple threads - the RSS size becomes noticeable larger also.

**Comment by mjp41** [comment]
If you 
```sh
cat /sys/kernel/mm/transparent_hugepage/enabled
```
then you can find out the setting.  I have found that it can have big effects on memory in some scenarios.  In snmalloc, we have similarly large aligned blocks, and this can sometimes lead to larger RSS, when there are lots of threads with small footprints.  Typically, I don't see an issue with larger footprints though.

You can change the setting with:
```sh
echo always >/sys/kernel/mm/transparent_hugepage/enabled
echo madvise >/sys/kernel/mm/transparent_hugepage/enabled
echo never >/sys/kernel/mm/transparent_hugepage/enabled
```
https://www.kernel.org/doc/html/latest/admin-guide/mm/transhuge.html

**Comment by birkmose** [comment]
Yes - this was it :) It turns out on the Azure VMs transparent_hugepage=always.
If I turn it off for instance the resident set size goes down: 

```bash
#transparent_huge_page=always
test@mimalloctest:~$ ps -ao pid,rss,comm | grep a.out
   2090  2636 a.out

#transparent_huge_page=never
test@mimalloctest:~$ ps -ao pid,rss,comm | grep a.out
   2202   652 a.out

```
