### ISSUE TITLE
Outdated version in conan center

### ISSUE THREAD

**Issue by gleb-kov** [microsoft/mimalloc#567]
Currently, all available versions in conan center are:
mimalloc/2.0.3
mimalloc/2.0.2
mimalloc/1.6.7

but 1.7.* is stable right now. Could you please bump the version?

**Comment by daanx** [comment]
ah, I did not even know there was a Conan package :-) Someone else is maintaining this (thanks!! that is great) -- perhaps you can find who that is in the Conan package description?

**Comment by gleb-kov** [comment]
Seems like contribution here https://github.com/conan-io/conan-center-index/commits/master/recipes/mimalloc will add a new configuration to conan center. I will try to add the 1.7.* version, hopefully it won't require many non-trivial changes in conanfile.py

**Comment by daanx** [comment]
Great! thanks so much :-)
