### ISSUE TITLE
Iteration on multiple vectors doesn't scale linearly

### ISSUE THREAD

**Issue by RT222** [microsoft/mimalloc#568]
Hello,

I'm working on an archetype based Entity Component System that I'm trying to make it as fast as possible. It is thoroughly benchmarked, and I wanted to see the impact mimalloc could have on the results. I was very impressed, the gains were huge and some operations are almost twice as fast as the default system allocator, this is definitively something I want for my project.

But for now I have to refrain to use it globally because I observed a very peculiar side effect on components iteration performance. In the following benchmarks, we simply iterate simultaneously on every component arrays and mesure the total time it took. As it should be on any decent ECS, the components are stored in contiguous arrays (std::vector in this case) to maximize spatial locality, the iteration is done by using the default container iterator. I'm using mimalloc 2.0.5, and the benchmarks are built with Visual Studio 17.1.2 on x64/Release mode. These results were obtained with catch2 benchmark using the --benchmark-no-analysis command line option to get a clean output :

With the default MSVC allocator :
```
benchmark name                            samples    iterations          mean
-------------------------------------------------------------------------------
1 component array iteration                 100             8    3.37712 us
2 component array iteration                 100             5     4.6392 us
3 component array iteration                 100             4     6.9585 us
4 component array iteration                 100             3    9.27033 us
5 component array iteration                 100             2     11.579 us
6 component array iteration                 100             2     14.081 us
7 component array iteration                 100             2     16.409 us
8 component array iteration                 100             2    18.6235 us
9 component array iteration                 100             2    20.8395 us
10 component array iteration                100             1     23.317 us
11 component array iteration                100             1     25.554 us
12 component array iteration                100             1     28.075 us
```

As you can see, with the default allocator, the time required to iterate on all component arrays scales linearly as expected.

With mimalloc :
```
benchmark name                            samples    iterations          mean
-------------------------------------------------------------------------------
1 component array iteration                 100             7      3.188 us
2 component array iteration                 100             5     5.3416 us
3 component array iteration                 100             4    7.45225 us
4 component array iteration                 100             3    10.4077 us
5 component array iteration                 100             2    13.0595 us
6 component array iteration                 100             2    15.8915 us
7 component array iteration                 100             2     18.363 us
8 component array iteration                 100             1      23.36 us
9 component array iteration                 100             1    162.141 us <--- What's happening here?
10 component array iteration                100             1    305.872 us
11 component array iteration                100             1    509.367 us
12 component array iteration                100             1    718.878 us
```

Doing the same tests with mimalloc, I still get good results when iterating on 8 component arrays or less, however each additional component array beyond that slows down the iteration loop drastically.

I ran the same benchmarks with varying components count and size, and my conclusion is that there's either a massive slowdown or none at all, and it's only happening with 9 component arrays or more. Given a component size, there's a very specific component count to reach to trigger it on my machine :

| Components size | Required count to trigger the issue | Component arrays size (bytes) |
| :---: | :---: | :---: |
| int8_t | 10202 | 10202 |
| int16_t | 7149 | 14298 |
| int32_t | 897 | 3588 |
| int64_t | 892 | 7136 |

I'm really puzzled by these results. I thought there would be a kind of memory threshold to reach to trigger the slowdown, and that it would then be logical that it requires more components for it to happen on smaller components size. But when we compare the component arrays size, they seems to vary without any logic. And why does this issue never ever happens if we're looping on 8 component arrays or less, even with huge components count (1000000 components of int64_t type for example)? 

I also tried to play with the different mimalloc options but none of them had any mesurable impact on the results.

I hope that this is a pertinent issue and that I'm not wasting your time here. I extracted the relevant code from my ECS library and simplified it so that you can test it on your end :
https://gist.github.com/RT222/b98d33514eca8fe3a4af82adec220f73

**Comment by daanx** [comment]
Thanks for the test program -- I could reproduce this on Ubuntu on an AMD5950x and it is indeed false cache line sharing what you are seeing. Mimalloc happens to allocate the arrays aligned to 4KiB (or more perhaps) and since the test iterates over all elements in the arrays in lockstep at some point the same cache lines are shared (as these distinguish on the lower bits of the address with at most 8 lanes for many cpu's).  I tested this by modifying your sample program by allocation EXTRA amount of entries (100) and starting the iterator for each array randomly at the `rand() % EXTRA` entry and the effect goes away and it scales linearly again.

Not sure how often a situation like this would occur in practice though.. but it would be nice to (try to) avoid it. I will ponder this a bit more and see if we can automatically mitigate this or perhaps by introducing a new call, like `mi_malloc_unaligned` or something. TBC.

**Comment by RT222** [comment]
Awesome, I'm really glad to have the explanation behind this mysterious problem. I may have to make some research to fully comprehend it, but now that I know what to look for, it will be far easier. I also think this isn't a very common case, in fact I never iterate on more than 3 components in practice, I only stumbled on this problem in the benchmarks. I think it's pretty safe for me to keep using mimalloc and I'm pretty happy about it given the huge speed boost it brings on the table.

A huge thank you for your prompt answer and for having taken the time to thoroughly review this issue.

**Comment by daanx** [comment]
Thanks :-)
>  I think it's pretty safe in my case to keep using mimalloc 
Yes, this kind of aliasing can happen anywhere and is hard to avoid in general.
