### ISSUE TITLE
mi_heap_visit_blocks won't visit blocks bigger than 2097152

### ISSUE THREAD

**Issue by MechSlayer** [microsoft/mimalloc#570]
When allocating blocks bigger than 2097152, `mi_heap_visit_blocks` won't visit them. Likely because `heap.page_count` won't increase when allocating more than that.

Example:
```c
#include <mimalloc.h>
bool test_visit(const mi_heap_t *heap, const mi_heap_area_t *area, void *block, size_t block_size, void *arg) {
    printf("I'm visiting a block of size %zu\n", block_size);
    return true;
}

int main() {
    mi_heap_t *heap = mi_heap_new();
    mi_heap_malloc(heap, 2097152);
    mi_heap_malloc(heap, 2097160);
    mi_heap_malloc(heap, 24576);
    mi_heap_visit_blocks(heap, false, &test_visit, NULL);
    return 0;
}
```

Expected result:
```
I'm visiting a block of size 24576
I'm visiting a block of size 2097152
I'm visiting a block of size 2097160
```
Actual result:
```
I'm visiting a block of size 24576
I'm visiting a block of size 2097152
```

**Comment by daanx** [comment]
Yes, this is not right :-( Unfortunately, there is no easy fix without impacting performance. I need a bit mo re time to figure out a good way to do this. TBC

**Comment by MechSlayer** [comment]
Sure, no problem. Is it always the same size on all platforms, or is there a way to check at which size will it stop visiting?

**Comment by epoupon** [comment]
@daanx have you thought about it? I guess it is complicated since the page is not registered in the heap itself (i.e. abandonned) and can be freed by any thread?
But does that also means that `mi_heap_destroy `won't delete them?

**Comment by daanx** [comment]
Hi @epoupon, indeed it is a bit tricky as such pages are treated as abandoned... that is good for the core allocator but not great for the heap walking (and indeed, `mi_heap_destroy` won't work for those -- didn't realize this yet). 

I want to do an interim release soon (this week) but I will look into this issue after that; it needs to be fixed.

**Comment by epoupon** [comment]
Thanks for your support! Will it be also fixed in the 1.x branch?

**Comment by daanx** [comment]
This is fixed now in the latest `dev`/`dev-slice` branches -- huge pages are now no longer abandoned but still eagerly decommitted if freed from other threads.
