### ISSUE TITLE
ATOMIC_VAR_INIT deprecation warnings when building with Clang 14

### ISSUE THREAD

**Issue by eklitzke** [microsoft/mimalloc#571]
I'm building mimalloc with `-std=c++20` and as of Clang 14 the use of `ATOMIC_VAR_INIT()` causes a bunch of deprecation warnings (I didn't see these warnings previously with Clang 13). Right now the warnings are harmless (but annoying). I think this can be easily worked around by creating a new macro that expands to `ATOMIC_VAR_INIT` only if the value of `__cplusplus` is less than 2020.

**Comment by daanx** [comment]
Thanks for the report, it should be fixed now.
