### ISSUE TITLE
posix_memalign broken in 1.7.5

### ISSUE THREAD

**Issue by albi-k** [microsoft/mimalloc#577]
Hi,
Allocating 2MiB aligned buffers fails in version 1.7.5. I have used this successfully in the past version 1.7.2.

```
#include <stdlib.h>
#include <assert.h>
#include <iostream>

int main()
{
	void* mem;
	if (posix_memalign(&mem, 2*1024*1024, 2*1024*1024) == 0)
		std::cout << "Success" << std::endl;
	else
		std::cout << "Failed with errno: " << errno << std::endl;
	return 0;
}

```

**Comment by daanx** [comment]
Yes, apologies -- I set a max alignment of 1MiB but that is clearly not enough. 
This is the same issue as #576.  A work-around for now is to use the latest `dev-slice` where the limit is 16 MiB.

**Comment by albi-k** [comment]
Ah, ok, just wanted to bring it to your attention.
My reason for using the 2MiB alignment is to try to improve the odds of those buffers being backed by "hugepages" although I'm not sure if it truly makes a difference.

**Comment by daanx** [comment]
Thanks for the report :-). But, right, in mimalloc the use of huge pages is automatic and alinging yourself will only make it worse. If "transparent huge pages" are enabled, mimalloc will already do optimal alignment of its super blocks (segment). Furthermore, using MIMALLOC_LARGE_PAGES=1 will force the use of such 2MiB OS pages (if the OS is configured to allow this).
