### ISSUE TITLE
bug: mi_heap_contains_block is not consistent with mi_heap_malloc_aligned

### ISSUE THREAD

**Issue by romange** [microsoft/mimalloc#587]
to reproduce:
```
void* res = mi_heap_malloc_aligned(heap_, 33554426, 8);
assert(mi_heap_contains_block(heap_, res));

```

for sizes smaller than 33554426 this passes. For this size the assertion fails.
tested on v2.0.5

**Comment by romange** [comment]
@daanx hello. did you have a chance to look at this bug?

**Comment by epoupon** [comment]
Looks like related to  #570

**Comment by daanx** [comment]
This is fixed now in the latest release where huge blocks are correctly owned by a heap like all other blocks.
