### ISSUE TITLE
feature request: bind `mi_heap_t` to certain `mi_arena_t`.

### ISSUE THREAD

**Issue by sighingnow** [microsoft/mimalloc#617]
The `mi_manage_os_memory()` API allows adding pre-reserved memory piece as an arena and makes subsequential allocation happens on that arena. But in programs where we have multiple pre-reserved memory piece and want to keep some level of isolation between those memory pieces, we cannot use a new heap for each arena, as currently allocation on `mi_heap_t` will lookup all arenas (see https://github.com/microsoft/mimalloc/blob/master/src/arena.c#L152-L191).

I'm wonder if there's any plan or possbility to implement the idea of binding heap to certain arena, as proposed in https://github.com/microsoft/mimalloc/issues/53#issuecomment-622235492?

**Comment by daanx** [comment]
The latest `dev-slice` (v2) has an initial experimental api where you can create a heap that exclusively allocates in a certain arena (running out of memory when the arena is full).  Let me know what you think :-)

```C
// Experimental: heaps associated with specific memory arena's
typedef int mi_arena_id_t;
mi_decl_export void* mi_arena_area(mi_arena_id_t arena_id, size_t* size);
mi_decl_export int   mi_reserve_huge_os_pages_at_ex(size_t pages, int numa_node, size_t timeout_msecs, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;
mi_decl_export int   mi_reserve_os_memory_ex(size_t size, bool commit, bool allow_large, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;
mi_decl_export bool  mi_manage_os_memory_ex(void* start, size_t size, bool is_committed, bool is_large, bool is_zero, int numa_node, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;

#if MI_MALLOC_VERSION >= 200
mi_decl_nodiscard mi_decl_export mi_heap_t* mi_heap_new_in_arena(mi_arena_id_t arena_id);
#endif
```

**Comment by sighingnow** [comment]
Hi @daanx,

Sorry for responding so late. I would like you know that we have cecently introduced this feature into our product and it works quite well.

Thanks!

**Comment by ysbqiaqia** [comment]
> The latest `dev-slice` (v2) has an initial experimental api where you can create a heap that exclusively allocates in a certain arena (running out of memory when the arena is full). Let me know what you think :-)
> 
> ```c
> // Experimental: heaps associated with specific memory arena's
> typedef int mi_arena_id_t;
> mi_decl_export void* mi_arena_area(mi_arena_id_t arena_id, size_t* size);
> mi_decl_export int   mi_reserve_huge_os_pages_at_ex(size_t pages, int numa_node, size_t timeout_msecs, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;
> mi_decl_export int   mi_reserve_os_memory_ex(size_t size, bool commit, bool allow_large, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;
> mi_decl_export bool  mi_manage_os_memory_ex(void* start, size_t size, bool is_committed, bool is_large, bool is_zero, int numa_node, bool exclusive, mi_arena_id_t* arena_id) mi_attr_noexcept;
> 
> #if MI_MALLOC_VERSION >= 200
> mi_decl_nodiscard mi_decl_export mi_heap_t* mi_heap_new_in_arena(mi_arena_id_t arena_id);
> #endif
> ```
Is there some demo for using?

**Comment by FoxieFlakey** [comment]
Should I open a new issue for this one questions? Thank you

The question is if I have deleted/destroyed all heap instances bound to an arena, Will it be safe to unmap/deallocate/whatever the memory managed by the arena? 

I seemingly can't find the documentation about "when its safe to do that" nor any function which similiar to `mi_arena_forget(mi_arena_id_t arena)` which makes mimalloc forgets that it even exist (effectively undo the `mi_manage_os_memory_ex` and its other variant effect but for the `mi_reserve_os_memory_ex` it releases the reservations)
