### ISSUE TITLE
Can't find mimalloc-override.o

### ISSUE THREAD

**Issue by vient** [microsoft/mimalloc#621]
Documentation mentions using `mimalloc-override.o` to statically override malloc but I can't find it anywhere, and cmake lists seem to not mention it. Was it deprecated?

**Comment by thehans** [comment]
As I understand it, only the visual studio solution generates the `-override` suffix.  But as long as your cmake options are all set correctly to statically override, then `mimalloc.o` or whatever resulting filename should work in its place.
