### ISSUE TITLE
"grep: memory exhausted" bug in 2.0.6

### ISSUE THREAD

**Issue by yu-re-ka** [microsoft/mimalloc#622]
```
$ LD_PRELOAD=libmimalloc.so grep foo
grep: memory exhausted

$
```

2.0.5 works fine.
bisected this to https://github.com/microsoft/mimalloc/commit/3c7ce7d3c6cd6a71db65cdd06881f45ab0848078, and reverting that fixes it

**Comment by daanx** [comment]
ah, that is very strange. Thanks for bisecting! Just difficult to say what happened though -- what OS did you use ? and what version of grep?  I will try to repro and attach a debugger to see what is the cause.

**Comment by yu-re-ka** [comment]
gnugrep 3.7 from NixOS

I used this script while bisecting nixpkgs:

```
#!/usr/bin/env bash
nix build .#mimalloc -o mimalloc
nix build .#gnugrep -o grep 
LD_PRELOAD=$PWD/mimalloc/lib/libmimalloc.so ./grep/bin/grep foo default.nix
```

**Comment by yu-re-ka** [comment]
here is a stacktrace:

![image](https://user-images.githubusercontent.com/86169957/191899556-26ecbcb8-73db-4da4-9184-f6493f6db4ad.png)

**Comment by daanx** [comment]
Ah, I see what happened (I think :-) ).
The `_mi_heap_realloc_zero` routine is called with `p=NULL` and `newsize=0` (little strange of course, but alas).
This will call eventually`_mi_heap_malloc_zero`, and since the size happened to be 0, it used to allocate a zero-size cell in mimalloc and return non-NULL. But after the commit above, it now returns `p` (= NULL) without allocation... I don't think that is strictly wrong but I will revert to the old behavior .

**Comment by yu-re-ka** [comment]
It does indeed fix the issue. Thanks!

**Comment by res2k** [comment]
An older, but still interesting summary on how other implementations handle zero-size (re-)allocs: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2396.htm#dr_400
(Spoiler: it's all over the place)

**Comment by asuka-mio** [comment]
> Ah, I see what happened (I think :-) ). The `_mi_heap_realloc_zero` routine is called with `p=NULL` and `newsize=0` (little strange of course, but alas). This will call eventually`_mi_heap_malloc_zero`, and since the size happened to be 0, it used to allocate a zero-size cell in mimalloc and return non-NULL. But after the commit above, it now returns `p` (= NULL) without allocation... I don't think that is strictly wrong but I will revert to the old behavior .
> 
> edit: ah, I see it was already fixed in the latest `dev-slice` branch.. ! I will release an updated version soon. Can you check if the latest `dev-slice` indeed fixes the issue for you (if it is not too much effort)

The dev-slice branch would failed on build for 32-bit devices:
FAILED: /home/tarsin/Acme/out/soong/.intermediates/external/mimalloc/libmimalloc/android_arm_armv8-a_cortex-a76_static/obj/external/mimalloc/src/bitmap.o
PWD=/proc/self/cwd prebuilts/clang/host/linux-x86/clang-r450784d/bin/clang -c -mthumb -Os -fomit-frame-pointer -DANDROID -fmessage-length=0 -W -Wall -Wno-unused -Winit-self -Wpointer-arith -Wunreachable-code-loop-increment -no-canonical-prefixes -DNDEBUG -UDEBUG -fno-exceptions -Wno-multichar -O2 -g -fdebug-default-version=5 -fno-strict-aliasing -Werror=date-time -Werror=pragma-pack -Werror=pragma-pack-suspicious-include -Werror=string-plus-int -Werror=unreachable-code-loop-increment -D__compiler_offsetof=__builtin_offsetof -faddrsig -fcommon -Werror=int-conversion -fexperimental-new-pass-manager -Wno-reserved-id-macro -fcolor-diagnostics -Wno-sign-compare -Wno-defaulted-function-deleted -Wno-inconsistent-missing-override -Wno-c99-designator -Wno-gnu-designator -Wno-gnu-folding-constant -Wunguarded-availability -D__ANDROID_UNAVAILABLE_SYMBOLS_ARE_WEAK__ -ffp-contract=off -fdebug-prefix-map=/proc/self/cwd= -ftrivial-auto-var-init=zero -enable-trivial-auto-var-init-zero-knowing-it-will-be-removed-from-clang -ffunction-sections -fdata-sections -fno-short-enums -funwind-tables -fstack-protector-strong -Wa,--noexecstack -D_FORTIFY_SOURCE=2 -Wstrict-aliasing=2 -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Werror=format-security -nostdlibinc -fdebug-info-for-profiling -Wno-enum-compare -Wno-enum-compare-switch -Wno-null-pointer-arithmetic -Wno-null-dereference -Wno-pointer-compare -Wno-xor-used-as-pow -Wno-final-dtor-non-final-class -Wno-psabi -Wno-null-pointer-subtraction -Wno-string-concatenation -msoft-float -march=armv8-a -mfloat-abi=softfp -mfpu=neon-fp-armv8 -mcpu=cortex-a55 -mfpu=neon-fp-armv8 -D__ARM_FEATURE_LPAE=1 -target armv7a-linux-androideabi10000 -fPIC  -Iexternal/mimalloc/include -Iexternal/mimalloc/src -Iexternal/mimalloc/include -Iexternal/mimalloc -isystem bionic/libc/include -isystem bionic/libc/kernel/uapi/asm-arm -isystem bionic/libc/kernel/uapi -isystem bionic/libc/kernel/android/scsi -isystem bionic/libc/kernel/android/uapi -Wall -Werror -O3 -DMI_DEBUG=0 -fPIC -Wall -Wextra -fvisibility=hidden -ftls-model=initial-exec -fno-emulated-tls -Wno-unused-parameter -Wno-unused-function -Wno-missing-field-initializers -std=gnu11 -Isystem/core/include -Isystem/logging/liblog/include -Isystem/media/audio/include -Ihardware/libhardware/include -Ihardware/libhardware_legacy/include -Ihardware/ril/include -Iframeworks/native/include -Iframeworks/native/opengl/include -Iframeworks/av/include  -Werror=bool-operation -Werror=implicit-int-float-conversion -Werror=int-in-bool-context -Werror=int-to-pointer-cast -Werror=pointer-to-int-cast -Werror=string-compare -Werror=xor-used-as-pow -Wno-void-pointer-to-enum-cast -Wno-void-pointer-to-int-cast -Wno-pointer-to-int-cast -Werror=fortify-source -Werror=address-of-temporary -Werror=return-type -Wno-tautological-constant-compare -Wno-tautological-type-limit-compare -Wno-reorder-init-list -Wno-implicit-int-float-conversion -Wno-sizeof-array-div -Wno-tautological-overlap-compare -Wno-deprecated-copy -Wno-range-loop-construct -Wno-misleading-indentation -Wno-zero-as-null-pointer-constant -Wno-deprecated-anon-enum-enum-conversion -Wno-string-compare -Wno-pessimizing-move -Wno-non-c-typedef-for-linkage -Wno-align-mismatch -Wno-error=unused-but-set-variable -Wno-error=unused-but-set-parameter -Wno-unused-but-set-variable -Wno-unused-but-set-parameter -Wno-bitwise-instead-of-logical -MD -MF /home/tarsin/Acme/out/soong/.intermediates/external/mimalloc/libmimalloc/android_arm_armv8-a_cortex-a76_static/obj/external/mimalloc/src/bitmap.o.d -o /home/tarsin/Acme/out/soong/.intermediates/external/mimalloc/libmimalloc/android_arm_armv8-a_cortex-a76_static/obj/external/mimalloc/src/bitmap.o external/mimalloc/src/bitmap.c
In file included from external/mimalloc/src/bitmap.c:21:
In file included from external/mimalloc/include/mimalloc-internal.h:11:
external/mimalloc/include/mimalloc-types.h:167:2: error: "mimalloc internal: the max aligned boundary is too large for the segment size"
#error "mimalloc internal: the max aligned boundary is too large for the segment size"
 ^
1 error generated.

I make a fix, see: https://github.com/AcmeUI/android_external_mimalloc/commit/52325f43bba883601fda3f2379c83eb08ee5ed20

**Comment by daanx** [comment]
> An older, but still interesting summary on how other implementations handle zero-size (re-)allocs: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2396.htm#dr_400
> (Spoiler: it's all over the place)

Thanks for the link! There is also
<https://en.cppreference.com/w/c/memory/realloc>
where it seems that C23 makes it undefined behavior with a `newsize=0`. I think the current `mi_malloc` behavior is at least consistent now where `NULL` is (now) only returned on error (and zero-sized allocations return a valid pointer).

**Comment by daanx** [comment]
@asuka-mio -mio wrote:
> The dev-slice branch would failed on build for 32-bit devices:
FAILED: 

Ah, thanks for the heads up -- I'll fix that.

**Comment by yu-re-ka** [comment]
Should we downgrade to 2.0.5 (in NixOS/Nixpkgs) until the new release is ready?

**Comment by daanx** [comment]
Just released a new version with the alignment fix.
