### ISSUE TITLE
overridden new/delete operators are not inlined

### ISSUE THREAD

**Issue by obhi-d** [microsoft/mimalloc#624]
File: mimalloc-new-delete.h
Operators are not inlined, this causes warning/errors during linking objs like:
 warning LNK4006: "void __cdecl operator delete[](void *,unsigned __int64)" (??_V@YAXPEAX_K@Z) already defined in unity_0_cxx.cxx.obj; second definition ignored

**Comment by daanx** [comment]
You should include this header file in only 1 source (`.cpp`) file -- did you do this or is it included in other files as well?

**Comment by obhi-d** [comment]
I definitely included it in a top level header file. My scenario is, I have a dll (lets call it base.dll) linking to mimalloc. The exe/other dlls linking to this base.dll should also use the overriden new/delete operator. Without explicitly exporting the operator definition from base dll, wouldnt I need to include this file in all dll/binaries then?

**Comment by daanx** [comment]
C++ requires just one definition for new/delete operations in a single compilation unit. So, you cannot define those in a top level header that is included in various source files.

On windows, DLL's are special -- and the idea is that each DLL uses it's own allocator and pointers allocated in one DLL should not be deallocated by another. So, overriding C++ new/delete needs to be done per DLL/EXE (called module). 

This is why `mimalloc` has the `mimalloc-redirect.dll` (see the README on dynamic overriding on Windows) which allows you to override the standard C library allocator executable wide for all loaded DLL's.  There is no other good way on Windows to do executable wide overloading as far as I know..

**Comment by obhi-d** [comment]
Okay thanks for clarifying. I am aware that a pointer allocated by one DLL in windows cannot be deallocated from another. I am relying on mimalloc-redirect (which I assumed overrides std::malloc/std::free, but I wasn't sure about the operator). I will close the issue, and read more about new/delete. Cheers.
