### ISSUE TITLE
how to use mimalloc in bazel project

### ISSUE THREAD

**Issue by viktorika** [microsoft/mimalloc#639]
i use bazel's malloc option to link mimalloc，and the compilation of mimaloc is as follows

cc_library(
    name = "mimalloc",
    srcs = [
        "src/static.c",
    ],
    textual_hdrs = glob(["src/*.c", "src/*.h"], exclude = ["src/static.c"]),
    hdrs = glob(["include/*.h"]),
    includes = ["include"],
    copts = [
        "-DMI_MALLOC_OVERRIDE",
        "-O2",
        "-Wall",
        "-Wextra",
        "--std=c++17",
    ],
    linkopts = [
        "-pthread",
        "-lrt",
    ],
    visibility = ["//visibility:public"],
)

because of the global variable initialization order，i find i can't control mi_process_load function execute before mi_malloc，What should I do?

**Comment by daanx** [comment]
Hi, the options seem ok where you link mimalloc statically with overriding. What is the exact problem? It should be the case `mi_process_load` is called first if possible when trying to override `malloc`/`free` so no one will allocate before mimalloc is initialized. What happens in your case?

**Comment by viktorika** [comment]
Now i want to use it in my server，but my server's framework has many global variable，when i use bazel's malloc option to link mimalloc，it will call abort。I use gdb debug then found the reason is that the mi_process_load is called after mi_malloc，i can't find a way to call mi_process_load first。

**Comment by daanx** [comment]
Overriding `malloc`/`free` is always a bit tricky -- did you read the [Overriding](https://github.com/microsoft/mimalloc#overriding-standard-malloc) section carefully?  

What OS are you targeting ?  What compiler are you using ?   Maybe dynamic overriding can work better?  

I guess you use C++ and the static initializers allocate memory (maybe by calling `atexit` for the destructors) before `main` runs. However, mimalloc should handle that fine and initialize; so I need more info what is going wrong.

**Comment by viktorika** [comment]
My environment is Linux，gcc7。And static override as follow。
cc_binary(
    name = "main",
    srcs = [
        "main.cc",
    ],
    malloc = ":mimalloc",
    deps = [
      '//comm2/summer:summer',
      '//comm2/svrkit:svrkitepoll',
      '//comm2/svrkit:svrkit_pb',
      '//comm2/tlvpickle:skbuiltintype',
    ],
    copts = [
      '-O2',
      '-Wall',
      '-Wextra',
      '-Werror',
      '--std=c++17',
    ],
    visibility = ["//visibility:public"],
)

I'll try dynamic link when I'm free。

**Comment by viktorika** [comment]
oh，i can't link with the library，it is ok that link the final program with the single object file
