### ISSUE TITLE
vs2019 fails to build mimalloc.sln from dev-slice commit ba8c0f890314d80d830599f686eaa63aafcee880

### ISSUE THREAD

**Issue by jackL999** [microsoft/mimalloc#643]
The build caused the link error LNK2019: unresolved external symbol **_mi_heap_malloc_zero_ex**
The error messages were,
`Creating library V:\mimalloc\ide\vs2019\..\..\out\msvc-x64\Release\mimalloc-override.lib and object V:\mimalloc\id
  e\vs2019\..\..\out\msvc-x64\Release\mimalloc-override.exp
alloc-aligned.obj : error LNK2019: unresolved external symbol _mi_heap_malloc_zero_ex referenced in function mi_heap_ma
lloc_zero_aligned_at_fallback [V:\mimalloc\ide\vs2019\mimalloc-override.vcxproj]
V:\mimalloc\ide\vs2019\..\..\out\msvc-x64\Release\mimalloc-override.dll : fatal error LNK1120: 1 unresolved externals [
V:\mimalloc\ide\vs2019\mimalloc-override.vcxproj]
`

**Comment by DaPhreak** [comment]
Same here.

**Comment by daanx** [comment]
I think it is fixed
