### ISSUE TITLE
assertion: "mi_page_usable_block_size(_mi_ptr_page(p)) >= adjust + size" on dev branch

### ISSUE THREAD

**Issue by epoupon** [microsoft/mimalloc#650]
Hello!
Just tested `dev` branch @ 4b56af178ec681ccd458d821905548231b0ad094
I get this assert when alignment is 4 or 8:
assertion: "mi_page_usable_block_size(_mi_ptr_page(p)) >= adjust + size" (src/alloc-aligned.c, l.67)
Note this worked fine in 1.7.7

**Comment by daanx** [comment]
Thanks for the report! I fixed the assertion (the code was correct, the assert was wrong).  Best, Daan
