### ISSUE TITLE
COPY command in the post-build event for the mimalloc-override project must enclose path in double-quotes

### ISSUE THREAD

**Issue by dennisbabkin** [microsoft/mimalloc#666]
The following command in the post-build event for the "mimalloc-override" project's configuration properties:

`COPY /Y $(ProjectDir)..\..\bin\mimalloc-redirect.dll $(OutputPath)`

must be changed to:

`COPY /Y "$(ProjectDir)..\..\bin\mimalloc-redirect.dll" "$(OutputPath)"`

to account for possible spaces in the file path.

**Comment by daanx** [comment]
Thanks so much!
