### ISSUE TITLE
Statically linking on Windows deadlocks on exit

### ISSUE THREAD

**Issue by Unsttopabull** [microsoft/mimalloc#672]
Minmalloc deadlocks on exit if you try to set a new default heap in the main thread 

Minimal example:
https://github.com/Unsttopabull/mimalloc-test 

Tested on:

Minmalloc v2.0.7

Windows 11 (21H2)
Visual Studio 2017 (15.9.51)
MinGW GCC 12.2
MinGW Clang 15

**Comment by daanx** [comment]
ah, what a strange bug; but I think it is fixed now :-)
