### ISSUE TITLE
OS memory may not be 0 initialized (leads to various crashes)

### ISSUE THREAD

**Issue by epoupon** [microsoft/mimalloc#703]
Hello,

mimalloc assumes OS memory is 0 initialized but it may not be the case on some platforms (which are not the officially supported ones)
For instance we had to manually memset the OS memory in `mi_thread_data_alloc` and in `mi_segment_alloc` after the `mi_segment_os_alloc` call.
It would be really handy to have something like `bool _mi_os_is_mem_zero_initialized()` to handle this problem

**Comment by daanx** [comment]
Thank you for the report. In the latest `dev` (and down stream `dev-slice`) I reorganized the files and the `src/prim` directory contains the primitive OS definitions for each platform. It would be best for your platform to add an explicit `_mi_memzero` call when the `_mi_prim_alloc` primitive is called. That ensures everything will work as expected. 

Hope this helps. Also, I hope the new separation of the low level API primitives help with porting to new platforms; let me know how it goes.

**Comment by enihcam** [comment]
https://github.com/miniupnp/miniupnp/issues/652

**Comment by epoupon** [comment]
Thanks! Will test this asap and tell you

**Comment by daanx** [comment]
Just a note that the latest release added more `is_zero` parameters to commit as well in the primitives.

**Comment by epoupon** [comment]
Hello, sorry I forgot to tell you that it is fine now!
Thank you for having isolated the OS-dependent code (perhaps some parts of init.c could have been integrated there)
