### ISSUE TITLE
Missing `mimalloc-override.o`?

### ISSUE THREAD

**Issue by thevinster** [microsoft/mimalloc#706]
I'm trying to link my programs statically on MacOS. According to the docs, it says to link it statically with `mimalloc-override.o`, but I don't see when after running CMake and make all. Looking through the Makefile, I do see `alloc-override-osx.c.o` within the CMakeFiles. Am I supposed to be linking against that object file? Is this the correct way to link MacOS programs statically for mimalloc?  

This was on the v2.0.9 release tag.

**Comment by thevinster** [comment]
I think I figured it out. I'm supposed to link with `CMakeFiles/mimalloc-obj.dir/src/static.c.o`. The docs seem outdated.

**Comment by daanx** [comment]
Ah yes. When you run "make install" it will take that file and install it as "mimalloc-override.o" but when just building it is not there. Will try to fix it.

**Comment by daanx** [comment]
I fixed this with an extra custom action to copy the object file to the cmake directory. Now called just "mimalloc.o" without the override for consistency with `libmimalloc.a`.
Thanks!
