### ISSUE TITLE
Debug assertions are not silent

### ISSUE THREAD

**Issue by gnzlbg** [microsoft/mimalloc#72]
Enabling `-DMI_DEBUG=3` produces output even when no errors are encountered. The library should only print when there is something to print.

**Comment by gnzlbg** [comment]
You could use a `MI_VERBOSE=LEVEL` to control when output is emitted.

**Comment by daanx** [comment]
Ah, building with `-DMI_DEBUG=3` enables the verbose option by default. You can suppress that by setting `MIMALLOC_VERBOSE=0`. I guess you would like that to be the default always.?

**Comment by gnzlbg** [comment]
Ah thank you, sorry for the duplicated issue, I thought they were unrelated. 

I think that would be a better default for packagers.

---

Unrelated, would it be possible to move all configuration macros into their own file, and document them there ? Figuring out which macros exist and what they do requires going fishing through the library sources. The library is not too big, so it can be done, but it is often unclear to me what they are intended to do. Maybe I should open a different issue for this ?

**Comment by daanx** [comment]
In the latest dev branch ([dev 6abdc5f]) I disabled the default verbose output even in debug build. 
Thanks!
