### ISSUE TITLE
limit process total memory

### ISSUE THREAD

**Issue by rtttech** [microsoft/mimalloc#730]
I need to limit the total memory of my program,  does mimalloc support this feature?

**Comment by epoupon** [comment]
Note that you can also use `ulimit` to limit the memory of your process (and you can also tweak the kernel in order to prevent overcommit)

**Comment by rtttech** [comment]
Our application runs on windows, linux, android, and other limited env,  and has disk file cache which can been freed when total memory reach the up limit. @daanx @epoupon
