### ISSUE TITLE
When build with musl, aligned_alloc function will not build

### ISSUE THREAD

**Issue by youngbe** [microsoft/mimalloc#733]
musl is an implementation of the C standard library built on top of the Linux system, just like glibc.
https://musl.libc.org/

When using musl to build mimalloc, it will not build aligned_alloc function, because musl not provide __USE_ISOC11 macro.

src/alloc-override.c:
```c
#if __USE_ISOC11
  void* aligned_alloc(size_t alignment, size_t size) { return mi_aligned_alloc(a
lignment, size); }
  #endif
```

I'm not sure if this macro is part of the C language standard, so, if this macro is part of the C language standard, then it's a musl bug, otherwise it's a mimalloc bug.

**Comment by daanx** [comment]
Ah, that is not great; if you read the comment, the macro is needed or otherwise Conda builds break.  Did you try to compile with `--std=c11` ?  Maybe we need to define `_ISOC11_SOURCE` at build time?  tbc

**Comment by youngbe** [comment]
Sorry, I am busy recently, I will find time to build.
