### ISSUE TITLE
minject reports "image virtual size extends beyond section data (0x2ed5000ul vs. 0x2ee4000ul)"

### ISSUE THREAD

**Issue by DaPhreak** [microsoft/mimalloc#734]
Hello!
Today minject reports this message when I try to run it on one of my unit tests.
When I delete just one of the tests in my source, it works fine.
But that is not a solution...

What can I do?

**Comment by daanx** [comment]
Yeah, `minject` cannot always rewrite a binary in-place... but maybe there is a way to improve it. Can you share the binary  that doesn't work for you so I can take a look?

**Comment by DaPhreak** [comment]
Yes, I can send you the exe (by email?).

**Comment by thehans** [comment]
@daanx can `minject` sources be added to the repository at some point, or is it strictly closed source?

**Comment by daanx** [comment]
Thanks -- I got the exe and can repro. Will look at it in the coming week.
Ah, sorry Hans but I have no plans to open source this at this time... (I am still having hope to integrate mimalloc directly into Windows itself in the future)

**Comment by DaPhreak** [comment]
> Thanks -- I got the exe and can repro. Will look at it in the coming week. 
Thank you very much!
If I change a bit in the Source in some random places, it works.
Yesterday I just ignored the test, developed further on our source and now all our executables (250+) can be injected.
Very strange...
 
> (I am still having hope to integrate mimalloc directly into Windows itself in the future)
Please, don't do that!
This would eliminate an advantage to our competitors. :laughing:

**Comment by daanx** [comment]
I might have fixed this in the latest dev and dev-slice branches; can you try?

**Comment by DaPhreak** [comment]
OK, I try ;)
