### ISSUE TITLE
ATOMIC_VAR_INIT deprecation warnings when building UE 5.1.1 with XCode 14.3

### ISSUE THREAD

**Issue by TroutZhang** [microsoft/mimalloc#735]
Similar to #571, I've met this deprecation warning (which treats as an error in Unreal), when building the current latest release 5.1.1 source code with the newly released XCode 14.3.

Unreal Engine 5 build C++ with [C++17 by default](https://github.com/EpicGames/UnrealEngine/blob/5ca9da84c694c6eee288c30a547fcaa1a40aed9b/Engine/Source/Programs/UnrealBuildTool/System/CppCompileEnvironment.cs#L54), so the [original fix for C++20](https://github.com/microsoft/mimalloc/commit/b7677b6f8482daad8374b2cf5430be2156308063) is not enough.
Though Unreal Engine 5 didn't specify the default C standard, Clang has its [default to C17](https://clang.llvm.org/compatibility.html)

> By default, Clang builds C code in GNU C17 mode

Thus, the [commit introducing the deprecation](https://github.com/apple/llvm-project/commit/0d459444e5105d689e6388612784b89a93054944) will be triggered when compiling [MiMalloc.c](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Source/Runtime/Core/Private/Thirdparty/MiMalloc.c) in the Clang's default C17 mode.

**Comment by daanx** [comment]
Thanks so much!

**Comment by daanx** [comment]
Should be fixed in the new release.
