### ISSUE TITLE
Is the CMake option MI_INSTALL_TOPLEVEL=ON really deprecated ?

### ISSUE THREAD

**Issue by Romain-Geissler-1A** [microsoft/mimalloc#737]
Hi,

I tried to ask this question already in https://github.com/microsoft/mimalloc/pull/255#issuecomment-1507110615 but there was no answer. Basically the question is: is the CMake option MI_INSTALL_TOPLEVEL=ON really deprecated ? And if yes how to you expect users to use mimalloc (ie you really want the users to bother about the subfolder name containing the mimalloc version which will regularly change) ?

Also, I quickly checked the fedora package, it uses this option: https://src.fedoraproject.org/rpms/mimalloc/blob/rawhide/f/mimalloc.spec#_37 I don't know if other distro package mimalloc, but they may use this option to. So is it really deprecated ?

Cheers,
Romain

**Comment by daanx** [comment]
Apologies for not answering earlier;  I undeprecated the option -- backwards compatibility is really important. I only deprecated as I thought there was not much use but I was wrong :-). Thanks!

**Comment by daanx** [comment]
Part of this is that I have been so amazed how much the CMakefile and options have grown while initially the idea was to have no options at all ... it is just a symptom of its success but I am still trying to minimize the complexity as much as I can.

**Comment by Romain-Geissler-1A** [comment]
Ok thanks. In your commit, you didn't remove the ` (deprecated)` string in the option description ;)

Then we will use this option to package mimalloc in the internal Amadeus build system and try to compare it to other famous allocator and see if it improves our workload. We can close this ticket.

Thanks !

**Comment by daanx** [comment]
> Ok thanks. In your commit, you didn't remove the ` (deprecated)` string in the option description ;)

Ah, I'll fix that too. Thanks again!
