### ISSUE TITLE
Expose standard C and POSIX APIs even without override

### ISSUE THREAD

**Issue by gnzlbg** [microsoft/mimalloc#75]
It would be great if the library could always expose a standard C and POSIX API, e.g., for example, right now, `mi_aligned_alloc` and `mi_posix_memalign` are missing. 

Ideally, they would always be available. This would allow writing a wrapper that uses the standard C names, e.g., `aligned_alloc`, and just always calls `mi_aligned_alloc` internally, instead of having some logic to do different things depending on `MI_OVERRIDE`.

**Comment by daanx** [comment]
I agree -- hope to get to it soon

**Comment by daanx** [comment]
The new commit exposes a whole host of `mi_` prefixed posix, unix, and C++ allocation variants. 
We just need a header file now that will automatically redirect `malloc` to `mi_malloc` and friends and that should give one more option of overriding malloc in projects. :-)

**Comment by gnzlbg** [comment]
Thank you!
