### ISSUE TITLE
Rights regarding the mimalloc logo

### ISSUE THREAD

**Issue by ErnyTech** [microsoft/mimalloc#76]
I would like to know the situation regarding the rights to use the mimalloc logo.
I would like to use it personally for my wrapper that I am creating to allow the use of mimalloc in the programming language D

**Comment by daanx** [comment]
Ah cool! Let me know how that goes and if there are issues (or improved performance :-) )
The logo is free -- it is included under the MIT license -- is that good enough?

**Comment by ErnyTech** [comment]
Thank you for having responded so quickly!

In case you have anything else to ask about my wrapper I'll open another issue

Thanks!
