### ISSUE TITLE
mi_malloc is much slower then original malloc in Windows (In big memory allocation, bigger then 1MB)

### ISSUE THREAD

**Issue by shisiyuan2011** [microsoft/mimalloc#799]
I test it in Windows10 visual studio2017 with single code,
	const auto start = std::chrono::steady_clock::now();

	for (int i = 0; i < 1000000; ++i)
	{
		void *p = mi_malloc(1024);//compare to malloc(1024) also malloc(1) mi_malloc(1) is the same
		mi_free(p);
	}

	const auto end = std::chrono::steady_clock::now();
	const auto num_ms = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
	const auto us_per_allocation = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
	std::cout << " allocations Done in " << num_ms << "us." << std::endl;

which is much slower then original malloc in Windows(slower for 3times);
did I miss some important code or I had some mistake in using of mimalloc?

**Comment by shisiyuan2011** [comment]
I'm sorry for unclear description, when I test the small memory(below 1MB) mimalloc is fast, but when I test big memory allocation(bigger then 1MB), the mimalloc is much smaller then sys malloc, the bigger memory the slower it is(80MB mimalloc 75us, sys malloc 3us). about the enveriment I set the mi_option as default.

**Comment by avpdiver** [comment]
Same issue on Ubuntu 22.04. But much worse.
CPU AMD Ryzen 5 2600.
Release compilation. 
The code is simple:
```

void Malloc_Test(size_t size)
{
    // warm up
    auto ptr = malloc(size);
    free(ptr);

    // test
    const auto begins = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < 1'000'000; i++)
    {
        ptr = malloc(size);
        free(ptr);
    }
    const auto ends = std::chrono::high_resolution_clock::now();

    const auto duration = ends - begins;
    std::cout << "Malloc avg time:\t\t" << (duration.count() / 1'000'000) << std::endl;
}

void MiMalloc_Test(size_t size)
{
    // warm up
    auto ptr = mi_malloc(size);
    mi_free(ptr);

    // test
    const auto begins = std::chrono::high_resolution_clock::now();
    for (size_t i = 0; i < 1'000'000; i++)
    {
        ptr = mi_malloc(size);
        mi_free(ptr);
    }
    const auto ends = std::chrono::high_resolution_clock::now();

    const auto duration = ends - begins;
    std::cout << "MiMalloc avg time:\t" << (duration.count() / 1'000'000) << std::endl;
}

int main()
{
    size_t SIZE[] = {
        8,
        16,
        32,
        64,
        128,
        1024,
        2048,
        4096,
        1048576,
        2097152};

    for (auto size : SIZE)
    {
        std::cout << "-----------------------------------" << std::endl;
        std::cout << "Alloc size: " << size << std::endl;
        Malloc_Test(size);
        MiMalloc_Test(size);
    }
   
    return 0;
}
```
The output is:
```
-----------------------------------
Alloc size: 8
Malloc avg time:	0
MiMalloc avg time:	156
-----------------------------------
Alloc size: 16
Malloc avg time:	0
MiMalloc avg time:	133
-----------------------------------
Alloc size: 32
Malloc avg time:	0
MiMalloc avg time:	132
-----------------------------------
Alloc size: 64
Malloc avg time:	0
MiMalloc avg time:	132
-----------------------------------
Alloc size: 128
Malloc avg time:	0
MiMalloc avg time:	141
-----------------------------------
Alloc size: 1024
Malloc avg time:	0
MiMalloc avg time:	170
-----------------------------------
Alloc size: 2048
Malloc avg time:	0
MiMalloc avg time:	221
-----------------------------------
Alloc size: 4096
Malloc avg time:	0
MiMalloc avg time:	322
-----------------------------------
Alloc size: 1048576
Malloc avg time:	0
MiMalloc avg time:	69978
-----------------------------------
Alloc size: 2097152
Malloc avg time:	0
MiMalloc avg time:	99714
```

**Comment by cneumann** [comment]
Modern compilers understand the semantics of `malloc`/`free` and are capable of eliminating the calls to these functions under certain circumstances. Have you looked at the generated code, I would expect the loop in `Malloc_Test` to be mostly optimized away - the time being 0 for any size is quite suspicious, don't you think?
Mimalloc uses the `malloc` attribute supported by some compilers (see e.g. [gcc manual](https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/Common-Function-Attributes.html#index-malloc-function-attribute)), but from a quick glance at the sources does not seem to associate `mi_free` as the deallocation function - so gcc probably cannot eliminate the calls to `mi_malloc`/`mi_free` in the same way.

**Comment by NaonaoCoke** [comment]
> Same issue on Ubuntu 22.04. But much worse. CPU AMD Ryzen 5 2600. Release compilation.
> 
> ```
> [cmake] -- Library base name: mimalloc
> [cmake] -- Version          : 2.1
> [cmake] -- Build type       : release
> [cmake] -- C Compiler       : /usr/bin/gcc-13
> [cmake] -- Compiler flags   : -Wall;-Wextra;-Wno-unknown-pragmas;-fvisibility=hidden;-Wstrict-prototypes;-ftls-model=initial-exec
> [cmake] -- Compiler defines : 
> [cmake] -- Link libraries   : /usr/lib/x86_64-linux-gnu/libpthread.a;/usr/lib/x86_64-linux-gnu/librt.a
> [cmake] -- Build targets    : static;tests
> ```
> 
> The code is simple:
> 
> ```
> 
> void Malloc_Test(size_t size)
> {
>     // warm up
>     auto ptr = malloc(size);
>     free(ptr);
> 
>     // test
>     const auto begins = std::chrono::high_resolution_clock::now();
>     for (size_t i = 0; i < 1'000'000; i++)
>     {
>         ptr = malloc(size);
>         free(ptr);
>     }
>     const auto ends = std::chrono::high_resolution_clock::now();
> 
>     const auto duration = ends - begins;
>     std::cout << "Malloc avg time:\t\t" << (duration.count() / 1'000'000) << std::endl;
> }
> 
> void MiMalloc_Test(size_t size)
> {
>     // warm up
>     auto ptr = mi_malloc(size);
>     mi_free(ptr);
> 
>     // test
>     const auto begins = std::chrono::high_resolution_clock::now();
>     for (size_t i = 0; i < 1'000'000; i++)
>     {
>         ptr = mi_malloc(size);
>         mi_free(ptr);
>     }
>     const auto ends = std::chrono::high_resolution_clock::now();
> 
>     const auto duration = ends - begins;
>     std::cout << "MiMalloc avg time:\t" << (duration.count() / 1'000'000) << std::endl;
> }
> 
> int main()
> {
>     size_t SIZE[] = {
>         8,
>         16,
>         32,
>         64,
>         128,
>         1024,
>         2048,
>         4096,
>         1048576,
>         2097152};
> 
>     for (auto size : SIZE)
>     {
>         std::cout << "-----------------------------------" << std::endl;
>         std::cout << "Alloc size: " << size << std::endl;
>         Malloc_Test(size);
>         MiMalloc_Test(size);
>     }
>    
>     return 0;
> }
> ```
> 
> The output is:
> 
> ```
> -----------------------------------
> Alloc size: 8
> Malloc avg time:	0
> MiMalloc avg time:	156
> -----------------------------------
> Alloc size: 16
> Malloc avg time:	0
> MiMalloc avg time:	133
> -----------------------------------
> Alloc size: 32
> Malloc avg time:	0
> MiMalloc avg time:	132
> -----------------------------------
> Alloc size: 64
> Malloc avg time:	0
> MiMalloc avg time:	132
> -----------------------------------
> Alloc size: 128
> Malloc avg time:	0
> MiMalloc avg time:	141
> -----------------------------------
> Alloc size: 1024
> Malloc avg time:	0
> MiMalloc avg time:	170
> -----------------------------------
> Alloc size: 2048
> Malloc avg time:	0
> MiMalloc avg time:	221
> -----------------------------------
> Alloc size: 4096
> Malloc avg time:	0
> MiMalloc avg time:	322
> -----------------------------------
> Alloc size: 1048576
> Malloc avg time:	0
> MiMalloc avg time:	69978
> -----------------------------------
> Alloc size: 2097152
> Malloc avg time:	0
> MiMalloc avg time:	99714
> ```

我测试的也很慢，不知道是不是测试的对不对。如果有其他使用方式，请指教一下。另外测试了一下重载的new 与delete，好像重载的要快一些。

**Comment by NaonaoCoke** [comment]
> I test it in Windows10 visual studio2017 with single code, const auto start = std::chrono::steady_clock::now();
> 
> ```
> for (int i = 0; i < 1000000; ++i)
> {
> 	void *p = mi_malloc(1024);//compare to malloc(1024) also malloc(1) mi_malloc(1) is the same
> 	mi_free(p);
> }
> 
> const auto end = std::chrono::steady_clock::now();
> const auto num_ms = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> const auto us_per_allocation = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> std::cout << " allocations Done in " << num_ms << "us." << std::endl;
> ```
> 
> which is much slower then original malloc in Windows(slower for 3times); did I miss some important code or I had some mistake in using of mimalloc?

这个解决了么？

**Comment by shisiyuan2011** [comment]
> > I test it in Windows10 visual studio2017 with single code, const auto start = std::chrono::steady_clock::now();
> > ```
> > for (int i = 0; i < 1000000; ++i)
> > {
> > 	void *p = mi_malloc(1024);//compare to malloc(1024) also malloc(1) mi_malloc(1) is the same
> > 	mi_free(p);
> > }
> > 
> > const auto end = std::chrono::steady_clock::now();
> > const auto num_ms = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> > const auto us_per_allocation = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> > std::cout << " allocations Done in " << num_ms << "us." << std::endl;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is much slower then original malloc in Windows(slower for 3times); did I miss some important code or I had some mistake in using of mimalloc?
> 
> 这个解决了么？

没有，我还尝试了预留内存，并没有提升很快。
我集中测试了1字节-80MiB的存储速度，测试内存在1MiB的时候比sys的malloc快，5MiB的时候就慢下来了，这是针对连续申请。
针对连续申请+写入+释放以及连续申请+释放的过程，mimalloc比sys的malloc要快至少50%。

I focused on testing the allocation speed of 1 byte to 80 MiB, and found that when the allcotion was 1 MiB, it was faster than Sys's malloc, but it slowed down when it was 5 MiB. 
for(int i=0;i<1e+6;++i) custom_malloc(1*MiB);

For the process of continuous application+write+release and continuous application+release, mimalloc is at least 50% faster than sys's malloc.
sort of code is just like that:
for(int i=0;i<1e+6;++i) {
   void*p=custom_malloc(1*MiB);
   custom_free(p);
}
for(int i=0;i<1e+6;++i) {
   char*p=(char*)custom_malloc(1*MiB);
   char*q=p;
   for(int j=0;j<1*MiB;++j){
      *q++='a';
   }
   custom_free(p);
}

**Comment by shisiyuan2011** [comment]
> > I test it in Windows10 visual studio2017 with single code, const auto start = std::chrono::steady_clock::now();
> > ```
> > for (int i = 0; i < 1000000; ++i)
> > {
> > 	void *p = mi_malloc(1024);//compare to malloc(1024) also malloc(1) mi_malloc(1) is the same
> > 	mi_free(p);
> > }
> > 
> > const auto end = std::chrono::steady_clock::now();
> > const auto num_ms = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> > const auto us_per_allocation = std::chrono::duration_cast<std::chrono::microseconds>(end - start).count();
> > std::cout << " allocations Done in " << num_ms << "us." << std::endl;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > which is much slower then original malloc in Windows(slower for 3times); did I miss some important code or I had some mistake in using of mimalloc?
> 
> 这个解决了么？

我最近又读了下源码，发现可以把MI_DEBUG设置成0，能够极大的提升速度（我只是测试了小内存的，可以再试试大内存的）。我觉得这个问题可以关闭了。
感谢开发者！！

I recently learn the code, find set #define MI_DEBUG 0, will accelerate the speed of mimalloc.
I think this issue can be closed.
Thank the developer for this great job again!!!
