### ISSUE TITLE
Readme contains invisible \u200b ZERO WIDTH SPACE, breaking URLs

### ISSUE THREAD

**Issue by o11c** [microsoft/mimalloc#8]
References 5 and 6 are affected.

**Comment by daanx** [comment]
Thanks! Fixed :-)

**Comment by o11c** [comment]
Hm, looks like there are more problems.

6 is still broken, looks like it should be http://courses.cecs.anu.edu.au/courses/CSPROJECTS/16S1/Reports/Timothy_Crundal_Report.pdf

(Also, 2 and 3 are to a site that's offline and not on wayback, but that might be transient)

**Comment by daanx** [comment]
Thanks! Now it should work :-)  the other two links were broken too and should work now.
