### ISSUE TITLE
`mi_heap_visit_blocks` callback is missing explicit calling convention

### ISSUE THREAD

**Issue by seanmiddleditch** [microsoft/mimalloc#84]
The callback `mi_block_visit_fun` is missing a calling convention specification (e.g. `__cdecl` or the like), which can cause linkage problems when mixing a `mimalloc` library compiled with one ABI but linked into a target that uses a different default ABI (e.g. using the `/Gv` switch that can be common in performance-oriented codebases).

Its standard practice in Windows code to always tag a calling convention on callback function declarations to avoid this issue. [Windows headers use the `CALLBACK` macro for this purpose](https://stackoverflow.com/questions/530504/what-does-a-callback-declaration-in-c-do) though specifying a new macro for mimalloc's purpose would suffice too so the code remains portable.

The idea is that this function can be declared in `mimalloc.h` using this specifier and then any user code that is defining a callback for `mi_heap_visit_blocks` would use the same specifier macro for the callback declaration, guaranteeing compatibility even if the default calling conventions differ.

**Comment by daanx** [comment]
Thanks for spotting this. I will add this.

**Comment by daanx** [comment]
Fixed in the latest dev branch
