### ISSUE TITLE
Allocation overriding on Windows with CMake

### ISSUE THREAD

**Issue by seanmiddleditch** [microsoft/mimalloc#85]
The file `alloc-override-win.c` is never included or built on Windows when using CMake. It appears that the file is only referenced at all in the provided `.vcxproj` files, which are not of help to parent CMake projects that are building via `add_subdirectory` (and may not even be using MSBuild anyway but rather Ninja, which is also the default CMake build system in Visual Studio itself these days).

**Comment by daanx** [comment]
Ah yes. I never  used cmake yet to build on windows but always use the Visual Studio solution. We need to add some rules to build this correctly on Windows.
