### ISSUE TITLE
Code comment for `mi_page_t.used` possibly incorrect

### ISSUE THREAD

**Issue by colesbury** [microsoft/mimalloc#861]
The comment for the `used` field in `mi_page_t` says it includes "blocks in `local_free` and `thread_free`". I think the `used` field only includes the blocks in `thread_free`, but not `local_free`.

In other words, blocks in `thread_free` are counted as in-use, but blocks in `free` and `local_free` are not counted as in-use.

https://github.com/microsoft/mimalloc/blob/da520480254b8af2ff9d7bf413d92c46c6db52dd/include/mimalloc/types.h#L298

**Comment by daanx** [comment]
Hi Sam, thanks -- you are right! I'll fix it up.
