### ISSUE TITLE
Override a couple additional C++ delete symbols

### ISSUE THREAD

**Issue by tbwLcFm5uXcAeQ** [microsoft/mimalloc#863]
I found some `delete` symbols in `libstdc++` that are currently not overridden:

```
del_opant.o:  _ZdlPvSt11align_val_tRKSt9nothrow_t
del_opnt.o:   _ZdlPvRKSt9nothrow_t
del_opvant.o: _ZdaPvSt11align_val_tRKSt9nothrow_t
del_opvnt.o:  _ZdaPvRKSt9nothrow_t
```

Should they be overriden?

**Comment by daanx** [comment]
Uh, maybe. Sometimes it does not matter as most of these functions eventually use malloc directly. Do you know the  C++ type signatures of the above functions?

**Comment by daanx** [comment]
Thanks! I merged it in `dev`/`dev-slice`.
