### ISSUE TITLE
[Feature Request] Support of `musl libc`

### ISSUE THREAD

**Issue by enihcam** [microsoft/mimalloc#872]
Please support `musl libc` so it can run on alpinelinux or any mobile/embedded platforms running `musl libc`.

Thanks.

**Comment by daanx** [comment]
It should work with musl on alpinelinux already. Did you use the `-DMI_LOCAL_DYNAMIC_TLS=ON` flag with cmake?

**Comment by daanx** [comment]
Let's continue further discussion in issue #644

**Comment by jirutka** [comment]
It indeed works already on Alpine Linux, we package [mimalloc2](https://pkgs.alpinelinux.org/packages?name=mimalloc2) since Alpine v3.17.
