### ISSUE TITLE
Library versioning

### ISSUE THREAD

**Issue by ranisalt** [microsoft/mimalloc#9]
The cmake install script should install the shared library to `libmimalloc.so.<ABI version>` and point a symlink to `libmimalloc.so`, instead it just installs to the latter. It should also add execution bit to it (chmod 755 instead of 644).

**Comment by ranisalt** [comment]
Packaged it for Arch Linux: https://aur.archlinux.org/packages/mimalloc-git/

**Comment by daanx** [comment]
That is great -- thanks for packaging it! I'll look into how to create symlinks and set execution bits using cmake...

**Comment by ErnyTech** [comment]
We need add SONAME to shared library for guarantee the compatibility of the abi
