### ISSUE TITLE
Azure Pipelines does not run any tests

### ISSUE THREAD

**Issue by gnzlbg** [microsoft/mimalloc#91]
AFAICT Azure Pipelines only checks that the library builds, but it does not run any tests.

Changes to the library should IMO be gated on all tests passing, and probably on checking that running the test suite of some multi-threaded allocation heavy program with a statically and dynamically linked mimalloc also passes.

**Comment by daanx** [comment]
Fixed now in `dev` by adding a stress test that is run on the Linux build -- later will add windows and mac too.

**Comment by gnzlbg** [comment]
Thanks. I don't know of any good allocator "verification" test suite or similar, but if any exist maybe that can be added as well.

**Comment by daanx** [comment]
The best way to test allocators is both unit test the API surface (done by `test-api` but needs more coverage) together with deep invariant checking on a wide range of workloads.  I use the benchmark suite for that now but that is very hard to run in the pipelines (using big programs like Lean and Redis) -- the new stress test is very stressful though :-) It will surely catch any immediate bugs.
