### ISSUE TITLE
Warning C4133

### ISSUE THREAD

**Issue by degski** [microsoft/mimalloc#94]
I had already spotted this in dev, but now it's in master:

    os.c(96): warning C4133: 'function': incompatible types - from 'char [15]' to 'LPCWSTR'
    os.c(113): warning C4133: 'function': incompatible types - from 'char [22]' to 'LPCWSTR'

A narrow c-string is consumed by a function that expects a wide-string (when compiled with `_UNICODE`).

To fix this warning, the most simple is to use the `TEXT()` macro:

    hDll = LoadLibrary(TEXT("kernelbase.dll")); // 96

and

    ok = LookupPrivilegeValue(NULL, TEXT("SeLockMemoryPrivilege"), &tp.Privileges[0].Luid); // 113

This will then also work correctly with `_MBCS`.

`GetProcAddress` (line 99) doesn't need this, as `GetProcAddress` consumes a narrow string (https://docs.microsoft.com/en-us/windows/win32/api/libloaderapi/nf-libloaderapi-getprocaddress), just for the purpose of consistency and added fun ;-) .

**Comment by daanx** [comment]
Thanks -- hope it is fixed now :-)

**Comment by degski** [comment]
Thunderbirds are go! (i.e. yes, it's fixed).
