### ISSUE TITLE
Windows ARM64 support?

### ISSUE THREAD

**Issue by hjyamauchi** [microsoft/mimalloc#941]
Hi,

Does mimalloc support Windows ARM64?

https://github.com/microsoft/mimalloc/issues/482 seems to indicate so but https://github.com/microsoft/mimalloc/blob/dev/ide/vs2022/mimalloc.sln seems to indicate that mimalloc isn't built for Windows ARM64?

Thank you,
Hiroshi

**Comment by hjyamauchi** [comment]
Hi again,

Similar to https://github.com/microsoft/mimalloc/issues/908, would there be a Windows ARM64 support?

A couple of questions:
- It seems that the binaries `mimalloc-redirect.dll` and `mimalloc-redirect32.dll` are provided as binary-only for X64 and X86 and its source code isn't available. Could these be added for ARM64?
- The cmake line https://github.com/microsoft/mimalloc/blob/54940a6a65d28c0d6499490899f6d420b3bb7e24/CMakeLists.txt#L144 might suggest that the same redirect mechanism doesn't work on Windows ARM64. Is it the case?

**Comment by hjyamauchi** [comment]
CC @daanx

**Comment by daanx** [comment]
Just an update: it would be great to have the redirection module for arm64 on Windows as well and we are working on it.

**Comment by hjyamauchi** [comment]
That's great! Looking forward to it!

**Comment by daanx** [comment]
It is there now, see #958

**Comment by hjyamauchi** [comment]
Thank for adding the support!
