### ISSUE TITLE
Build fails with Error evaluating generator expression: $<TARGET_OBJECTS:mimalloc-obj>

### ISSUE THREAD

**Issue by elszben** [microsoft/mimalloc#95]
It is not possible to build master (or the newest release 1.0.3) using cmake.

Full output:

elszben@elx78373ycn:~/Downloads/mimalloc-1.0.3$ cmake .
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No build type selected, default to *** Release ***
-- Override standard malloc (MI_OVERRIDE=ON)
-- Output library name   : mimalloc
-- Installation directory: lib/mimalloc-1.0
-- Configuring done
CMake Error:
  Error evaluating generator expression:

    $<TARGET_OBJECTS:mimalloc-obj>

  The evaluation of the TARGET_OBJECTS generator expression is only suitable
  for consumption by CMake.  It is not suitable for writing out elsewhere.

-- Generating done
-- Build files have been written to: /home/elszben/Downloads/mimalloc-1.0.3

Any idea how to fix it?

Thanks in advance.

**Comment by daanx** [comment]
Replacing `$<TARGET_OBJECTS:mimalloc-obj>` with 
```
${CMAKE_CURRENT_BINARY_DIR}/CMakeFiles/mimalloc-obj.dir/src/static.c${CMAKE_C_OUTPUT_EXTENSION}
```
might fix this. What version of `cmake` are you using? (I usually use 3.10)

**Comment by elszben** [comment]
The proposed workaround works correctly, thanks.
I am using cmake 3.5.1 and I am stuck on a custom 16.04(ish) Ubuntu due to company decisions.
Is there any chance you would support compiling with older cmake?:)

**Comment by daanx** [comment]
Thanks! I think I will just roll back to the cumbersome expression above so it works on more cmake versions :-)
