### ISSUE TITLE
Dev-slice 5cd09ce produces compile errors with VS2022

### ISSUE THREAD

**Issue by jackL999** [microsoft/mimalloc#955]
Using the following command with Visual Studio 2022 produces errors 

`MSBuild.exe` -nologo -v:minimal -m -t:Rebuild -p:Configuration=Release -p:Platform=x64 mimalloc.sln

c:\v\mimalloc\test\main-override-static.c(23,1): error C2059: syntax error: '<<'[c:\v\mimalloc\ide\vs2022\mimalloc-test.vcxproj]
refers to 
`<<<<<<< HEAD`

c:\v\mimalloc\test\main-override-static.c(26,1): error C2059: syntax error: '=='[c:\v\mimalloc\ide\vs2022\mimalloc-test.vcxproj]
refers to
`=======` 

c:\v\mimalloc\test\main-override-static.c(28,1): error C2059: syntax error: '>>' c:\v\mimalloc\ide\vs2022\mimalloc-test.vcxproj]
refers to
`>>>>>>> dev`

c:\v\mimalloc\test\main-override-static.c(258,36): error C2143: syntax error: missing ';' before '{' [c:\v\mimalloc\ide\vs2022\mimalloc-test.vcxproj]
refers to
`static void test_canary_leak(void) {`

c:\v\mimalloc\test\main-override-static.c(246,35): error C1075: '{': no matching token found [c:\v\mimalloc\ide\vs2022\mimalloc-test.vcxproj]
refers to
`static void test_heap_arena(void) {`

**Comment by daanx** [comment]
Ah thanks! I merged incorrectly.
