### ISSUE TITLE
Dev-slice 54c5af5 produces compile errors with VS2022

### ISSUE THREAD

**Issue by jackL999** [microsoft/mimalloc#963]
Using the following command with Visual Studio 2022 produces errors in the file test\main-override-static.c

MSBuild.exe -nologo -v:minimal -m -t:Rebuild -p:Configuration=Release -p:Platform=x64 mimalloc.sln

c:\v\mimalloc\test\main-override-static.c(255,36): error C2143: syntax error: missing ';' before '{' [c:\v\mimalloc\ide
\vs2022\mimalloc-test.vcxproj]
c:\v\mimalloc\test\main-override-static.c(243,35): error C1075: '{': no matching token found [c:\v\mimalloc\ide\vs2022\
mimalloc-test.vcxproj]

**Comment by daanx** [comment]
Thanks! I think it is fixed now :-)
