### ISSUE TITLE
Will mimalloc add support for mallopt?

### ISSUE THREAD

**Issue by asssrias** [microsoft/mimalloc#969]
Like: [https://man7.org/linux/man-pages/man3/mallopt.3.html](mallopt)

**Comment by daanx** [comment]
Probably not since most of those options are super specific to their particular implementation: <https://man7.org/linux/man-pages/man3/mallopt.3.html>, like `M_TOP_PAD` or `MXFAST` etc.  Is there anything specific you would like mimalloc to do that is not covered by the current mimalloc options?
