### ISSUE TITLE
Linker multiple redefinition when using mimalloc-new-delete.h

### ISSUE THREAD

**Issue by jdpatdiscord** [microsoft/mimalloc#973]
Hi, I see your activity as of writing and was just reviewing this for any similar issues.

Non force inlined functions in mimalloc-new-delete.h result in multiple definition linker errors when linking a library that has already included the header into another project which includes it as well.

I apologize if this is basic, but Is there any easy way to fix this with CMake? The function definitions in question are not force inlined despite being simple function definitions in a header.

Examples:
```
  void operator delete(void* p) noexcept              { mi_free(p); };
  void operator delete[](void* p) noexcept            { mi_free(p); };

  void operator delete  (void* p, const std::nothrow_t&) noexcept { mi_free(p); }
  void operator delete[](void* p, const std::nothrow_t&) noexcept { mi_free(p); }
```

Error example:
```
C:/msys64/ucrt64/bin/../lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: STLbuild/libSTL.a(String.cpp.obj): in function `operator delete(void*)':
C:/Users/user/Documents/GitHub/blame-john-engine/STL/tests/build/_deps/mimalloc-src/include/mimalloc-new-delete.h:34: multiple definition of `operator delete(void*)'; CMakeFiles/String.dir/te
stsrc/StringTests.cpp.obj:C:/Users/user/Documents/GitHub/blame-john-engine/STL/tests/build/_deps/mimalloc-src/include/mimalloc-new-delete.h:34: first defined here

```
v2.1.7

**Comment by daanx** [comment]
I think, according to the C++ standard, you are supposed to only have _one_ definition of new/delete when linking -- these are not supposed to be inlined (and the `mimalloc-new-delete.h` should only be included in one source file). Now, that is of course unfortunate if you link various libraries that each have their own definition of new/delete... but that is just the way C++ works I think. (see also <https://stackoverflow.com/questions/8186018/how-to-properly-replace-global-new-delete-operators>).  

Now, I am not a C++ expert so maybe I am wrong about this?

**Comment by res2k** [comment]
I'd also like to point out a source of problems if you'd force-inline the override operators: you might end up with different default memory allocators in different pieces of code!
Imagine you're having your library with force-inline mimalloc operators. Inside the library you have eg a factory function returning a pointer. Now, at some point, you're `delete`ing the that pointer. If you weren't careful and used the _exact same_ allocation operators, you may end up attempting to free them using a different allocator or heap. Ooops!

To me, it seems including the overrides in a static library is fishy.
This should probably not be done; rather, static library code should probably just rely on the application providing appropriate implementations of the allocation operators, if any.
